monkeytypegame/monkeytype

public/js/script.js
Currently, in Safari, whenever you hit the escape key while the text field is focused/focusable, the text `Escape` is appended to the text cursor in the text field.
=> Prevent text input from escape key in Safari

public/css/style.scss, public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
**New Feature** Adds caret option feature.
* 3 additional caret types
* Block
* Outline Block
* Underline
* Adds settings selection of caret
* Adds command line support for caret selection
* Saved as all other preferences are
* Works with all font sizes
* Changed caret animation from color -> opacity to support all caret types
* Changed caret scaling to transform via scale instead of em to support all caret types
* Changed settings buttons to auto columns versus template to scale evenly with any number of buttons
closes https://github.com/Miodec/monkey-type/issues/90 - Add cursor selection feature request
=> Add caret options

public/js/script.js
The window will scroll after the cursors passes text that is beyond the middle of the page, keeping the active text in the middle of the window.
fixes https://github.com/Miodec/monkey-type/issues/67
=> Scroll Longform text

public/js/userconfig.js
This is needed because the theme change claimed about 100ms on my tests. So, when the favicon update runs, there's no change for the root style that what he sees.
I do think could be a better solution to this, but to a temporary solution i think its valid.
=> Add a timeout to call the updateFavicon fn

public/index.html, public/js/commandline.js, public/js/misc.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
Features added:
1. Treats caps lock as backspace if this new setting is on. Caps lock is now emulated on both default and emulated layouts.
2. Adds the capability to "unshift" from upper to lower case with caps lock on. Both default and emulated layouts should now behave as expected for all caps lock-related typing.
Simultaneous bug fixes:
1. Fixes a bug where shifting between upper and lower case would sometimes be wrong while caps lock is on. For example, with caps lock turned on in emulated Colemak, the O key would type lowercase o because it corresponds to a symbol and not a letter in Qwerty.
2. Fixes a bug where pressing the enter key in an emulated layout would result in a console error.
=> Adds caps lock backspace mode and fixes some caps lock bugs.

public/js/script.js
No more imprecise timing! (unless you're cpu-bound or alt-tabbed or something)
Timing is now correct to +/- 3ms. Before, it would sometimes drift to at least +3 seconds per hour.
[Before, 60s](https://i.imgur.com/tnFVJes.png)
[After, 60s](https://i.imgur.com/xa7458d.png)
Even long tests are now free of time drift:
This should also result in more accurate stats.
=> fixed time drift by using a self-adjusting timer

CONTRIBUTING.md, README.md
- Moved "how to contribute" from README.md to CONTRIBUTING.md
- Restructured the original steps for more info, especially with troubles on .firebaserc_example
Not related to any open Issue but saw that the Community Profile under 'Insights' could use a CONTRIBUTING.md so thought I'd help make one. :)
=> Moved notes on contributing to CONTRIBUTING.md

public/css/style.scss, public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
This feature is somewhat the answer for users that wanted immediate feedback to see what they have typed wrong from probably the ff reasons:
- They're keyboard switches exhibits bouncing but they aren't aware yet
- Reading too fast they'll see that they were typing words ahead instead of the current word
- Wanted to be conscious of their mistakes immediately instead of waiting till the end of the session (and likely to make better approaches the next time they encountered the words)
- Helping to realise their stupidity :) <-- me
There might be other reasons, but ultimately I think a number of MT users will appreciate a similar functionality
=> Feature: Indicate Typos

public/css/style.scss, public/index.html, public/js/script.js
Replaces specific typography characters with universal standards.
This is available to the user by a default checked checkbox.
The option is given to the user rather than always automatically applied because:
a) I'm not 100% sure other languages or keyboard layouts do not use these typography symbols as standard inputs.
b) There may be some who enjoy the challenge of entering Shift+Option+[ just to get a fancy quote mark.
=> [#390] Typography Symbols are not mapped to universal keyboard standards.

public/themes/alduin.css, public/themes/list.json
ported from [alessandroyorba's vim colour-scheme](https://github.com/AlessandroYorba/Alduin).
preview:
=> add "alduin" theme

public/css/style.scss
this tweak makes the incorrect word hint be positioned in the middle of the lines and not overlapping the upper or lower lines in any font family or in any font size
=> better hint positioning for all fonts and sizes

public/js/misc.js
This fixes #503.
The added simplePopup had private methods, which totally breaks Firefox and Safari since it's a syntax error and this file then doesn't load at all. We can simply make these methods public, there's no reason they need to be private to work, it's just a code organization thing.
=> Remove private methods from simplePopup (fixes in Firefox, Safari, Internet Explorer)

static/themes/iceberg_dark.css, static/themes/iceberg_light.css, static/themes/list.json
Port of [iceberg.vim](https://github.com/cocopon/iceberg.vim).
Before you merge though, is there any way I can override the color for time/word counter? I find the automatic one not distinct enough on the dark variant.
Previews:
light
dark
(screenshots updated to reflect latest commit)
=> Add Iceberg Dark and Iceberg Light themes

static/index.html
This is a monkey patch that hopefully makes animations smoother at high refresh rates. It simply overrides `jQuery.animate()` with gsap, which claims to be up to 20x faster than jquery. See example speed test https://greensock.com/js/speed.html
The gsap jquery plugin is discontinued. For a more permanent solution, I think we should switch to css animations or (non-jquery) gsap.
=> Adding jquery gsap plugin

static/themes/matrix.css
Fixed issue #635 "Problem: Cannot see anything while using RGB and Matrix theme "
Matrix sub-color changed according to theme
Old matrix theme sub-color: #032700 Luminosity Contrast Ratio: 1.29:1 to #003B00 Luminosity Contrast Ratio: 1.63:1
Rgb theme sub-color: #444444 Luminosity Contrast Ratio: 1.94:1 which has contrast similar to other themes
=> Fix sub-color according to contrast 

static/languages/turkish.json
Fixed hâl to hal because you need to press shift+3+a to type that char which makes it practically very difficult for these kind of tests and also we most commonly type that word "hal".
=> Removed unused turkish char

src/js/commandline.js, src/js/script.js
Appending to the dom in a loop is slow. By simply moving append out of the loop, we can speed up showing the word list, the word history, and the single list command line.
There are other instances of this antipattern in the code, but fixing these three should already have high impact.
=> Optimize appending to the dom

static/index.html
Noticed a missing whitespace in the description for `show all lines` in the settings page.
=> Fix Typo in Settings

static/themes/list.json, static/themes/repose_dark.css, static/themes/repose_light.css
Port of https://github.com/repose-theme/repose
=> Add Repose dark and light themes

src/js/commandline.js, src/js/script.js
Hi!
It was really annoying to not be able to close the command line with Escape when using swap escape/tab. This makes it so Escape always closes it no matter the setting. Tab behavior unchanged.
=> Have Escape always close command line/leaderboard

src/js/script.js
Hi!
Firefox uses Alt for a number of shortcuts, like switching tabs with Alt + N. This makes it so these shortcuts don't start the test.
=> Ignore keys with Alt modifier

src/js/script.js, src/js/userconfig.js, src/sass/style.scss
Hi!
I found the default smooth version too distracting, so I made this! I also think the non-smooth version fits better with the "block" caret style.
I based the setting off of the existing "smooth caret" setting, hopefully everything is covered!
There's 2 parts where I'm not sure if I what I did is optimal:
* [script.js](https://github.com/SeerLite/monkeytype/blob/3a1a31983ed18fe92e16f64ae7ad068fd400f01a/src/js/script.js#L1345-L1349)
* [userconfig.js](https://github.com/SeerLite/monkeytype/blob/3a1a31983ed18fe92e16f64ae7ad068fd400f01a/src/js/userconfig.js#L984-L1002)
Let me know if I should change anything in either of those!
Also, the prettierc pre-commit hook corrected a lot of formatting mistakes in most of the files I edited, but they weren't related to my changes at all. I disabled …
=> Add smooth caret blinking setting

static/languages/code_java.json
Replaced "instanceofinterface" with "interface" in code_java.json
"instanceofinterface" isn't a term, and I'm assuming that it's supposed to be "interface" since "instanceof" is the line directly before.
=> Fixed typo in java language

src/sass/style.scss
Changed from this  
to this
in Firefox, in every other browser it was already done.
=> Removed arrows in firefox in every input field type number

static/themes/carbon.css
Added the missing error extra color, without this it defaults to the text color. 
Also changing the colorful variants to match.
=> Missing --error-extra-color for carbon.css

src/js/script.js
Not sure why I [ask](https://github.com/Miodec/monkeytype/pull/751#issuecomment-757552309) if I'm gonna end up making a PR anyway :p
`!=` so it allows when both modifiers are pressed together
It was originally a one-liner but the formatter split it up like this. Not a fan of how it looks but I'm not sure what the Javascript formatting standards are.
=> Ignore Alt only modifier on Linux

static/themes/stealth.css
File was also formatted with prettier.
**Stealth theme before**
**Stealth theme after**
=> Fix: Timer not visible with new stealth theme #847

static/quotes/german.json
Didn't add a language or theme
(No GitHub issue)
Not a theme.
(Yes, I know I may be fulfilling a stereotype here...)
a6c1ae8: "löschen" is a verb and should therefore not be capitalized in German grammar.
08b236c: "ihr" is singular, "Lehrer" is plural - before, it was saying "their teachers". I checked whether the updated version is the correct version of the quote before commiting.
=> Fixing a typo in a german quote

src/js/script.js, static/index.html
Fixes #863
https://github.com/Miodec/monkeytype/issues/863
When refreshing the page or going back using the browser back button on a route other than "/" you would see a flickering on the animation transition between the main page `pageTest` and the other one. This is caused because the `pageTest` is set to active by default in the html.
This PR aims to fix this behaviour by setting the `pageTest` to `hidden`  and setting the proper classes when the page is loaded.
=> Fix transition on page reload

src/js/script.js
We can instantly reject non trusted events, such as those coming from client-side JS scripts. 
This doesn't fix all cases, but it stops a very simple and major exploit which I was previously able to take advantage of.
=> Fixed Exploit Allowing JS triggered KeyboardEvents

src/js/script.js
Related to #917. I didn't realize the space character was also manually triggered when replacing a newline.
I didn't see an easy way to handle this, so I made it ignore _any_ space character's `isTrusted`. I doubt one can cheat much with only spaces anyway.
An even better way to handle this would be to call one of the functions under `keydown` directly instead of running `trigger`, but I didn't want to mess too much with that and just get this fixed first
=> Treat every space character as trusted

src/js/script.js
If the profile button/icon is clicked while the info is loading you get an error `Missing account data. Please refresh.`
This disables clicking on that icon until the profile has finished loading.
It's easier to test this by throttling requests to "Fast 3G" in Chrome's network tab.
=> Disable clicks on profile icon during loading.

static/themes/_list.json, static/themes/gruvbox_dark.css, static/themes/gruvbox_light.css
Hey there!
I feel like the current gruvbox themes don't really match what people using gruvbox (i.e. me) want to see. The green sub-color especially looks really odd to me and not really appropriate.
In this PR you'll find my proposition for a more gruvbox-like version of both the light and the dark theme.
The dark theme ends up looking pretty similar to the default serika-dark theme, but with actual gruvbox-accurate colors.
=> Better gruvbox themes

src/js/settings.js, src/js/simple-popups.js
This implements the feature discussed in #977.
**Technical changes for `SettingsGroup`**
- Moved code to update the settings to a separate method `setValue`.
- Button actions will not be triggered for buttons with class `disabled` or `no-auto-handle`.
=> Add option to specify a custom font in Settings

src/js/account.js, src/js/script.js, src/js/userconfig.js
Currently the charts always use the font _Roboto Mono_. This is a simple change that applies the selected UI font instead. This makes the appearance consistent.
=> Make chart font follow user settings

static/languages/code_rust.json
It's [`VecDeque`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html), not `VeqDeque`. :)
=> Fix Spelling Mistake In Rust Language

src/js/script.js, static/funbox/_list.json, static/funbox/read_ahead_hard.css
Added read ahead hard funbox. It makes the current and the next two words invisible.
=> added read ahead hard funbox

src/sass/style.scss
Punctuation in right-to-left languages displayed incorrectly.
before the fix:
after the fix:
=> RTL languages - Punctuation

src/js/commandline.js, src/js/script.js, src/js/settings.js, src/js/simple-popups.js, src/js/userconfig.js
This allows the user to type a custom font name into the command input box then press Enter to set a custom font in the _Change font family_ command.
This also fixes an issue where the settings page does not reflect the current settings when directly accessing `/settings`.
=> Enable custom font entry when changing font through the command line

static/quotes/english.json
I noticed that when typing certain quotes in monkeytype, completing the
quote with punctuation wouldn't bring me to the 'finished' screen due
to an extra, hidden whitespace. This PR removes the white spaces from the
english quotes.
=> Removing hidden whitespace after completed quotes

src/js/shift-tracker.js, static/index.html
* update key list to add symbols
Added the symbols that are on the right side of the keyboard and the symbols that are on the left side to their appropriate lists. Left the `^` key because it is neutral.
* Edit opposite shift text
Not all languages use shift for capitalization, so with the added symbols, it doesn't make a lot of sense to say 'capitalisation', so I turned it to 'shifting'.
=> Opposite Shift, update key lists to add their symbols

src/js/userconfig.js
This changes and fixes the following related to the custom fonts feature:
- Fix font names that are not valid CSS identifiers (`8bit` for example) not being applied successfully.
- Prevent font names that would be invalid configuration values from being entered.
- Add notification messages when:
- An empty font name is entered via the command line that resets the font to the default.
- An invalid font name is entered.
=> Custom font fixes

src/js/config.js, static/index.html
So it looks better by default with most theme. With some themes the default
black+0.25 was really hard to see, or just looked really bad.
An alternative way of doing this would be to make the timer color part of the theme, so each theme chooses what color it should use (and then some can keep the default black+0.25 if it looks better)
=> Make default timer color "main" and full opacity

src/js/commandline-lists.js, src/js/settings.js, src/js/test/funbox.js, src/js/test/test-logic.js, src/js/ui.js
Changed how funbox was called to have whatever was selected be saved to a variable. For example, this makes it so when the "nausea" or "space balls" themes (or any future visual theme) are selected in settings they are "saved" but not "active". The settings page does not change and is still usable. This also makes it so that the funbox theme is temporarily disabled going into leaderboards, account, or about pages. Will temporarily disable when results screen is shown as well to address #937
=> Made it so funbox gets temporarily disabled when not taking a test

.firebaserc_example, CONTRIBUTING.md
When I cloned the repository, the .firebaserc_example file was indeed not present. And I noticed that it is frequently deleted by mistake and re-added (see https://github.com/Miodec/monkeytype/pull/819). I believe this is due to the CONTRIBUTING.md instructions (cf https://github.com/Miodec/monkeytype/pull/384#issuecomment-702093486):
> Rename `.firebaserc_example` to `.firebaserc` 
Renaming the file itself will indeed delete it when committing, I updated the sentence so it doesn’t happen anymore.
=> Add .firebaserc_example back and update CONTRIBUTING.md so it doesn’t get deleted anymore

src/js/db.js
Change pace caret for quotes to use average wpm of up to a max of the last 10 quotes completed in target mode if the current quote has never been completed before rather than returning (0 / 0) resulting in undefined (NaN), and displaying an invalid pace caret position in the block in certain situations.
This issue is not listed, but was discovered by me not long ago today.
Reproducing the issue:
1. Set the pace caret mode to "average" in settings.
2. Load up a test in quote mode (any sub-mode is fine).
3. Reload until you find a quote that you have completed before (displaying the average wpm of that quote).
3. Complete the test beating the pace caret so it doesn't disappear before navigating to the results.
4. Start another test, and if the new test quote is a quote you have not …
=> Fixed undefined (NaN) issue with Personal Average Pace Caret when using quote mode

src/js/test/test-logic.js
when restarting test on some specific funbox modes, the test config is not being updated. This fixes it as the test-logic should be calling funbox.funboxSaved and not the active funbox as the active funbox is set to "none' when on the results screen.
this should fix #1250
=> fixed bug with certain funbox modes

src/js/test/test-logic.js
Addressing #1309 
Test logic was calling the currently active funbox when checking for the "Plus one" funbox. Saved funbox will now be called to re-apply "plus one" when restarting test.
=> fixed bug with plus one funbox

static/languages/german_1k.json
After further feedback and help removed two doubles and changed two typos. Also added a . in bzw to give it a bit more sence...
Btw, I am sorry I have to do this so often, but there were some mistakes and I'm an perfectionist...
=> Removed doubles and typos from German 1k

src/js/commandline.js
Possible fix to get theme preview to work? Looks like hover function for items in theme list is not being called for some reason. Moving the call up a few lines of code seems to fix the issue. Maybe clearPreview function is doing something? I am still quite new to javascript so maybe I am missing something idk.
Addresses #1307
=> Fixed theme preview

src/js/input-controller.js, src/js/test/test-logic.js, src/js/test/test-stats.js
This commit addresses the improvement suggested in #966. 
This code works by storing the last time an alpha key or the spacebar was pressed. I decided not to count pressing backspaces or caps locks as 'typing' but this can be changed by adding `TestStats.updateLastKeypress()` to the handling functions in `input-controller.js`. It uses this to create a new, shorter test time which is then used to cut the critical arrays which are used to calculate stats.
=> Ignoring Zen Trailing AFK #966

static/languages/german_10k.json
the name within german_10k.json was still set to german_1k
=> fixed name field within german_10k.json

src/js/popups/word-filter-popup.js, static/index.html
This commit introduces a few changes to the selection of custom filtered datasets:
- The "ok" button has been separated into "add" and "set"; the former doesn't clear the text field, making it easier to combine datasets.
- A few functions have been switched around to fix the loading icon and to circumvent some finnicky behaviour.
- The forEach loop has been replaced with a join; this looks a bit cleaner and is generally more performant.
=> Improved custom prompts.

package-lock.json, package.json, src/js/commandline-lists.js, src/js/theme-controller.js, static/index.html
Allows users to choose to randomize only dark or only light preset themes, preventing unnecessary jarring visual transitions if desired. 
Closes #1386.
=> Implement light and dark theme randomization functionality

static/languages/slovak_10k.json
Fixing a problem: wrong name in slovak_10k.json file. It was my mistake when I was creating the file. I have forgotten to change the name in slovak_10k.json file.
I hope it will work just fine now.
Maclogger
=> Wrong name in slovak_10k.json file

src/js/layouts.js
This is the reference version of the Hands Down layout as found here: http://handsdownlayout.com
For easier reference, the core is:
```
q c h p v   k y o j / 
r s n t g   w u e i a
x m l d b   z f ' , .
```
=> Add handsdown reference layout

static/quotes/german.json
The quote was ugly with that kind of brackets and now it is much easier and much more common.
=> Update Quote German

src/js/commandline-lists.js
This is a continuation of #1504
Hides Power Mode in command line when not searches for, and changes how the power "level" options are displayed to the user in the command line. Of course I'm open to alternate views, but as i mention in my comment on #1504 I feel this is better.
=> Power Mode continuation

gulpfile.js, static/.well-known/security.txt, static/index.html, static/security-policy.html
This pull request adds a security policy to MonkeyType in order to better facilitate responsible vulnerability disclosures, moving them out of GitHub issues and into email/discord. Included in the policy is a `/security-policy.html` page with footer link, as well as a security policy in `/.well-known/security.txt`.  Security.txt is an [Internet Draft](https://datatracker.ietf.org/doc/html/draft-foudil-securitytxt-12) that has been submitted for RFC review, it's stated mission:
> “When security risks in web services are discovered by independent security researchers who understand the severity of the risk, they often lack the channels to disclose them properly. As a result, security issues may be left unreported. security.txt defines a standard to help organizations define the process for …
=> Add Security Policy

static/index.html
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>
On the About page, GitHub is displayed as Github. This is a common spelling mistake, so I fixed it.
Resolves #
=> fix GitHub spelling on about page

src/js/input-controller.js
Added a line to input-controller.js that adds an incorrectLetter event to the replay if stop on word is active and the user attempted to submit an incorrect word.
=> Fix stop on word replay error

src/sass/media-queries.scss
Added a few lines of scss so that the popup for changing the custom text looks cleaner on smaller screens. The left image is the current UI and the right is after the edit. 
<div style="display: flex; align-items: center;">
</div>
I know this is not really important (like, who uses monkeytype on mobile?), but I thought it would be a nice addition, especially since all the other parts of the UI are so nice and clean. Also, I'm thinking of adding more media queries for some other parts (login and leaderboard screens) as well. I'm hoping to get a lay of the land for the codebase before moving on to larger PRs and bug fixes. Thank you!
=> Add media-query for cleaner #customTextPopup for under 1050px and 600px screens

static/themes/_list.json, static/themes/vscode.css
I have added a new theme to Monkeytype, based on VSCode's default dark theme. 
The values are taken from [here](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_vs.json)
=>  Add VSCode Theme (Dark)

gulpfile.js, src/js/input-controller.js, src/js/test/test-logic.js, src/js/test/test-stats.js, src/js/test/weak-spot.js, static/funbox/_list.json
Keeps track of a per-character "weakness" score, basically a moving average of the spacing duration with a penalty for incorrect letters. The weakspot funbox mode uses this to bias towards words with lots of weak letters.
There are a few hardcoded parameters here that I tweaked a bit until it seemed right to me, but could use some work. LMK if there's a better place to put them.
I've only tested it with English; it should work with other scripts but might behave a little weirdly if there are a lot more characters. (It wouldn't break, it just might not make obviously sensible word choices.)
It doesn't persist weakness scores at the moment. Having used it for a bit I actually like it that way, it gives a feel of working on particular things for one session but being able to reset it.
=> Add weakspot mode.

src/js/layouts.js
I've added a few other people's layouts recently, and now I'm asking to add my own I use every day.
https://github.com/Apsu/APT repo with details is here
APT is competitive with other top tier optimized layouts on various analyzers, and the symmetric version is the only other center punctuation layout besides Engram, so I think it's worth a spot here.
=> Add APT layout

src/js/test/weak-spot.js
Gets rid of `defaultScore` (which was hacky), instead makes the learning rate faster at the start so that it's a simple mean for the first `perCharCount` of each letter and an exponential average afterwards. Chars that haven't been seen at all don't contribute to a word's score.
The effect should be that it seems "fairer" with only a small amount of input.
- [] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [] I understand that the maintainer has the right to reject my contribution and it may not get accepted.
- [] If my PR is a new …
=> Improvements to weakspot.

src/js/replay.js
Makes use of jQuery.fn.on 2nd argument selector
(https://stackoverflow.com/a/1207393/6791873).
Apart from being a lot simpler and cross-platform, this also fixes replay
seeking breaking in some strange conditions like having the Firefox
devtools open. Yes, it took me a while to figure that one out.
This, combined with the input rewrite #1325, should fix all replay problems/errors I personally came across.
=> Simplify replay seek click handler

src/sass/style.scss
Fixed range slider thumbs looking weird on firefox. They now have the same styling as in chrome.
=> Fix slider thumbs on firefox

src/js/commandline.js
- Refactor deprecated key codes in `commandline.js` to use its respective keys. For more info, please refer to [this link](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) for more info.
=> refactor(commandline): deprecated keycodes to keys

src/js/account-controller.js, src/js/account.js
When user uses Google Sign In to login for the first time, he is prompted to choose a username. If prompt is closed (cancel pressed), request is sent with `{name: null}`. Check fails and prompt reappears. User is now stuck in this loop, unless a valid username is provided. There might be reasons why user would choose not to proceed with this, so let's provide an option not to. If prompt is closed, break the loop and sign out.
=> Add exit condition for username loop

src/js/test/test-ui.js
Signed-off-by: Alexander Johansen <odyssey346@disroot.org>
This adds date and time of when a screenshot was taken using the Screenshot button in Monkeytype. This fixes #1781. 
It's a bit buggy, sometimes text starts clipping out of screenshot. I'll see if I can fix that
Closes #1781
#1781
=> add time and date of when screenshot was taken

backend/dao/user.js
I noticed that the rate limit for changing name on account was incorrectly set to 30 days in seconds, but Date.now() returns milliseconds, so the limit would actually be 0.03 days instead of the intended 30 days.
The only thing I've changed is multiplied the delay by a thousand so that its in milliseconds.
```
30 * 24 * 60 * 60 * 1000
>> 2592000000
```
=> Fix bug in update name time limit

src/sass/style.scss
Rounded                                        vs               Non-Rounded
Makes it look a bit more modern , can be reduced to 0.5 instead of 0.75 , 0.5 is more subtle.
=> Increase roundness

src/js/exports.js, src/js/global-dependencies.js, src/js/replay.js
Expose a global replay() function to get replay data
This allows the data to be exported for analysis using the console, e.g.
with `copy(replay())`.  I expect it can be used in future as the basis
for the "ttr" file described in the TODO.
As discussed with mio on discord #development
=> Expose a global replay() function to get replay data

src/sass/style.scss
Fixes white borders around color inputs on firefox.
Before:
After:
=> fix color input borders on firefox

static/quotes/english.json
Fixed a Spanish character that was wrong, probably encoding weirdness from a copy paste or something.
=> Fixed spanish 'á' character in quote source

src/sass/style.scss
Changes /src/style.css, changing the properties of the id "leaderboardsWrapper" to fixed instead of absolute so the user doesn't scroll past it.
=> fix(leaderboard): absolute -> fixed

static/index.html
HTML treats newlines as whitespace and collapses it + the spaces down to a single space which has the underline. This fixes this by tightening up the `<span>`s
to
=> Remove extra space in "Sign In" link

src/sass/style.scss, static/fonts/_list.json
This PR adds the [JetBrains Mono](https://www.jetbrains.com/lp/mono/) font hosted on [Google Fonts](https://fonts.google.com/specimen/JetBrains+Mono)
=> Add JetBrains Mono font

src/sass/style.scss
changed background color input border to 2px to match danger zone buttons
=> fix background color input border

.github/workflows/ci.yml
Adds a workflow that on every PR **merge** to **any** branch, runs prettier (`pretty-quick`) to fix the new commits. This should finally fix the issues with formatting coming from PRs made through the GitHub UI or other means that skip the pre-commit hook.
After merging, you should run
```
npx prettier --write .
```
on all active branches to fix all leftover formatting issues.
After this, no more badly formatted code should ever reach master again, which means no more noise diff on unrelated commits :)
Marking as draft until input rewrite is merged so I don't have to fix new formatting conflicts >:)
=> Add GitHub workflow to lint and auto-format PRs

src/sass/popups.scss
Makes the width of the quote search responsive to the width of the screen
This is how it looks currently:
This is how it would look:
(The window is the same size across the screenshots.)
=> Fix quote search popup width

src/js/input-controller.js
Found the root cause for https://github.com/Miodec/monkeytype/issues/2057
Even though the bug is fixed with the change from Mio, typing \` will still keep the accuracy as 100 whereas a wrong character will drop it to 0. This fix will make sure \` will also be counted during calculating accuracy.
=> Incement accuracy even for trailingComposeChars

src/js/account.js
The timeout notification (the one that appears when the user reload the page very often) has a typo on it, more specifically on the word _"enabled"_, which is currently written as _"enalbed"_
=> Fix typo "enalbed" to "enabled"

static/quotes/english.json
A quote had a different type for its `length` field than the other quotes. This broke a parser I was writing.
=> fixed length type for english quote

src/js/test/british-english.js
* Allows words that include punctuation to be matched with the wordlist and replaced. Original punctuation is retained. Fixes cases such as "`gray,`" in quote 1953.
* Fully recapitalises the replacement of entirely uppercase words.
=> Improve British English replacement for edge cases

src/js/test/test-logic.js
Make the handling of the y axis minimum value consistent between different parts of the app.
Closes #
[#2124] opened by me
=> Correct the end of test result chart chopping off values from the 'raw' line

backend/api/routes/config.js, backend/api/routes/leaderboards.js, backend/api/routes/new-quotes.js, backend/api/routes/preset.js, backend/api/routes/psa.js, backend/api/routes/quote-ratings.js, backend/api/routes/result.js, backend/api/routes/user.js, backend/dao/leaderboards.js, backend/middlewares/rate-limit.js
This PR addresses issue #2110 where endpoints would share the same rate limiter.
- All endpoints are now using their respective middlewares
- Created function that pulls the IP Address (rather than copy pasta'ing)
- Assigned generic "too many requests" message for easier referencing
=> fix: endpoints share the same rate limit

static/quotes/english.json
Removes trailing white space and fixes some remaining unicode quotation characters in `english.json`.
I used https://gist.github.com/connorjan/61d12889ffdf2eb372bf38e5fb1d87c2 to perform the fixes.
=> Removes trailing spaces and unicode quotation characters from english.json

static/themes/shadow.css
This change simply fixes the logo and text at the top left of the webpage. The original theme ignores the red novelty and blue text on the keycap set.
=> logo fixed to match gmk shadow novelties

src/js/commandline-lists.js, src/js/config.js, src/js/settings.js, src/js/test/caps-warning.js, static/index.html
This adds the option to disable the capslock indicator that shows when typing. The default option is having it on. The option is under the "behavior" settings group.
=> Add Capslock Indicator Settings Option

CONTRIBUTING.md, backend/example.env, backend/init/mongodb.js
I have added the option to use MongoDB credentials to login to MongoDB. This is for people who have MongoDB locked with a password.
The new `.env`entries are:
1. DB_USERNAME
1. DB_PASSWORD
1. DB_AUTH_MECHANISM
1. DB_AUTH_SOURCE
Closes #
This is a redo of [this PR](https://github.com/Miodec/monkeytype/pull/2167) that doesn't have unrelated changes.
=> Add Option to Use MongoDB Credentials

src/js/test/test-logic.js, src/js/test/test-ui.js, src/sass/test.scss, static/index.html
This PR adds a button that will retry to save a result that has failed to save. The red redo button only shows up when a test has failed to save and will hide itself again when the result has saved. When it has succeeded in saving the result it should remove the click listener. I have tested this by disconnecting from the internet, doing a 10 word test, trying the button, reconnecting to the internet, and trying the button again.
There might be some bugs. For example, the button may activate twice. So this still might need some work.
Closes [#2166](https://github.com/Miodec/monkeytype/issues/2166)
=> Add Retry Saving Result Button

src/js/ui.js, static/index.html
Closes the original issue in #667 by allowing middle/ctrl clicks on menu buttons to open a page in a new tab.
=> change menu buttons to links

src/js/test/wikipedia.js
This PR uses regex to try and replace the missing gap in the wikipedia text. It looks for a word or number that is at least three characters long (to prevent "PH.D" being picked up), followed by a "." followed by a letter (not a number to prevent decimals being picked up). This however is not fool proof, as I have discovered that wikipedia articles are the mother of edge cases and so when I was testing I got this problem.
(The arrow is just so that I know that it was my regex that is changing the text, it is a space in the pr)
I don't think that this properly solves the issue and I don't think that any amount of regex will be able to get all the edge cases but I would say that this is better than before.
Closes #2112
=> Fix for Wikipedia newline issue

src/js/input-controller.js
Closes #2181
This pr doesn't solve the problem in a particularly nice way because it may not be obvious to the user how they failed the test. I am not sure exactly how to solve this one however because it seems that the opposite shift functionality and the master/expert mode are at odds which each other. The idea of the opposite shift settings is that is doesn't type incorrect opposite shifts where as the idea of master mode is a focus on typing EVERY letter correctly. So idk, here's my attempt though.
=> Added functionality so that you fail on incorrect opposite shift for master and expert mode

src/js/test/wikipedia.js
I don't know if what I'm doing isn't great practice but what I'm doing is not taking Wikipedia's way of turning the HTML into text and instead asking for the HTML (removing `explaintext=true` in the URL). Then I replace every instance where there's a new paragraph (`</p><p>`) with a space, and convert the HTML back into text. One problem I see with this is that if there's a pronunciation or a measure with a unit it will remove the space between it (eg. 12 km -> 12km) . This does consistently add the space between paragraphs and does not confuse acronyms, though.
Closes #2112 and extends on PR [#2193](https://github.com/Miodec/monkeytype/pull/2193)
=> Completely Fix Wikipedia Spacing

src/js/test/test-logic.js
A fix for the issue mentioned [here](https://discord.com/channels/713194177403420752/713195089303830548/922167641609744404) and [here](https://discord.com/channels/713194177403420752/713195115275091969/922076092477607996). The changes made in this pr mean the website redirects authenticated users to the submit a quote popup if no quotes exist for the language they have selected.
=> Added redirect to quote submission page when a language has no quotes

src/js/test/test-logic.js
With a large font size or a high word count, the page would go down to the bottom upon restart, this was very annoying for me. So, I added a simple line to scroll to the top of the page after the test restarts.
=> Add scrolling to top after test restarts

static/sw.js
The previous version of the service-worker did not cache any resources other than `index.html`. This version checks where the request is asking for data from and decides to request normally if accessing an api serving dynamic data and caches data returned from routes that are not an api serving dynamic data.
=> update sw.js to properly cache and request

static/sw.js
Fixed google analytics requests being cached when they shouldn't be. If in the future, you want to see which responses are being saved to cache, you can go to the `Storage` tab of the Firefox developer tools and select `Cache Storage` -> `https://monkeytype.com` -> `sw-cache`
=> Added google analytics to no cache list

src/sass/popups.scss
Css properties of button text were set to `transform: 0.25s`. This is invalid and `transition: 0.25s` is likely what the code was intended to say.
=> Correct button text animations

src/js/account/result-filters.js
Load result filters calls a nonexistent function Misc.countAllKeys, causing it to error every time. I'm not completely certain what countAllKeys did but my best guess is that it counts the number of keys in a json object. I replaced the function call with code that counts the number of keys in the object, fixing the issue.
=> Replaced call to nonexistent function Misc.countAllKeys

src/js/elements/new-version-notification.js
Because `sw.js` doesn't check if it's cache is equal to the server's files, cache is not updated when a new version of the site's files are released. Fixed this by clearing cache on page load if working on localhost or 127.0.0.1 and clearing cache if a new version was released on Github.
=> Clear sw-cache if localhost or new version

gulpfile.js, static/sw.js
Multiple things are occuring in this pr, all related to the service worker and caching system
*  Added `event.waitUntil(self.skipWaiting());` and `event.waitUntil(self.clients.claim());`
* These functions stop old service workers and allow the new service worker to take control
* https://stackoverflow.com/questions/41009167/what-is-the-use-of-self-clients-claim 
*  Placed delete caches inside of "activate" event.
*  Caches should be removed and clients.claim() should be run when the sw is activated (first loaded)
* Open cache by name before checking and setting cache for better precision
* Removed "monkeytype.com" and "localhost:5000" from nocache list.
* Now that sw.js is updated after each build and new files are requested, we don't have to request new ones if there was a bad file in an …
=> Fix bug that prevented sw cache from being deleted

static/themes/_list.json, static/themes/dmg.css
Added DMG theme. When typing is active, the menu buttons disappear to leave only one, the power indicator.
Default color settings:
Colorful mode (green errors referencing the screen):
=> Added DMG theme

CONTRIBUTING.md
The link to the LANGUAGES.md file found [here](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md#standards-and-guidelines) is linked to a forked version.
- Updated link to LANGUAGES.md in CONTRIBUTING.md:126
=> LANGUAGES.md in CONTRIBUTING.md links to forked version

frontend/src/scripts/account/all-time-stats.ts
When creating a new account, the total time typing shows `NaN:NaN:NaN`. This PR _**should**_ fix it. See https://github.com/Miodec/monkeytype/issues/2567
Closes #2567
=> display 0 if the time typing is NaN, closes #2567

frontend/src/scripts/test/test-timer.ts
Fixed the layoutfluid timer warnings so that it happens on all amounts of layouts and so that the countdown and switch are accurate.
Closes #
=> Fix layoutfluid timer warnings

frontend/src/scripts/controllers/chart-controller.ts
Keeps the line that the funbox label annotation sits on transparent.
=> Keep funbox annotation line transparent

frontend/static/languages/code_javascript.json
As a frequent user of the Javascript Code prompt, this is just a small nitpick that's been bugging me (pun intended 🙂) for a while. There is no `ondbclick` method or property in the Javascript language. This PR simply fixes the typo in the `code_javascript.json` file to change `ondbclick` to the corrected `ondblclick`.
MDN Link:
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondblclick
I checked `code_javascript_1k.json` to make sure the typo didn't occur in that file, and confirmed that `ondbclick` only exists in `code_javascript.json`.
Love this product and happy to help in any way I can. Please let me know if I missed anything!
Closes #2884
=> Fixes Javascript typo (#2884)

frontend/src/ts/elements/commandline-lists.ts
Now, when user loads challenge, website navigate him to the test mode, so challenge loads properly now. Before that change, user could navigate to settings tab, load the challenge and then it would work weird. It was like typing test in settings. Now this function works good
Also, that will be good if somebody will test this cause I did changes in older website version so that works for me and idk if it will work now
=> load challenge bug fix

CONTRIBUTING.md, backend/docker-compose.yml, backend/example.env, package.json
As discussed: Simple docker compose setup for running redis and mongoDb through docker. Running Redis and MongoDB locally is now as simple as running ``docker-compose up`` (assuming Docker is already installed).
=> Add docker-compose and instructions to README

frontend/static/quotes/english.json
As per [this video](https://www.youtube.com/watch?v=X8HSnP1SiI0), Morshu said that Link should give him *rubies* and he "can't give credit."
=> Fix punctuation and spelling mistakes on Morshu's quote.

backend/src/api/controllers/user.ts, backend/src/api/routes/users.ts, backend/src/dal/user.ts, backend/src/utils/discord.ts, frontend/src/ts/ape/endpoints/users.ts
- Adds an endpoint to get and update a user's associated discord avatar.
- Depends on the implicit OAuth2 grant flow
=> Add get avatar endpoint

frontend/static/themes/_list.json, frontend/static/themes/tron_orange.css
1. Created "tron_orange.css" file in ./frontend/static/themes/
2. Added corresponding hex codes for the theme in ./frontend/static/themes/_list.json
-flip test colors and colorful mode disabled
-flip test colors enabled only
-colorful mode enabled only
-flip test colors and colorful mode enabled
Closes #
=> added "tron_orange" theme

frontend/static/languages/spanish_1k.json
"Barcelona" is spelled with a capital B (such is the case of "Madrid").
=> Fixed a spelling error in Spanish 1k

backend/__tests__/dal/user.spec.ts, backend/src/api/controllers/user.ts, backend/src/api/routes/users.ts, backend/src/api/schemas/filter-schema.ts, backend/src/constants/base-configuration.ts, backend/src/dal/user.ts, backend/src/middlewares/rate-limit.ts, backend/src/types/types.d.ts
As recommended by @Bruception , This PR is for the Backend and will ovveride #3084 
"As a user i would like to be able to save filter configurations to be able to generate mutiple reports"
This PR allows users to create custom filters, which are just `ResultFilter` instances.
Previously the front end would store the `ResultFilter` in the local storage on the browser, however this means only 1 filter can be saved, and it is constantly overriden.
This PR now stores these custom filters in the backend database.
- The user can click on "new filter" at any time and this will create a new custom filter based on the current filters applied.
- The user will be prompted to name the filter
https://user-images.githubusercontent.com/26475724/172541220-47027be5-58a5-49a1-b5f8-36dd72f85b72.mp4
- The …
=> Custom Filters [Backend]

backend/src/api/schemas/filter-schema.ts, backend/src/constants/base-configuration.ts
As raised by @Bruception in #3106 , This PR adds validation to the custom filter names, same as the tage name validation
=> Custom Filters Name Validation

frontend/src/styles/account.scss, frontend/src/styles/popups.scss, frontend/src/styles/z_media-queries.scss, frontend/src/ts/account/result-filters.ts, frontend/src/ts/ape/endpoints/users.ts, frontend/src/ts/constants/default-snapshot.ts, frontend/src/ts/db.ts, frontend/src/ts/pages/account.ts, frontend/src/ts/popups/new-result-filter-preset-popup.ts, frontend/src/ts/types/types.d.ts, frontend/static/html/pages/account.html, frontend/static/html/popups.html
As recommended by @Bruception , This PR is for the FrontEnd and will ovveride #3084 
NOTE: I will rebase this pr onto main once #3105 is merged, so ignore the backend changes in the pr, they are from the previous pr
"As a user i would like to be able to save filter configurations to be able to generate mutiple reports"
This PR allows users to create custom filters, which are just `ResultFilter` instances.
Previously the front end would store the `ResultFilter` in the local storage on the browser, however this means only 1 filter can be saved, and it is constantly overriden.
This PR now stores these custom filters in the backend database.
- When the user clicks on the preset button, the filter preset section opens up
- The user can click on “save filter as preset” which will prompt them to …
=> Custom Filters [FrontEnd]

frontend/src/ts/elements/account-button.ts
- Hide the avatar icon when using an avatar from discord.
- Prevents the avatar icon from being shown underneath a transparent discord avatar
Before:
After:
=> fix: hide account icon when using discord avatar

frontend/webpack/config.base.js, frontend/webpack/config.dev.js, frontend/webpack/config.prod.js
Credits to @devkennyy for leading me to mess around with webpack and fix this 
The `monkeytype.js` bundle has to be included in html files for the webpack live reload to work. I inferred this from the tests. Hence I have began including `monkeytype.js` bundle in html files in `development` mode but not in production mode.
This will provide us with the best of the both worlds as we will be able to enjoy live reload in html files in development mode and not have to bear unnecessary load on the server in production for serving javascript bundles.
=> Fix webpack hot reload not working on html file changes.

frontend/static/html/popups.html
replaced the edit field in edit profile to 'save'. felt a little misleading since we were already editing and should be saving our changes.
=> replaced edit with save

frontend/static/languages/code_haskell.json
=> Fix typo in language `code_haskell`

frontend/src/ts/test/test-ui.ts
Turns out the characters were CSS in the `warnings.html` file. 
Closes #3067
=> fix random characters showing on screenshot

frontend/src/ts/popups/simple-popups.ts
Before this fix you couldn't add themes with " ", and now you can. And also when you make invalid name for your theme, now you don't see popup that theme was updated successfully
=> Custom theme edit fix

frontend/static/html/bottom.html
The Privacy, Security and Terms links in the footer were broken when clicked on a page whose URL is a subdirectory (e.g. https://monkeytype.com/profile/<profile-id>), pointing at https://monkeytype.com/profile/privacy-policy.html, etc. This PR changes the hrefs to absolute rather than relative to fix that.
=> fix the links in the footer for profile pages

frontend/static/terms-of-service.html
Added a space after the link to the privacy policy, so that it doesn't look like this:
=> fixed a typo

frontend/src/ts/elements/commandline.ts, frontend/src/ts/popups/ape-keys-popup.ts, frontend/src/ts/popups/custom-test-duration-popup.ts, frontend/src/ts/popups/custom-text-popup.ts, frontend/src/ts/popups/custom-theme-popup.ts, frontend/src/ts/popups/custom-word-amount-popup.ts, frontend/src/ts/popups/google-sign-up-popup.ts, frontend/src/ts/popups/import-export-settings-popup.ts, frontend/src/ts/popups/new-result-filter-preset-popup.ts, frontend/src/ts/popups/quote-report-popup.ts, frontend/src/ts/popups/quote-search-popup.ts, frontend/src/ts/popups/saved-texts-popup.ts, frontend/src/ts/popups/simple-popups.ts, frontend/src/ts/popups/word-filter-popup.ts, frontend/src/ts/test/practise-words.ts
=> 🗑️Replace deprecated functions

frontend/static/quotes/spanish.json
Replaced en dash U+2013 at quote 103 to one hyphen `-` as the former is difficult to type.
=> spanish quotes: replaced en dash with `-`

backend/src/api/schemas/config-schema.ts, frontend/src/styles/keymap.scss, frontend/src/ts/config.ts, frontend/src/ts/constants/default-config.ts, frontend/src/ts/elements/commandline-lists.ts, frontend/src/ts/elements/keymap.ts, frontend/src/ts/pages/settings.ts, frontend/src/ts/types/types.d.ts, frontend/static/html/pages/settings.html
Added a setting for displaying the top key row in the keymap. 
Three options are available: always show the top row, show it depending on the layout setting or never show the top row. 
I thought this change was necessary as the top row normally pollutes the keymap but for the funbox simon says mode it is necessary to see some other characters( like the ß in qwertz).
=> Added config for displaying the keymaps top row

frontend/static/quotes/english.json
Fixed a small typo in the source of an English quote. Changed `begining` to `beginning`.
`frontend/static/quotes/english.json`, Line `384`
Closes #
=> Fix typo in quote

frontend/src/styles/profile.scss
This PR makes longs words wrap in the profile bio & keyboard fields.
Closes #3365
Before:
After:
=> Fix profile bio issue

frontend/static/languages/spanish_10k.json
=> Fix typo in spanish_10k.json

README.md
I changed the link to the discord bot from https://github.com/Miodec/monkey-bot to https://github.com/monkeytypegame/monkeytype-bot.
=> Update README link to discord bot

frontend/static/themes/blue_dolphin.css
For the blue dolphin theme, when the colourful mode was used, errors were really hard to see.
Colorful mode is on in the above image.
In the above image, the "c" is wrongly typed but it barely looks like it. The reason being the difference between the error color and the main color is too little.  Therefore I suggest a change in the colourful error colour.
Main colour vs **Previous** colourful error colour
Main colour vs **New** colourful error colour
----------------------------------------------------------------------------------
Here's how it looks:
**Before**
**After**
Original colourful error : #ffbde6
New colourful error : #d1a5fd
I tried to keep it with the pastel-like colours that @vimiomori used.
=> Change the error colour in the blue dolphin theme to make it more readable

frontend/src/ts/elements/commandline.ts
=> fix(commandline): Make esc close the commandline when quick restart is set to esc

frontend/src/styles/test.scss, frontend/src/ts/controllers/input-controller.ts, frontend/src/ts/test/test-input.ts, frontend/src/ts/test/test-stats.ts, frontend/src/ts/test/test-ui.ts
other bug fixes and keymaping is in this draft pr: [Korean Keymap #3456](https://github.com/monkeytypegame/monkeytype/pull/3456)
- fixed wpm calculation in ``test-inputs.ts`` and ``test-stats``
- fixed Korean word compiling counting as an input in ``input-controller``.
- fixed corrected history in ``input-controller`` 
- fixed burst calculation ``test-stats``
- now handles Korean characters regardless of language.
Handle Korean in any language
=> fixing wpm and correctedHistory for Korean

frontend/static/languages/catalan.json
The "ñ" letter doesn't exist in catalan, it is written as "ny"
Closes #
=> Correct catalan.json cataluña->catalunya

frontend/static/languages/catalan_1k.json
The "ñ" letter doesn't exist in catalan, it is written as "ny"
Closes #
=> Corrected catalan_1K.json Cataluña -> Catalunya

frontend/src/ts/ui.ts
This PR changes the bottom key tip to just be `ctrl + shift + p` or `cmd + shift + p` based on the detected platform, rather than `ctrl/cmd + shift + p`.
Before:
After (Windows):
=> Change displayed modifier key based on platform

frontend/src/styles/test.scss, frontend/src/ts/test/test-ui.ts
I noticed the "unreached" words at the end of the input burst heatmap use the same styling as the median speed, which is misleading. In this test I never reached "under first":
These words don't have a `.heatmap#` class so they get the default `.word` styling.
This PR de-emphasizes those words:
=> De-emphasize unreached words in burst heatmap

frontend/src/ts/commandline/index.ts
Closes #2361. Fixed command line input bug on android. 
1. Replaced the `keyup` listener with `input` listener on the command line component.
2. Removed meta key checks that won't be needed with `input` listener.
=> Fixed #2361

frontend/src/ts/pages/profile.ts
Fix it automatically changing the url in the url bar (which gets requested if someone reloads the page) to https://monkeytype.com/profile/undefined (which apparently is already the username of an existing user) when going to the profile url of a non-existent user (for ex. https://monkeytype.com/profile/dfjksahjkadfsjhkasfhjkadhjksf ) , by not replacing url state unless the response status is 200
=> prevent redirect to /profile/undefined when going to the page of a non-existing profile

frontend/static/languages/english_10k.json
This removes the word "telecharger" from `english_10k.json`. [_<span lang="fr">Télécharger</span>_](https://en.wiktionary.org/wiki/t%C3%A9l%C3%A9charger) is the French word for _download_, but I can't find any meaning for it in English. It probably slipped into the list because it looks like it plausibly could be an English word.
=> Remove "telecharger" from `english_10k`

frontend/static/quotes/french.json
Hi,
Here is a transformation of the character `œ` which is not mapped on many french layout. It is replaced with `oe`
=> transform œ character which is not on many keyboard

frontend/src/ts/controllers/sound-controller.ts
When the volume of the sound-on-click is set to loud, the 'sine' sound generated through the `oscillatorNode` has an audible 'pop' sound that can be quite distracting. This is most apparent when you go to zen mode and do some keyboard mashing.
The reason there is this pop is that the audio abruptly stops within the function call `oscillatorNode.stop(audioCtx.currentTime + 1);` on line 377 of `sound-controller.ts` without any fading in the volume. 
This problem is outlined in this [StackOverflow post.
](https://stackoverflow.com/questions/29378875/how-can-i-avoid-this-clicking-sound-when-i-stop-playing-a-sound)
This can be solved by implementing an audio fade using the gainNode's function setTargetAtTime(), which [the MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam …
=> Add audio fade to remove audible 'pop' within sine's sound-on-click

frontend/static/themes/dark_note.css
The typing animation was messing the word history. This changes the typing effect only to show up within the wordswrapper
This fix makes them visible again in the history
And the effect remains in tact in the test
=> theme dark note: fix word history display

frontend/src/ts/test/ip-addresses.ts
If the shorter form is preferred, the zero part should instead be the empty string, since it is never written as `...:0:...`.
=> funbox: gave IPv6 addresses' parts leading zeros

frontend/src/styles/core.scss
In some cases when the styles are not loaded yet, the fonts are rolled back to the default 'serif' family which looks very ugly
=> add backup font-family "sans-serif"

frontend/static/quotes/french.json
In french, there is always a space character before ! ? or : punctuation signs. 
This PR fixes the few quotes missing this space character.
=> Fix french punctuation typo - missing space

frontend/src/ts/settings/theme-picker.ts
I left a bug report, issue #3971, which showed how the active theme selection in the theme section of the settings wasn't being properly removed when the user changed the settings. We would have something that looked like this. 
This PR fixes that.
=> Fixed issue #3971 - active theme selection is properly removed

frontend/src/ts/controllers/account-controller.ts, frontend/src/ts/pages/login.ts, frontend/src/ts/popups/simple-popups.ts, frontend/src/ts/utils/misc.ts, frontend/static/email-handler.html
Integrate check for too long passwords into `isPasswordStrong`, and consistently check for it wherever passwords can be created / changed.
As discussed on discord with @Miodec. There was 1 check in place for 25 characters, which could easily be avoided when resetting your password, or changing it in settings.
The max length of 64 is a sure-to-be-safe length that still allows for much safer passwords, but longer lengths should still work fine with firebase.
The login page now also checks for `isLocalhost` to ingore password checks as requested by @Miodec.
There is still some duplication of the password checks where importing the function is not possible, or more info than the boolean result is needed.
=> improve password length check

frontend/static/themes/_list.json, frontend/static/themes/nord_light.css
Adds `nord light` theme. Uses [Nord palettes](https://www.nordtheme.com/#palettes-modularity).
Couldn't find any nordic-vibe light themes, so I though I'd try something myself.
Also had a hard time chossing between `nord7` and `nord15` (see screenshots below). Settled with the former. Let me know your thoughts.
=> Add nord light theme

frontend/static/html/pages/about.html
The about page has a few anchor references to the supporters and contributors that have no corresponding reference location.
e.g.
```html
<a href="#supporters_title">Supported</a>
and
<a href="#contributors_title">expanded</a>
```
=> fix: Add about page supporters/contributors references

frontend/src/ts/commandline/index.ts
Adds support for moving the selection up and down in the command line with ctrl-n/p (emacs) and ctrl-j/k (vim), which is muscle memory for a lot of people but currently unsupported in the main list view people use.
Supporting both feels a lot more natural, and makes navigation easier for people that either don't have arrow keys at all or on their main layer (like myself!)
=> feat: support Emacs/Vim navigation in command line

frontend/static/languages/english_10k.json
I have removed "tion" from the english 10k word list because I was not able to find a definition for it in any dictionary, and as a native English speaker I am not aware of any definition for it. I certainly do not believe that it is one of the ten thousand most used words.
=> Remove the (non-)word "tion" from the English 10k word list

frontend/src/ts/controllers/chart-controller.ts
If accuracy is turned off and either no average lines or only one average line is displayed, after refreshing the page, the accuracy average line(s) are incorrectly displayed.
Closes #
=> Average line(s) are incorrectly displayed

frontend/src/ts/test/funbox/funbox.ts, frontend/src/ts/test/test-logic.ts, frontend/src/ts/types/types.d.ts, frontend/src/ts/utils/misc.ts
The "arrows" funbox starts each test with either a left or right arrow.
Closes #4120
=> "Arrows" funbox starts with left/right only

frontend/static/quotes/english.json
This quote was missing a dot. I added the dot. Quote char length is also updated accordingly. 
:^)
=> fix: added missing dot to quote

frontend/src/styles/caret.scss, frontend/src/styles/test.scss
The comment indicated the same CSS which was written below
Removed 2 CSS comments which had the same style written below.
Like this -  
```diff
- / * property_x: value_y; */
property_x: value_y;
```
It ain't much but it's honest work 🙂
=> REMOVE: Redundant comment in CSS

frontend/src/ts/controllers/chart-controller.ts, frontend/src/ts/pages/account.ts
This pr fixes the problem with the buttons under chart, now they are toggles buttons with their respective color theme
Closes #
*This Pr fix is a fix to the issue [#4124](https://github.com/monkeytypegame/monkeytype/issues/4124)
*use the getConfigChanges function to get the updated values between bd and localstorage
*crea una nueva funcion para cambiar el estado de los botones con su tipado
=> fix:#4124 graph buttons are now toggles

frontend/src/ts/controllers/sound-controller.ts, frontend/src/ts/pages/settings.ts
This PR addresses #4245. 
The error is that `sine`, `sawtooth`, `square` and `triangle` options within the setting's sound-on-click section is (sometimes) not being played. 
This is because the `playClick()` function in line 246 of `settings.ts` responsible for this logic plays the most recent key the user has pressed, instead of being given a fixed codeOverride. This can lead to unpredictable behaviour, and the preview will sometimes play (see #4245 for more detail)
I used `KeyQ` as the codeOverride because that is the same note used in the preview for these sounds in`sound-on-click.ts`, which is responsible for the sound-on-click commandsSubgroup. In that code, they provide the 'KeyQ' override for Sine, Sawtooth, Square and Triangle.
I provide an optional parameter that allows us to …
=> Fixed Settings Sound-on-Click Preview - Sine, Sawtooth, Square, Triangle

frontend/static/html/pages/test.html
Adds `spellcheck="false"` which disables autocomplete on MacOS in Safari.
=> fix: disable autocomplete on MacOS in Safari

backend/src/documentation/public-swagger.json
Fixed an typo at the documentation of monkeytype api. Changed "monketype" to "monkeytype".
=> Fixed an typo at the documentation of monkeytype api

frontend/static/layouts/_list.json
Adds keymaps for the graphite keyboard layout as described [here](https://github.com/rdavison/graphite-layout).
Closes #
=> Update _list.json - Added graphite keymap layouts

frontend/src/ts/test/caps-warning.ts
Closes #4330 
**Issue**: The CapsLock message stayed on Screen even when turned off (by pressing CapsLock) when the focus was outside the test.
**Fix**: The status of CapsLock is now updated even when CapsLock is pressed outside of focus of the test, hence fixing the persistently displayed CapsLock message.
I am typing a word, then pressing <kbd>CapsLock</kbd> to turn it on, then pressing <kbd>Tab</kbd> to move out of focus and then pressing <kbd>CapsLock</kbd> to disable it (and enable and disable it again as you can see in the "After").  Earlier the message on screen stayed being displayed and status of CapsLock was not updated, it is now fixed.
Before:
After:
Thank you!
=> Fix persistent CapsLock message being displayed

frontend/src/ts/controllers/input-controller.ts
Reproducing the issue:
1. Go to monkeytype.com and enter `zen` mode
2. Type some words, then press enter. This will put the cursor on a new line
3. Press backspace to get the cursor back on the previous line
4. Press space
5. Verify the cursor is on a new line
https://github.com/monkeytypegame/monkeytype/assets/6445410/58f86a54-1634-4e7d-9070-e72aee47c46a
The fix:
Pass a `boolean` into `updateWordElement` to determine if the function call came from `backspaceToPrevious`. If it did and the current character is a new line, set `newlineafter` to `false` and remove all existing `.newline` nodes which seems unnecessary for them to exist
https://github.com/monkeytypegame/monkeytype/assets/6445410/1e3dce74-cd2f-4858-9c70-bff6aecd4eb7
Feel free to close if this breaks other functionality that is …
=> Zen mode - removes extra newlines if backspace ends up on a newline

frontend/src/ts/controllers/input-controller.ts
Another small zen mode fix - currently when a user backspaces words, the word count doesn't update in real time
Prod:
https://github.com/monkeytypegame/monkeytype/assets/6445410/640d3828-0d8b-4365-8215-739d826083c6
This branch:
https://github.com/monkeytypegame/monkeytype/assets/6445410/3cac9e50-7e1f-42b6-b4ff-3893b645d897
=> updates word count when backspacing words in zen mode

frontend/src/ts/controllers/chart-controller.ts
The scale of the accuracy average over time(on the last 10/100) line chart wasn't fixed at 0-100 which caused a scale issue in some cases.
Before - the lower line is too low [about 0.25x of what it should have been]:
After:
=> Fixed wrong scale when displaying accuracy average line chart

frontend/static/languages/code_python.json
The word 'capitilise' was found in the `code_python.json`, but it is not a valid Python method or keyword. This commit removes the incorrect word from the list to ensure accuracy and consistency in the provided Python syntax information.
=> removed 'capitilise' from the code_python language

frontend/src/styles/test.scss, frontend/src/ts/controllers/chart-controller.ts, frontend/src/ts/test/test-ui.ts
* Mouse blocks wpm speed while hovering words in input history
* Moved wpm speed above word so that it is not blocked by mouse
* Changed color to sub-alt, cleaner imo
* Changed .wordInputAfter to .wordInputHighlight base class, added .wordInputHighlight--WithSpeed, which can be omitted for highlights not using speed
* Here is the only other time .wordInputAfter was being used. As you can see, it is working perfectly
=> Improve word highlight UI in input history

frontend/src/ts/elements/result-word-highlight.ts, frontend/src/ts/test/test-ui.ts
Bug when user toggles result words and instantly hovers over chart. Occurs because of animation. Waits 250 ms since last toggle before highlighting
https://gyazo.com/ae4eb42efab8dccd8078fdbf448e22ec
=> fixed quick toggle-to-highlight bug

frontend/scripts/json-validation.js
CI prompts when a quote length is incorrect but does not fix it, or print how to fix it.
Print the expected length.
=> ci(frontend/scripts): print expected quote length

frontend/static/themes/rainbow_trail.css
The `monkey see` word couldn't see in rainbow trail theme.
Before:
After:
=> Couldn't see `monkey see` in rainbow trail theme

frontend/static/themes/rainbow_trail.css
Rainbow trail theme is supposed to hide correct words after a while. Previously this was done by setting the color to the background color at the end of the animation. With a custom background set the words will still be visible.
The fix will set the opacity to 0 instead of setting the text color to the background color to hide the text.
=> Fixed rainbow trail theme to support custom backgrounds

frontend/src/styles/test.scss, frontend/src/ts/test/funbox/funbox-list.ts, frontend/src/ts/test/funbox/funbox-validation.ts, frontend/src/ts/test/funbox/funbox.ts, frontend/src/ts/types/types.d.ts, frontend/static/funbox/tts.css
Funbox refactoring
Refactoring of custom css rules and loading of custom css files to reduce the amout of redundant code and have a better code sparation.
1. add funbox mode as class
Remove need for `applyConfig` to set classes on e.g. `#words` and the `Funbox.activate` and `Funbox.clear` methods to cleanup individual funboxes.
Replace this by setting the funbox modes as classes on the body element (e.g. funbox `arrows` adds class `fb-arrows`). The css can now use `body.fb-arrows #words ` instead of `#words.arrows`. 
In addition the body class attribute is only altered if there was a change in active funboxes. Previously this was set on each test restart causing "flickering" in some cases.
2. loading of funbox css
Currently there is a method `applyCSS` on funboxes with needs a custom css …
=> refactor funbox

backend/private/style.css, frontend/src/styles/core.scss, frontend/src/styles/nav.scss, frontend/src/ts/config.ts
As a user who recently started using the web with downloadable fonts disabled, I noticed the experience of Monkeytype is very inconsistent with the normal experience.
This just adds an appropriate fallback font to any font declarations, so the UI is much closer to the experience of someone with downloadable fonts enabled.
The only odd one is `--font: "Roboto Mono", "Vazirmatn", monospace;`, where you have a monospace font, followed by a sans-serif font. For this, I appended `monospace` to the end.
> You should always include at least one generic family name in a font-family list, since there's no guarantee that any given font is available.
> 
> — https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
=> fix: use appropriate fallback fonts (SethFalco)

CONTRIBUTING_ADVANCED.md, package.json
**_Most_** engineers working with Docker Compose, or who have installed Docker Compose since July 2023 should have Docker Compose v2 installed.
For clarity, `docker-compose` is v1, and `docker compose` is v2. Compose V1 is deprecated.
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
> 
> — https://docs.docker.com/compose/
Docker Compose v2 is fully backward compatible with v1, so nothing else needs to change. Could we have the Compose v2 syntax referenced instead?
* Similar to https://github.com/flathub/website/pull/1937
* Similar to https://github.com/nextcloud/cookbook/pull/1772
* Similar to https://github.com/juliushaertl/nextcloud-docker-dev/pull/209
=> chore: use docker compose v2 (SethFalco)

frontend/src/ts/popups/saved-texts-popup.ts
Text saved with space separated words are now loaded with space only.
Fixes #4534
Previous Behavior:
"This is|a test" --save with or without pipe delimiter on--> "This", "is|a", "test" --load with delimiter--> "This|is|a|test"
Fix Behavior
"This is|a test" --save with or without pipe delimiter on--> "This", "is|a", "test" --load with delimiter--> "This is|a test"
=> fix(custom text): resolve incorrect loading of custom text with pipes

.github/workflows/monkey-ci.yml, .github/workflows/pretty-fix.yml
This PR bumps the `actions/checkout` version from `v3` (Node 16) to `v4` (Node 20) as Node 16 has reached eol, additionally, there would be some minor performance improvements in the checkout time of workflow runs.
=> ci: bump actions/checkout to v4

frontend/src/ts/config.ts
Saving config to localStorage after resetting some values.
Closes #4638
=> fix: save confidence mode after setting stopOnError and vice versa

frontend/src/ts/config.ts, frontend/src/ts/controllers/theme-controller.ts, frontend/static/html/pages/settings.html
- Changing manually to a preset or custom theme now turns auto switch theme mode off with a notification. And now the auto switch mode does override the custom theme as well (statement in settings also updated), priority simply given to the last way theme was modified.
- Fixes #4659, that is the footer theme is now correctly displayed with auto switch themes as well.
=> fix: auto switch theme behavior & footer theme indicator

frontend/src/ts/popups/edit-profile-popup.ts
Length checks for GitHub and Twitter are now made before sending server requests. Appropriate notifications are displayed, ~~while continuing the rest of the profile update~~.
Tested with different combinations of updates.
Closes #4653
=> refactor(profile): notify that fields are too long before making a request to the server (sanidhyas3s)

frontend/src/ts/test/test-ui.ts
fix for #4678
Indexes values to create uniform distribution, and prevents negative values from existing in burstmap.
Ranges can be modified by changing the decimal values; current distribution is below and appears similar to what is currently used.
<15%, 15%-35%, 35%-65%, 65%-85%, 85%+
where the percentages refer to the amount of words in a given range
i.e. the lowest ~15% of words are in the lowest range, and the next 20% are the in next, etc.
I believe it's less computationally expensive as well, so there's that.
=> impr(result): rework burst heatmap speed brackets (keenemeck)

CONTRIBUTING_ADVANCED.md
Building with no `export` statement will result following output: 
```
monkeytype-frontend  | [0] ERROR in /monkeytype/frontend/src/ts/firebase.ts
monkeytype-frontend  | [0] ./src/ts/firebase.ts 4:9-23
monkeytype-frontend  | [0] [tsl] ERROR in /monkeytype/frontend/src/ts/firebase.ts(4,10)
monkeytype-frontend  | [0]       TS2459: Module '"./constants/firebase-config"' declares 'firebaseConfig' locally, but it is not exported.
monkeytype-frontend  | [0] ts-loader-default_e3b0c44298fc1c14
monkeytype-frontend  | [0]  @ ./src/ts/index.ts 27:0-21
monkeytype-frontend  | [0] 
monkeytype-frontend  | [0] ERROR in /monkeytype/frontend/src/ts/firebase.ts
monkeytype-frontend  | [0] ./src/ts/firebase.ts 4:9-23
monkeytype-frontend  | [0] [tsl] ERROR in /monkeytype/frontend/src/ts/firebase.ts(4,10) …
```
=> docs: add one key step to configure Firebase

frontend/src/ts/test/test-ui.ts
Screenshot is not working if funbox crt is enabled because html2canvas does not support  "modern" css color functions.
See https://github.com/niklasvh/html2canvas/issues/2700
As workaround disable globalCss before taking the screenshot and apply it after.
Closes #4754
=> fix(result page): cannot take screenshot if crt funbox is active (fehmer)

backend/src/documentation/public-swagger.json
Fix errors in swagger documentation:
- replaced invalid  `basePath` with `host` and `schemes`
- add missing datatypes on arrays
- fix path parameter of  `/users/{uidOrName}/profile` and add missing query parameter
=> fix: Fix swagger documentation

backend/src/constants/funbox-list.ts, frontend/src/ts/test/funbox/funbox-list.ts, frontend/src/ts/test/funbox/funbox.ts, frontend/static/funbox/_list.json
This PR adds a new mode, `ddoouubblleedd`, that causes each letter of each word to be repeated.
I noticed some issues with compatibility detection while implementing this feature. I have chosen to be consistent with the existing state of affairs instead of trying to correct everything in one PR.
- The words produced by the mode are not understandable when pronounced by TTS. However, setting the `unspeakable` property makes the mode incompatible with all other unspeakable modes, which is not desirable. I have not marked the mode as `unspeakable` to be consistent with the existing `backwords` rule, which is also not `unspeakable` despite producing unintelligible text.
- This mode and all other modes that use `alterText`, such as `backwards`, `capitals`, and `rAnDoMcAsE`, are considered to …
=> feat: add mode that doubles each letter to funbox

frontend/static/layouts/_list.json
Added Portuguese from Portugal qwerty layouts, both ISO and ANSI
=> feat: Update _list.json to add Portuguese from Portugal layouts, both ISO and ANSI (diogozarro)

frontend/src/ts/test/words-generator.ts
This PR makes that: 
When using `code_javascript` or `code_javascript_1k` language with punctuation, the word can contain
- \`word-wrapped-in-ticks\` 
- `   (single tick as a word)
This code changes the `punctuateWord` function, adding some conditions for javascript language.
=> impr: add backtick in javascript language when punctuation is enabled (ascodeasice)

frontend/static/funbox/crt.css, frontend/static/themes/chaos_theory.css, frontend/static/themes/dmg.css, frontend/static/themes/dots.css, frontend/static/themes/lavender.css, frontend/static/themes/moonlight.css, frontend/static/themes/snes.css, frontend/static/themes/taro.css
- apply box-shadow on buttons
- fix lavender theme hiding buttons on hover
- update crt mode specific themes not to use nested css
=> fix: crt mode not working on buttons

backend/src/dal/leaderboards.ts, backend/src/server.ts
Add a partial index for each leaderboard containing all users appicable for that leaderboard. The index covers all fields used by the query/result   (covered query), so .we don't need to fetch any documents. The index is pre-sorted by the correct fields (wpm, app, timestamp) so there is no sorting to be done during the query.
=> perf: Improve leaderboard performance by adding better index (fehmer)

backend/src/constants/profanities.ts
removed "d4mn" (previously excluded "damn") for consistency.
=> impr: remove non-profane word

backend/__tests__/dal/public.spec.ts, backend/jest-mongodb-config.js, backend/src/dal/leaderboards.ts, backend/src/dal/public.ts, backend/src/types/types.d.ts
Update the leaderboard and public speedStats directly in mongodb without importing the data into the nodejs process first. 
Local measurements with 2.2M users,  ~230k users applicable to the leaderboard. 
- eliminates  ~400mb of network traffic between mongo and the node
- reduces CPU load on Mongo by ~50%
- reduces CPU load on the node process from ~40% to  less then 1%.
- reduce the overall time to update by ~40%
| **Task**  | **Old Time** | **New Time** |
|-----------|--------------|--------------|
| aggregate | 8.1s         | -            |
| loop      | 0.4s         | -            |
| insert    | 6.7s         | 9.2s         |
| index     | 1.1s         | ?            |
| histogram | 0.01s        | 0.1s         |
| **total** | **16.5s**    | **9.75s**    |
=> perf: improve leaderboard aggregation (fehmer)

frontend/static/html/pages/about.html
Change "amount" to "number" on About page (# of characters is countable)
- none related
=> fix(about): "amount" to "number" (borisnezlobin)

frontend/static/funbox/space_balls.css
The first commit updates the background image URL, resolving an issue where the previous GIF was not loading due to the gfycat service being discontinued.
The second commit hides the Y-axis scrollbar that appears after rotating the page using `transform: rotateX(35deg);`.
=> fix: update the background image and hide the scrollbar in the funbox space_balls (yunfachi)

frontend/static/languages/code_java.json
`throwas` is not a java keyword.
=> fix: remove invalid java keyword  (fehmer)

frontend/static/themes/dark_note.css
=> fix: ligatures not displayed correctly with dark_note theme  (fehmer)

frontend/__tests__/test/lazy-mode.spec.ts
Test for bug in lazy mode not removing accents if the replacement is empty. Fix in commit 1c8b5ff
=> test: add test to remove accents in lazy mode

frontend/static/layouts/_list.json
Added graphite_angle_vc layout to layout emulator.
This is a variant of graphite which is very well optimized for users who are not interested in ever using an ergonomic keyboard. It includes the PK swap on the right hand, the VC swap on the left hand, an XQ swap on the left hand, and then an angle mod which moves X to the center of the keyboard.
The purpose of the VC swap is to leave the C in the original graphite position. This position is very nice for preserving alt fingering compatibility on SC (you can use LM LI). A benefit of having X in the middle of the board is that it is easy to alt XC with LI LM. Also, since this version of the layout is really intended for row stagger keyboards, the position of the letter X on the qwerty B key means that it should be equidistant on both …
=> feat(layouts): add graphite_angle_vc (rdavison)

frontend/static/quotes/spanish.json
I added a letter that was missing from quote id 154 at the Spanish quotes file.
=> fix: typo in spanish quote id 154 (TortitasT)

frontend/static/quotes/portuguese.json
=> impr(quotes): add Portuguese quotes (ikarofelix)

.gitignore, monkeytype.code-workspace
To use [jest extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) in vscode some settings are needed. This PR add a workspace file. To get the extension to work open the workspace file in vscode.
=> chore: configure vscode-jest extension (fehmer)

frontend/docker-compose.yaml
add `user: node` to the `docker-compose.yaml` so docker uses that user instead of the root user when bringing up the container, this makes npm have appropriate rights
=> fix(docker-compose): use the user "node" for the frontend container (dirk-hub)

frontend/src/ts/popups/simple-popups.ts
- The current popup will not close since `<textarea>` tags are not scanned for input values. This made the popup form "incomplete". PR fixes this problem.
- Also made close button appear after timeout.
Closes #
#5016
=> fix: ape key popup close button (andGuo)

frontend/static/quotes/code_assembly.json
=> impr(quotes): Add code_assembly quotes (penguin-teal)

frontend/static/languages/code_c.json
Remove extra `strlen_s` concatenated onto the `strlen` (`strlenstrlen_s` isn't anything) in language Code C.
=> fix(language): two words concatenated on one line (penguin-teal)

backend/__tests__/dal/leaderboards.spec.ts, backend/src/dal/leaderboards.ts, frontend/src/ts/elements/leaderboards.ts, frontend/src/ts/utils/misc.ts, shared-types/types.d.ts
`discordId` and `discordAvatar` should not be `null` on  `LeaderboardEntry`.
=> fix: leaderboard discord properties being null  (fehmer)

frontend/src/ts/pages/login.ts
Sign-up and Sig-In input fields are preserved indicators when the user signs out.
invoked `.hide` on all the indicators when the user performs logged out. So, the previous state of input field indicators gets hidden, and when the user again starts providing details then after the indicators behave again. 
Issue screenshot:
=> impr: Hide input fields indicators on Sign Up page after logged out (underscoore)

frontend/src/styles/test.scss, frontend/src/ts/test/test-ui.ts, frontend/static/html/pages/test.html
=> feat: Add copy missed words to result screen

frontend/src/ts/test/wikipedia.ts
Add the corresponding Wikipedia subdomains to many language groups. I excluded Wikipedias with less than 100,000 articles and Chinese.
=> impr(funbox): add 46 group languages to wikipedia (realcyguy)

backend/src/dal/leaderboards.ts
Try to provide LB results during the LB update. There is a very small time-frame where already running queries might fail during the update. For now we keep the 503 error in this cases and monitor how often this happens on production.
=> impr: provide all-time LB results during LB update (fehmer)

frontend/src/ts/utils/misc.ts
I wanted to practice backtick (grave accent) and tilde, but they are not currently included when the "specials" funbox setting is enabled.
=> impr(funbox): add ` (grave accent, 96) and ~ (tilde, 126) to specials (fitzsim)

frontend/src/ts/commandline/commands.ts, frontend/src/ts/test/test-stats.ts
Add the test words and input history to "copy result stats" data:
```
{
"lastResult": {...},
"wordsHistory": ["people", "little"],        // words to be typed
"inputHistory": ["poelpe", "little"]    // words actually typed
}
```
=> feat: add testWords and wordsHistory to copy result stats

frontend/static/html/popups.html
Use same column width on 15 and 60 seconds leaderboards to fix different row hights.
=> fix: leaderboard tables having different column width (fehmer)

package-lock.json, package.json
Starting monkeytype in dev mode (running `npm run dev` from the root directory) opens the frontend in the browser before the backend is available, causing the current user to be logged out. This is quite annoying during development because you have to login every time.
With the change we wait for the backend to be available before starting the frontend.
=> chore(dev): wait for backend to be ready before starting frontend (fehmer)

frontend/__tests__/utils/format.spec.ts, frontend/src/ts/account/pb-tables.ts, frontend/src/ts/elements/modes-notice.ts, frontend/src/ts/pages/account.ts, frontend/src/ts/popups/pb-tables-popup.ts, frontend/src/ts/test/result.ts, frontend/src/ts/utils/format.ts
use `Math.floor` when displaying accuracy values without decimal places.
Fixes #5114
=> impr: floor accuracy intead of rounding when not showing decimal places (fehmer)

frontend/src/ts/db.ts, frontend/src/ts/elements/last-10-average.ts, frontend/src/ts/test/pace-caret.ts
Personal bests on tags are still broken if the backend is missing the `numbers` flag.
=> fix: fix tags personal bests handling of missing numbers flag (fehmer)

frontend/static/.well-known/security.txt
Changing the expiry date for security.txt to something that isn't already passed.
Unfortunately, the RFC requires having an expiry date. Long-term, there should probably be a better solution than someone manually updating this (or not) every year, but as it's technically broken now I've stuck with the quickest fix again (cf #3074).
=> chore: expire security.txt 2024-06-03

frontend/static/languages/estonian_10k.json, frontend/static/languages/estonian_1k.json
=> fix: remove °C from estonian language (fehmer)

frontend/src/ts/elements/profile.ts
Add mouseover with percentage of test completed and restarts per completed test to the overall typing stats on profile and account page.
=> impr: show total completed test percentage and restarts/test on profile (fehmer)

frontend/src/ts/event-handlers/global.ts
Prevent the print dialog to show up when trying to open the command line with `ctrl-shift-p` on chrome.
=> fix: prevent print dialog to open with ctrl-shift-p (fehmer)

frontend/static/languages/_groups.json, frontend/static/languages/_list.json, frontend/static/languages/code_ook.json
Ook! is a programming language designed for orang-utans. Ook! is essentially isomorphic to the well-known esoteric language [BrainF***](http://www.muppetlabs.com/~breadbox/bf/), but has even fewer syntax elements.
- A programming language should be writable and readable by orang-utans.
- To this end, the syntax should be simple, easy to remember, and not mention the word "monkey".
- Bananas are good.
=> feat: add ook coding language (fehmer)

frontend/src/ts/test/words-generator.ts
Replace the german character [`ß`](https://de.wikipedia.org/wiki/%C3%9F) with `ss` for all variations of swiss german, including `swiss_german_1k` and `swiss_german_2k`.
Initial implementation of the feature resulted from Issue #3699
=> impr: replace ß in all variations of swiss german (Jeanot-Zubler)

frontend/src/ts/controllers/input-controller.ts
fix `enter` not restarting the test while on test page
=> fix: enter quick restart not working on test page (fehmer)

frontend/src/ts/controllers/account-controller.ts
Modify the "Firebase Error : (auth/email-already-in-use)" notification message for better clarity and intuitiveness.
=> chore(message): better error message

frontend/src/ts/utils/misc.ts
changed the main delimiter from "|" to  "," and changed delimiters in "item.charStats" and "item.tags" from "," to ";". This will prevent possible error with csv viewers not registering "|" as the delimiter.
updated from pull request  [#5248] 
[#5248] can now be deleted
=> impr(csv export): change main delimiter from | to , (vjgtigers)

SELF_HOSTING.md, docker/docker-compose.yml
fixes the problem reported in https://github.com/monkeytypegame/monkeytype/discussions/5245
=> fix: self-hosting failing to run without valid serviceAccountKey.json (fehmer)

frontend/src/styles/core.scss
changed the fpsCounter css settings to change the fps text color from the hard coded green/red to theme text/error colors
=> impr: changed fps text color from hardcoded values to match user theme (vjgtigers)

docker/backend/Dockerfile, docker/frontend/Dockerfile
Docker build is hanging for `npm ci` on frontend. Use last working version of the node docker image for now.
=> fix: docker build hanging for frontend (fehmer)

frontend/src/html/header.html, frontend/src/html/pages/account.html, frontend/src/html/pages/profile.html, frontend/src/styles/nav.scss, frontend/src/styles/profile.scss, frontend/src/ts/elements/profile.ts, frontend/src/ts/pages/profile.ts
Added code so when the users mouse hovers over the progress bar the percent complete of that level is displayed
Also:
added "data-balloon-pos="up""  so that the total user xp on profile view will new appear
Closes #
pull [#5269]
messed up the branch when changing and couldn't fix it
on account and profile view page:
on profile view page:
=> impr(profile): add level percentage when hovering over progress bar (vjgtigers)

backend/package.json
Backend dev script `"dev": "ts-node-dev ./src/server.ts -- --inspect --transpileOnly"` doesn't process the flags `--inspect` or `--transpileOnly`.
Changing it to `"dev": "ts-node-dev --transpile-only --inspect -- ./src/server.ts"` as [ts-node-dev](https://www.npmjs.com/package/ts-node-dev) suggests processes both:
> ts-node-dev [node-dev|ts-node flags] [ts-node-dev flags] [node cli flags] [--] [script] [script arguments]
=> build(backend): fix dev script flags not being processed (NadAlaba)

frontend/static/languages/git.json
Adds `@` to the list of git words.
`@` is a commonly used alias for `HEAD`. See the [specifying revisions section](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emem) of the git documentation for further refence.
=> impr(language): Add @ to git words (tjkuson)

frontend/package-lock.json, frontend/package.json
Current version of the vscode [vitest plugin](https://marketplace.visualstudio.com/items?itemName=vitest.explorer) requires `vitest` version `>=1.4.0`.
=> chore: update vitest to 1.5.0 (fehmer)

frontend/src/ts/modals/custom-text.ts
Modified the behavior of custom text input. Previously, when entering `\n\n`, users would get one new line and a `\n` character. Now, I've adjusted it so that entering `\n\n` results in two new lines. This was achieved by appending a space to `\n` characters before other operations.
Closes #5347
=> fix: issue where '\n\n' was not rendering correctly in custom text (SpaceWaffles5827)

frontend/src/ts/utils/misc.ts
Add the low quotation mark („) to the "Remove fancy typography" option. This symbol is common in Eastern European languages and functions the same as American “/British ‘.
=> impr(remove fancy typography): add low quotation mark (K0stov)

frontend/static/themes/9009.css
The css has double `colorful-error-color` and no `error-extra-color`
=> fix(9009.css): removed double colorful-error-color (Taz03)

frontend/src/ts/elements/leaderboards.ts
=> fix(leaderboard modal): language dropdown resets after reopening lb (ykahveci)

package-lock.json, package.json
When backend is in maintenance mode it responds with HTTP status code `503`. `wait-for-localhost-cli` is waiting for `200` before starting the frontend.
Fixed by updating `wait-for-localhost-cli` and passing `--status-codes 200,503`.
=> chore: fix frontend not starting in dev mode if backend is in maintenance (fehmer)

frontend/__tests__/utils/numbers.spec.ts, frontend/src/ts/utils/numbers.ts
For some users too many decimal places are shown on the profile page:
The `user.xp` value for this user is not a `Long` as expected. Result from the `GET profile` call:
```json
{
xp: 14852507.822024472
}
```
While wo do round the XP value to a full number in the [UserDal.incrementXp](https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/dal/user.ts#L604) method this will not fix existing non-long values to be rounded in the database.
This PR fixes the `Numbers.abbreviateNumber` method not handling the `decimalPoints` parameter on values `<1000` but not fixing the inconsistencies in the database.
=> fix: too many decimals showing on profile page for some users (fehmer)

CONTRIBUTING_ADVANCED.md, SELF_HOSTING.md
Use Github Flavored Markdown's blockquote color highlights to make notes and warnings more clear.
=> docs: utilize blockquote color highlights (unrealapex)

frontend/src/styles/inputs.scss, frontend/src/ts/account/result-filters.ts
- **Simplify exclusions:** If a user needed to see results from all funboxes except gibberish, they'd need to select all items one by one except for gibberish, which is a tedious process given that there are almost 40 items to select.
- **Simplify cancellations:** When a user selects more than 20 items, the values shown get replaced by one item `21 selected`, so if a user was seeing the results from 22 funboxes, and clicked on another item by mistake, the only way to cancel that last selection is by selecting the all option, then deleting it, then selecting the 20-something items one by one.
1. Handle typescript errors in a different way from `@ts-expect-error`.
2. Allow deselecting items in the tags, funbox, and language dropdowns of results filters.
Now if all items are selected, all …
=> impr(results filters): allow deselecting options in multiselect dropdowns of results filters (NadAlaba)

SELF_HOSTING.md
Some of selfhosting was written in a laidback style (no caps at the start of a sentence), but it was only like that for small patches around the doc, so I changed the rest to match. Also fixed a typo.
=> docs: fix a typo and apply styling to the whole doc (Warrobot10)

backend/__tests__/api/controllers/user.spec.ts, backend/src/api/controllers/user.ts, frontend/__tests__/elements/test-activity-calendar.spec.ts, frontend/src/ts/elements/test-activity-calendar.ts
- fix graph showing 13 months instead of 12
- graph not showing values older than 12month to fill the first week
=> fix: test activity graph bugs (fehmer)

frontend/src/terms-of-service.html
fixed misaligned tooltip in terms-of-service.html, like #5443 
*see above*
Closes #
=> fix: misaligned tooltip in terms-of-service (extoplasm)

frontend/src/ts/test/test-ui.ts, frontend/static/funbox/tts.css
I am not sure this is on purpose or not. If you choose highlight=off in tts funbox you cannot see what you typed.
=> fix: typed letters not visible in tts funbox if highlight=off (@fehmer)

frontend/static/layouts/_list.json
Gallium v2 is very appreciated and popular layout, would be nice to have it.
It seems this is all what is needed. If not, please let me know.
Layout itself was taken from Alt Layouts discord
```
gallium-v2 (GalileoBlues) (6 likes)
b l d c v  j f o u ,
n r t s g  y h a e i
x q m w z  k p ' ; .
MONKEYRACER:
Alt: 32.63%
Rol: 44.64%   (In/Out: 19.56% | 25.08%)
One:  2.65%   (In/Out:  0.45% |  2.21%)
Rtl: 47.29%   (In/Out: 20.00% | 27.29%)
Red:  2.27%   (Bad:     0.22%)
SFB: 0.85%
SFS: 5.06%    (Red/Alt: 0.81% | 4.26%)
LH/RH: 46.56% | 53.44%
```
=> feat(layout): gallium v2 (AurimasAnskaitis)

frontend/src/ts/test/wordset.ts, frontend/src/ts/utils/misc.ts
Previous zipf index calculation was based on an approximation of the harmonic number that approaches the actual harmonic number near infinity, but does a very bad job at approximating the harmonic number of small values.
This caused the frequency of the first index to be 57% of the actual frequency, and the 2nd index became more frequent than the first one, which caused the word "be" to appear more than the word "the", when it should appear half as much as "the".
New approximation of the harmonic number is slightly better for large values and very much better for small values.
=> fix(zipf): improve approximation of zipf distribution (@NadAlaba)

.husky/pre-push
`nvm use` does not work on nvm-windows, and there is no need for it to run every time anyone pushes to any branch.
=> chore(husky): run `nvm use` only when needed in pre-push hook (@NadAlaba)

frontend/src/ts/elements/test-activity-calendar.ts
=> fix: test activity calendar months having wrong indentation (@fehmer)

frontend/src/ts/test/test-ui.ts
Apply highlight mode in both `"test"` and `"loading"` pages.
On initial page load, the current page is set to `"loading"`, so no highlight mode is applied.
When in `"loading"` page, the active element is yet to be defined, so we should check if we are actually in `"test"` page before calling `updateActiveElement();`
Closes #5507
=> fix(test): apply highlight mode in loading and test (mitjans)

frontend/static/themes/mexican.css
There are some issues with the main and sub-alt color being the same. The PR is changing the sub-alt color to light blue. This changes the UI a lot (test settings, settings page, account page) but keeps the test colors the same, which I think is more important.
- original 
- fixed 
- original 
- fixed 
- original 
- fixed
=> fix: fix mexican theme being unreadable (@fehmer)

backend/src/api/controllers/user.ts, backend/src/utils/misc.ts, frontend/src/ts/ape/endpoints/users.ts, frontend/src/ts/modals/edit-profile.ts
Removes unnecessary consecutive newlines when updating user bio or user keyboard on user profile modal to limit extreme layout stretch. 
Currently only trims server-side then updates the frontend with trimmed values the server returned. 
Blocking multiple newlines on the input felt weird so I decided not to implement it.
Closes #5526
=> impr(server): trim consecutive newlines when updating user profile (theiereman)

backend/__tests__/api/controllers/user.spec.ts, backend/__tests__/dal/user.spec.ts, backend/src/api/controllers/quote.ts, backend/src/api/controllers/result.ts, backend/src/api/controllers/user.ts, backend/src/dal/user.ts, backend/src/types/types.d.ts
Optimize database access for UserDal:
- Only fetch a subset of the document using projection if a small subset of the user document is needed
- Detect missing user by inspecting the `updateOne` result instead of fetching the user first
=> impr: optimize database access for UserDal (@fehmer)

backend/src/api/controllers/dev.ts, backend/src/api/routes/dev.ts
Fix lint warnings during ci-be build:
- `backend/src/api/controllers/dev.ts:272`: 'it' is defined but never used. 
- `backend/src/api/routes/dev.ts:2`: 'authenticateRequest' is defined but never used.
=> chore: fix check annotations for dev routes (@fehmer)

frontend/src/styles/account.scss
Tags button is flashing on load if the current active tags are matching the tags from the result:
Introduced with e29d280.
=> fix: test history tags button flashing on load (@fehmer)

frontend/static/themes/mexican.css
Yesterday I learned that the sub-alt color should be a slightly brighter or slightly darker color of the background.
=> fix: mexican theme sub alt color (@fehmer)

frontend/src/html/pages/test.html, frontend/src/styles/test.scss, frontend/src/ts/controllers/input-controller.ts, frontend/src/ts/elements/modes-notice.ts, frontend/src/ts/test/test-config.ts
Improve keyboard navigation accessibility on the test-config section, improve semantic.
Maybe the fact that we were not able to focus textButtons with the keyboard was on purpose but I think it's more relevant to allow it, especially since in mobile layout it is focusable. I also sometimes accidentally log out because the log out button is just before the text field in the tabindex hierarchy, so it would resolve that small but annoying issue.
impr(test-config section): impossible to navigate with the keyboard in the test-config section (@Truiteseche)
Related issues (doesn't fix it at all):
#4857
=> impr(test config): allow keyboard navigation (@Truiteseche)

backend/__tests__/dal/user.spec.ts, backend/src/dal/user.ts
fix mongo update pipeline leaving behind tmp data
=> fix: cleanup tmp while updating users inbox (@fehmer)

backend/__tests__/dal/user.spec.ts, backend/src/dal/user.ts
- fix non-read rewards being claimed
- claim rewards on deletion
- fix claiming badges can result in duplicate badges in users inventory
=> fix: updateInbox claiming all rewards (@fehmer)

frontend/src/ts/pages/settings.ts
Tooltip is behind the "zipf" funbox button:
=> fix: upside down funbox tooltip not visible on settings page (@fehmer)

frontend/static/quotes/turkish.json
=> feat(quotes): add Turkish quotes from various sources (@turkwr)

.github/workflows/monkey-ci.yml
Only checkout the package-lock.json initially because it is used to fetch the cache.
If the cache is missing checkout all files and run the install to fill the cache.
Reduces the time of prime-cache in case the cache is up to date from ~10 seconds down to one second.
=> ci: optimize prime-cache checkout (@fehmer)

.github/workflows/semantic-pr-title.yml
=> impr(ci): verify pr titles include author name (@rizwanmustafa)

backend/package.json
Activating inspector allows attaching a debugger to an already running node process (npm dev script).
=> build(backend): activate inspector to attach debuggers (@NadAlaba)

.github/pull_request_template.md
New ci action fails if github username isn't prefixed with `@`. So let's tell contributors before hand to do that.
=> fix: pr template to align with new github action (@NadAlaba)

frontend/src/ts/ape/adapters/ts-rest-adapter.ts
Fixes problem with old browsers (e.g. safari from 2022) not supporting `AbortSignal.timeout`.
On old browsers the configured client timeout (usually ten seconds) will be ignored.
=> fix: don't use fetch timeout on very old browsers (@fehmer)

packages/contracts/esbuild.config.js
`esbuild` is outputting build files of packages/contracts in `./dist/src/*`, but other packages are expecting them to be in `./dist/*`, which is happening due to the different Windows path separator `\`.
=> build(contracts): fix output paths for windows (@NadAlaba)

backend/src/constants/funbox-list.ts, frontend/__tests__/utils/generate.spec.ts, frontend/src/ts/test/funbox/funbox-list.ts, frontend/src/ts/test/funbox/funbox.ts, frontend/src/ts/utils/generate.ts, frontend/static/funbox/_list.json
Added a hexadecimal mode to the funbox.
Closes #5620
=> feat(funbox): added hexadecimal (@asasine)

.github/workflows/monkey-ci.yml
Don't download the cache on prime-cache. We only need the  `cache-hit` flag.
Reduces the runtime by six seconds.
=> ci: skip cache download on prime-cache job (@fehmer)

.github/workflows/monkey-ci.yml
Skip the checkout before running paths-filter action on pull requests.
Reduces runtime of `pre-ci` from 13s down to 2s
=> ci: skip full checkout on pre-ci on pull requests (@fehmer)

backend/__tests__/api/controllers/psa.spec.ts, packages/contracts/src/presets.ts
- add tests to verify recordClientVersion is called
- remove tailing slash for `/presets` endpoints
=> chore: add test for recordClientVersion (@fehmer)

frontend/static/languages/filipino.json
Replaced less commonly appearing or less frequently typed word:
bayan → pasok (entry • entrance • admission • school day • work day • going to work)
My bad, I really missed this one out. It was on my list/notes, but I completely forgot about it.
It's been a year or two since I started planning to update some words in the list. So, yeah, this will be my final update on the most common 200 words in Filipino—unless someone requests an update. But I believe that's unlikely, as I've done my best to provide a useful list for everyone.
=> impr: update filipino word list (@Killer8Hyper)

frontend/src/ts/elements/account/result-filters.ts
Result settings getting reset to defaults on page load
Steps to reproduce:
- go to account page
- set filter to last week
- reload the page
=> fix: result filters getting reset on page load (@fehmer)

backend/__tests__/api/controllers/ape-key.spec.ts, backend/src/api/routes/ape-keys.ts, backend/src/api/routes/quotes.ts, backend/src/api/routes/users.ts, backend/src/middlewares/permission.ts
Use `getPartialUser` instead of  `getUser`
=> impr: optimize permissions middleware (@fehmer)

package.json, packages/release/package.json, packages/release/src/buildChangelog.js, packages/release/src/index.js
1. When updating the version, the script is getting current version from root `package.json`, but updating `release/package.json`, so root `package.json` never gets updated and minor will always be zero.
Chosen solution was to get version from root, but update both.
Other possible solution is to not use version in `release/package.json` at all (i.e, get and set version in root only).
**[EDIT]**
Solution changed to removing version from all `package.json` other than root one, and only get and update it in root.
2. Change single quotes in `nodemon --exec '...'` to double quotes.
3. Changes in `buildChangelog.getLog()` are because some shells don't support evaluating subexpressions in `$(...)`.
4. Change root `package.json` version to current version.
5. In commit titles, trailing …
=> fix(release script): not updating root `package.json` version + not supporting some shells (@NadAlaba)

backend/src/constants/funbox-list.ts, frontend/src/ts/test/funbox/funbox-list.ts, frontend/src/ts/test/funbox/funbox.ts, frontend/static/funbox/_list.json
Add instant messaging like typing as described in #5847
- use all lowercase letters
- replace `.` with `enter`
=> feat: add instant messaging funbox (@fehmer)

frontend/src/ts/test/caret.ts
- When getting to a long multi-line word, the caret jumps to the last line of that word instead of the line of the first letter.
=> fix(caret): getting last letter top in long multiline words (@NadAlaba)

frontend/src/ts/constants/default-result-filters.ts
Name can only be 16 characters.
=> fix: result filters defaults invalid (@fehmer)

frontend/src/styles/test.scss, frontend/src/ts/config.ts, frontend/src/ts/test/test-ui.ts
1. When text is a single long multi-line word that takes up all of the screen, `#wordsInput` position will be below the visible screen which requires scrolling down.
- This PR tweaks `#wordsInput` position calculation by considering a `word` height as the height of a single line of a word.
- For visual illustration of this bug see this [video on discord server](https://discord.com/channels/713194177403420752/713195089303830548/1281633634650165278)
2. When a long multi-line word is used in tape mode, this word will wrap to multiple lines causing inability to type the letters which are below the first line.
- The chosen solution was to use `white-space: nowrap` on `.tape .word` elements.
- For visual illustration of this bug see [this](https://discord.com/channels/713194177403420752/71319511 …
=> fix: multi-line words causing issues in ui scrolling and tape mode (@NadAlaba)

frontend/static/themes/dark_note.css
Dots for correct letters are too big:
=> fix: dark note theme dots being too big (@fehmer)

frontend/static/languages/serbian.json, frontend/static/languages/serbian_10k.json, frontend/static/languages/serbian_latin.json, frontend/static/languages/serbian_latin_10k.json
I've specified `rightToLeft`, `ligatures` and `bcp47` attributes in all Serbian files just to make them more understandable.
I suppose that `rightToLeft` and `ligatures` are false by default. Please let me know if I'm wrong.
=> impr(serbian): add more attributes to Serbian files (@rammba)

frontend/static/languages/_groups.json, frontend/static/languages/_list.json, frontend/static/languages/docker_file.json
I've added support for Dockerfile "language" even if it's not the language actually. All words added are listed in the [official docs](https://docs.docker.com/reference/dockerfile/#overview). I've put it to the other group of languages.
P.S. File name is `docker_file.json`, because when I name it `dockerfile.json`, my VS Code detects it as an actual dockerfile. Let me know if name should be changed.
=> impr(dockerfile): add support for Dockerfile language (@rammba)

frontend/src/ts/elements/fps-counter.ts
Fixes the `fps-counter` element showing higher fps when opened multiple times due to multiple loops getting created.
Closes #5989
=> fix: resolve fps counter showing increased fps when opened multiple times (@blru)

frontend/src/ts/modals/simple-modals.ts
Fixed the typo in modal that appeared when trying to revoke all tokens
fixed issue: #6011
=> fix: correct spelling in revoke all tokens modal (@Andotrium)

frontend/static/languages/french_10k.json, frontend/static/languages/french_2k.json
I was doing some typing tests and I noticed the "music" word in the french languages pack. I checked in a dictionnary and that word doesn't exist so I removed it from every package that had that word in it. The only correct existing word is "musique".
=> fix(language): removed non-french from the french language files (@theiereman)

backend/src/constants/funbox-list.ts, frontend/src/ts/controllers/input-controller.ts, frontend/src/ts/test/funbox/funbox.ts, frontend/src/ts/utils/json-data.ts, frontend/static/funbox/read_ahead.css, frontend/static/funbox/read_ahead_easy.css, frontend/static/funbox/read_ahead_hard.css
Makes it easier to recover when not correctly remembering a word
=> impr(read ahead): show words after correcting typo with backspace (@notTamion)

frontend/src/html/head.html
there are two manifest tags in the rendered head, it seems that the `/manifest.json` file already has been added by [vite.config.prod.js](https://github.com/monkeytypegame/monkeytype/blob/ca21b8dc3ae092af2b7140e1e0deeece8bc73130/frontend/vite.config.prod.js#L110)
=> fix: remove the duplicate manifest tag (@malkiii)

frontend/src/html/pages/test.html, frontend/src/styles/test.scss, frontend/src/ts/elements/leaderboards.ts
Clicking on the rank (after getting a better rank in the daily leaderboard) will automatically open the leaderboard modal on the corresponding language screen
Honestly, I mostly added this for me because I like to go to the daily leaderboard after I did a good run and it was annoying me to have to open it + change the language to french + change to daily.
=> feat(result page): open daily leaderboard when clicking the daily leaderboard rank (@theiereman)

frontend/static/themes/dark_note.css
Errors are still shown in blind mode when using the dark note theme.
Fixes #6185
=> fix: blind mode not working in dark note theme (@fehmer)

frontend/src/ts/elements/profile.ts
Make streak hover text when no streak offset is applied consistent with the setting location
The hover text label now properly directs a user to the "Account Settings > Account" section instead of "Settings > Danger Settings" when they don't have a streak offset set.
=> fix(profile): Streak hover text description without a streak offset is now consistent with the setting's location (@wclxb)

frontend/src/styles/media-queries-green.scss, frontend/src/styles/media-queries-purple.scss
Fixed tooltip alignment issue for mobile and tablet views (#6042) and formated the CSS file for improved readability
Closes #6042 
- Updated CSS for better tooltip positioning and formatted the file for readability.
- Tested on mobile and tablet views (images attached below).
=> fix: tooltip alignment issue for mobile and tab views (@HariramakrishnanK)

frontend/src/ts/commandline/lists.ts, frontend/src/ts/controllers/analytics-controller.ts, frontend/src/ts/event-handlers/account.ts, frontend/src/ts/modals/import-export-settings.ts, frontend/src/ts/test/custom-text.ts, frontend/src/ts/test/wikipedia.ts, frontend/src/ts/utils/local-storage-with-schema.ts, frontend/src/ts/utils/url-handler.ts, packages/util/src/json.ts
Replaces raw JSON parsing with schema-based validation across frontend TypeScript files to improve type safety and error handling.
- Updated JSON parsing in:
- `account.ts`
- `import-export-settings.ts`
- `analytics-controller.ts`
- `local-storage-with-schema.ts`
- `url-handler.ts`
- `commandline/lists.ts`
- `test/wikipedia.ts`
- Added schema in `test/custom-text.ts`:
```typescript
export const customTextDataSchema = z.object({
text: z.array(z.string()),
mode: CustomTextModeSchema,
limit: z.object({ 
value: z.number(), 
mode: CustomTextLimitModeSchema 
}),
pipeDelimiter: z.boolean(),
});
```
- Enhanced runtime type safety
- More robust error handling
- Consistent JSON parsing approach
=> refactor: Replace JSON.parse with parseJsonWithSchema (@dev-mohit06)

frontend/static/themes/dark_note.css
Fix the `--roundness` CSS variable override in the Dark Note theme, which incorrectly targets the account menu's first child.
Current look on hover:
The fix adds precision to the selector to avoid targetting `.button`s that are children of `.accountButtonAndMenu`, fixing that very issue.
There might be other places this variable incorrectly impacts, but I don't know the codebase so any insight is welcome. If there's none but still a better/different selector to use, let me know too!
=> style(dark note theme): fix roundness variable affecting account menu (@WarningImHack3r)

frontend/static/layouts/_list.json
It seems to be a pretty popular mod for colemak without additional mods, which is easy to switch to from vanilla colemak, but for some reason nobody added it ;/
https://colemakmods.github.io/ergonomic-mods/wide.html
=> feat(layout): colemak_wide keyboard layout (@papersacculos)

frontend/static/layouts/_list.json
Adding `galite`, a hybrid tweak of GalliumV2, Graphite, and Colemak-DH, with more standard punctuation keys.
The [final version](https://www.reddit.com/r/KeyboardLayouts/comments/1iqo9ob/galite_galliumgraphite_hybrid_with_simplified/) is based on discussion and feedback from a [thread](https://www.reddit.com/r/KeyboardLayouts/comments/1ipdk2t/what_are_the_communitys_thoughts_on_a_gallium_row/) on the AKL community subreddit. 
Repo with details, notes, and stats:  [almk-dev/galite](https://github.com/almk-dev/galite)
=> feat(layout): add galite keyboard layout (@almk-dev)

frontend/src/html/pages/about.html, frontend/src/html/pages/account.html, frontend/src/html/pages/leaderboards.html, frontend/src/html/pages/settings.html, frontend/src/index.html, frontend/src/styles/core.scss, frontend/src/ts/elements/scroll-to-top.ts, frontend/src/ts/pages/leaderboards.ts
- scroll to users position when using the user button
- add scroll to top button on leaderboard page
=> feat: leaderboard scroll to users position when using the user button (@fehmer)

backend/__tests__/api/controllers/leaderboard.spec.ts, backend/src/api/controllers/leaderboard.ts, frontend/src/ts/pages/leaderboards.ts, packages/contracts/src/leaderboards.ts
Show the users ranking for the last day on the daily and for the last week on the weekly leaderboard correctly.
- Fix request query schema for the [daily rank](https://api.monkeytype.com/docs/internal#tag/leaderboards/operation/leaderboards.getDailyRank) having pagination
- Fix request query schema for the [weekly rank](https://api.monkeytype.com/docs/internal#tag/leaderboards/operation/leaderboards.getWeeklyXpRank) missing the `weeksBefore` parameter
- Fix frontend to include the `daysBefore` or `weeksBefore` parameter on `rank` calls
=> fix: past leaderboard not fetching the users rank (@fehmer)

backend/__tests__/api/controllers/user.spec.ts, backend/src/api/controllers/user.ts, backend/src/services/weekly-xp-leaderboard.ts
Ensure user is removed from the weekly XP leaderboards if they either `opt-out`, `reset` their account or `delete` their account.
=> fix: remove user from XP leaderboard if opt-out, reset or deleted (@fehmer)

frontend/src/ts/test/words-generator.ts
This is a followup to PR #6297.
1. `:` is a valid punctuation mark and isn't decided in another if/else branch, so I left it as-is.
2. `;` is also a valid punctuation mark but it is used as a question mark in the appropriate if/else branch. So here I convert it to a period.
Modern greeks use either a period or a comma in place of a middle dot/ano teleia. I would say that a period fits better most of the time.
Closes #
=> fix(punctuation): Add period instead of semicolon for Greek lang (@sledgehammer999)

backend/__tests__/utils/misc.spec.ts, backend/src/utils/misc.ts
Backend was using `Math.floor` on wpm and accuracy while frontend is using `Math.round`. `
Frontend:
[leaderboard.ts:buildTableRow](https://github.com/monkeytypegame/monkeytype/blob/master/frontend/src/ts/pages/leaderboards.ts#L481) -> [format.ts:typingSpeed](https://github.com/monkeytypegame/monkeytype/blob/master/frontend/src/ts/utils/format.ts#L26)
Backend: 
[daily-leaderboard.ts:addResult](https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/utils/daily-leaderboards.ts#L73) -> [misc.ts:kogascore](https://github.com/monkeytypegame/monkeytype/blob/master/backend/src/utils/misc.ts#L69) which is then used in redis for the sorted set.
This was leading to wrong sorting in the daily leaderboard :
=> fix: rounding issues causing daily leaderboard to be out of order sometimes (@fehmer)

frontend/static/layouts/_list.json
After feedback from the AKL community, I have reverted many of the changes made in Galite to the point where it is not meaningfully different from Gallium. As such, Galite is deprecated and no longer supported/recommended. Apologies for the inconvenience.
=> fix: remove deprecated galite layout (@almk-dev)

.eslintignore, backend/private/index.html, backend/private/script.js, backend/private/style.css, docker/backend/Dockerfile, docs/SELF_HOSTING.md
- fixes /configure endpoint not working in docker image because of the missing `private` directory
- adds `export configuration` button to api server configuration
=> fix(docker): fix configuration endpoint, add configuration export (@fehmer)

backend/__tests__/tsconfig.json, backend/scripts/tsconfig.json, backend/src/api/routes/docs.ts, backend/src/api/routes/swagger.ts, backend/tsconfig.json, frontend/__tests__/tsconfig.json, packages/contracts/__test__/tsconfig.json, packages/funbox/__test__/tsconfig.json, packages/funbox/package.json, packages/util/__test__/tsconfig.json
1. fix openapi specification path so that /docs endpoint would work on dev.
> Error: ENOENT: no such file or directory, stat 'backend/src/static/api/public.html' Stack: Error: ENOENT: no such file or directory
2. fix openapi specification path so that API Operation would work on /stats endpoint on dev.
> Cannot read openApi specification from backend/src/api/routes/../../static/api/openapi.json. Swagger stats will not fully work.
3. remove unneeded `files` & `ts-node` options from `tsconfig.json` in various places.
> File 'backend/src/types/types.d.ts' not found.
The file is in the program because:
Part of 'files' list in tsconfig.json
4. add the missing `pnpm test` script to the funbox package.
=> build: fix openapi spec path for docs & stats endpoints on dev (@NadAlaba)

.github/workflows/ci-failure-comment.yml, .github/workflows/monkey-ci.yml, .github/workflows/semantic-pr-title.yml, .github/workflows/write-labels.yml, packages/release/src/buildChangelog.js
1. remove duplicate correct examples in semantic-pr-title error message, and make the examples more diverse (show how to credit multiple contributors).
2. make the scope (quotes, languages, ...) consistently plural across the repo docs (A subjective change I know, but in the changelog, the scope looks better when it is plural i.e. **quotes:** add various quotes).
3. update deprecated action `upload-artifact` from v3 to v4, because it was making the `ci-failure-comment` workflow fail.
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
4. use the same official action to download and upload artifacts across the repo's …
=> chore(workflows): update deprecated action and remove duplicate workflow message (@NadAlaba)

frontend/src/ts/controllers/theme-controller.ts, packages/contracts/__test__/schema/config.spec.ts, packages/contracts/src/schemas/configs.ts
=> fix: protect against stored xss in custom background url (@fehmer)

.github/workflows/ci-failure-comment.yml
change the name of the input action that should've been changed in #6344 when the action was changed.
Sorry!
=> chore(workflows): use correct name of action input (@NadAlaba)

backend/docker/compose.yml, frontend/docker/compose.dev.yml
Global install of pnpm is not working as user  `node`. As a workaround we add `pnpm` during the build phase of the image and run the entrypoint as user  `node`
=> fix: local development using docker not working with pnpm (@fehmer)

frontend/static/layouts/_list.json
This PR adds the [Hands Down Promethium layout](https://www.reddit.com/r/KeyboardLayouts/comments/1g66ivi/hands_down_promethium_snth_meets_hd_silverengram/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
=> feat(layout): Adds Hands Down Promethium layout (@andre-krueger)

pnpm-lock.yaml
- bump the `vite` version that `vitest` uses from 5.2.14 to 5.4.17 to get the fix vitejs/vite@14b5ced for this warning when running multiple tests simultaneously (as in `pnpm test-pkg` or `pnpm test`):
> WebSocket server error: Port is already in use
=> chore(deps-dev): bump vitest's vite fom 5.2.14 to 5.4.17 (@NadAlaba)

frontend/src/ts/controllers/quotes-controller.ts, frontend/src/ts/utils/json-data.ts
because vite dev server does not throw a 404 when fetching a non existing json document, but responds with an html document and a 200 status code
=> chore: throw error when response in fetchJson() is not json (@NadAlaba)

frontend/src/ts/controllers/badge-controller.ts
RGB rainbow effect is disabled if user prefers reduced motion. Currently the badge is then only shown in the default color. This PR adds a background with the rgb effect.
Before:
After:
=> impr: use rainbow effect on rgb badges for reduced-motion (@fehmer)

frontend/src/ts/controllers/theme-controller.ts
If the specified background image is invalid, then we can hide it using `this.style.display='none'`, which will also hide the default white outline and broken image icon
Also fixed a typo in the notification for it (temporairly -> temporarily)
Tested fix by entering invalid custom background URL in settings (i.e. `https://tehtuhgsfdsfjsdg.com/test.jpg`)
Closes #6524 
Thanks!! :)
=> fix: stop broken background images from displaying (@mattlau1)

frontend/src/ts/modals/edit-profile.ts, packages/contracts/src/schemas/users.ts
=> impr(profile): validate inputs for twitter, github and website (@fehmer)

frontend/src/ts/pages/settings.ts
Prevent user from deselecting all layouts/languages in customLayoutfluid and customPolyglot selects.
Fixes FRONTEND-MW and FRONTEND-MS
=> impr(settings): prevent customLayoutFluid and customPolyglot to be empty (@fehmer)

frontend/.eslintrc.cjs, frontend/package.json, pnpm-lock.yaml
=> chore: add eslint compat plugin (@fehmer)

frontend/static/themes/chaos_theory.css
fix the transition animation for the theme palette icon in the chaos_theory theme.
hovering over the current theme button would trigger a smooth 180° flip of the palette icon. However, when quickly moving the cursor away, the icon would abruptly snap back to its original position instead of transitioning smoothly.
https://github.com/user-attachments/assets/55b6683a-c83b-4f93-806b-bf289bf30c5f
-------------
https://github.com/user-attachments/assets/59d08d45-ba2d-4921-9cc4-ee84455a0571
=> fix: smooth transition for theme palette icon in chaos_theory theme (@byseif21)

frontend/src/ts/controllers/page-controller.ts, frontend/src/ts/pages/profile.ts
Add Open Graph meta tags to user profile pages to improve how they appear when shared on social media platforms. This includes title, description and URL meta tags.
Closes #6597
This PR adds Open Graph Protocol (OGP) meta tags to user profile pages to fix the issue with LinkedIn and other social media platforms incorrectly redirecting profile links to the homepage. The implementation:
- Adds dynamic Open Graph meta tags for title, description and URL
- Updates tags whenever a profile page is loaded
- Uses the user's name in the title tag for better personalization
Closes #6597
=> feat(profile): add Open Graph meta tags for social sharing (@TryOmar)

backend/package.json, backend/src/app.ts, backend/src/utils/etag.ts, pnpm-lock.yaml
If frontend and backend are deployed with a new COMPATABILITY_CHECK header frontend might show the backend version is lower because of the http header of a cached response.
Adding the COMPATABILITY_CHECK version as part of the etag fixes this.
=> fix: compatability check header shown if client is using cached responses (@fehmer)

frontend/src/html/pages/settings.html
The is minor but I think it should be "typing test" not "type test"
=> style: correct text in difficulty settings descriptions (@byseif21)

frontend/src/ts/commandline/commandline.ts
Previously, when selecting a language via the text button on the test page, the checkmark (fa-check) in the commandline language list wouldn't update until a page refresh. This was due to the commandline's caching mechanism not detecting changes triggered outside its own control.
Although it first appeared to be a language-specific issue, it was later identified that the caching logic was generally insufficient — it didn’t account for updates to the active command state or configuration flags like usingSingleList.
Fixed the caching logic in the commandline module by tracking a more complete internal state. The system now correctly detects changes in the command list, active state, and configuration, and rebuilds the list UI when necessary.
- The commandline uses a caching mechanism …
=> fix(commandline): improve caching to fix stale checkmark and UI state (@byseif21, @fehmer)

frontend/src/ts/controllers/theme-controller.ts
Closes #6616 
Changes:
- Refactored theme preview state management to use a single state object
- Removed redundant state variables
- Maintained the same debouncing behavior for smooth scrolling
=> fix(theme): wrong theme application during preview (@byseif21)

frontend/src/ts/config.ts
* It was possible to add duplicate languages to Polyglot mode or duplicate layouts to Layoutfluid mode via the command line
* Prevent duplicate entries in Polyglot and Layoutfluid configs by deduplicating values before saving, ensuring unique values regardless of input source.
=> fix(commandline): prevent duplicate entries in Polyglot and Layoutfluid funbox modes (@byseif21)

frontend/src/ts/controllers/input-controller.ts
Fixes the keymap UI not highlighting the current letter to be typed when backspaced to a previous word in layout emulator.
https://github.com/user-attachments/assets/12ba72d8-567b-4097-bbf6-407814140545
=> fix(input-controller): update keymap UI on backspace in layout emulator (@47th)

frontend/src/html/pages/settings.html, frontend/src/styles/animations.scss, frontend/src/styles/settings.scss, frontend/src/ts/elements/settings/settings-group.ts, frontend/src/ts/event-handlers/settings.ts, frontend/src/ts/pages/settings.ts, monkeytype.code-workspace, packages/contracts/src/schemas/configs.ts
Allow to deep-link to  a specific config setting.
Users in discord often ask how to enable a specific setting. Instead of guiding them manually to the correct settings we can use a deep-link:
https://github.com/user-attachments/assets/90b99660-13ae-49bf-8ff2-c5e6da290070
Added a link next to the group on mouse over to copy the deep link to the clipboard:
=> feat(settings): Add deep links to specific sections (@fehmer)

backend/src/api/controllers/result.ts, backend/src/dal/leaderboards.ts, frontend/src/ts/pages/leaderboards.ts
We added `minTimeTyping` to the configuration but it was only used to create the indicies.
=> fix(leaderboard): use minTimeTyping from configuration (@fehmer)

frontend/src/styles/settings.scss
Highlight was not visible if the user has prefers-reduced-motion enabled.
=> fix(settings): fix highlight not visible with reduced-motion (@fehmer)

frontend/src/html/pages/leaderboards.html, frontend/src/styles/core.scss, frontend/src/styles/leaderboards.scss, frontend/src/styles/media-queries-brown.scss, frontend/src/styles/media-queries-gray.scss, frontend/src/styles/media-queries-purple.scss, frontend/src/styles/media-queries.scss, frontend/src/ts/pages/leaderboards.ts
* when the table got wider than the screen, it broke the layout and pushed other elements out of view.
fixed it by `overflow-x: hidden`
* making the table itself more responsive, so it adapts across screen sizes
* video ; 
https://github.com/user-attachments/assets/c84272d1-4c77-4e59-980e-aab09c18d6a1
Closes #6732
=> fix(leaderboards): content overflow on smaller screens (@byseif21, @miodec)

frontend/src/html/pages/settings.html, packages/contracts/src/schemas/presets.ts
**`impr`** - Clarified description for "Reset Settings" feature, emphasizing that in addition to tags, settings presets are also preserved.
**`refactor`** - the unused type `PresetName` was misspelled as `PresentName`.
=> impr(settings): clarified 'reset settings' wording (@SamLonneman)

frontend/static/quotes/code_rust.json
*   Fixes various compile errors in the Rust quotes.
*   Removes trailing whitespace.
*   Converts leading whitespace to tabs.
Note: This does not fix out of date issues (such as the rand API), or the likely unnecessary uses of `extern crate` (since rust 2018).
=> fix(quotes): code_rust compilation and whitespace (@nafets-st)

frontend/src/styles/account.scss, frontend/src/styles/animations.scss, frontend/src/ts/pages/account.ts
fix the highlight animation for the account history table (when clicking a chart dot) was not visible or only worked inconsistently. This was because the animation was applied to the <tr> element, but the background color for table rows is set on the <td> elements. As a result, the animation was hidden by the static background color of the table cells.
Closes #
=> fix(account-history): highlight animation is not working on result selection (@byseif21)

packages/funbox/src/list.ts
I've changed the difficulty of the `layout_mirror` funbox from 1 to 3.
The `layout_mirror` funbox completely mirrors the keyboard layout, significantly increasing difficulty compared to other funboxes currently labeled as difficulty level 1, (`earthquake`, `capitals`, `gibberish`), which are much less disruptive.
The `layout_mirror` funbox is also similar to the `mirror` funbox (which mirrors the screen), currently rated at difficulty level 3. Since `layout_mirror` alters the entire keyboard layout itself, making even basic typing extremely challenging, it makes sense for it to also be difficulty level 3.
=> chore(funbox): increase layout_mirror difficulty to level 3 (@ShizukoV)

docs/SELF_HOSTING.md
Improved grammar, structure, and tone of the `docs/self_hosting.md` file for better clarity and consistency. Changes include fixing typos, rewording vague instructions, improving formatting, and aligning with the overall documentation tone.
This PR does not add any quotes, languages, themes, or layouts.
---
Closes # (none)
=> docs(self-hosting): improve grammar and structure of setup guide (@nitin-is-me)

frontend/static/themes/incognito.css, frontend/static/themes/rainbow_trail.css, frontend/static/themes/sewing_tin_light.css, frontend/static/themes/suisei.css
all themes that use `background-clip: text` should have the `padding-bottom: 0.1em` to prevent the cut logo letters.
=> fix(themes): clipped logo letters in some themes (@byseif21)

frontend/src/styles/settings.scss
On the settings page
- theme -> custom add a margin to the left of the color picker
- buttons/input on the right side align with the top of the text on the left side
=> fix(style): fix visual problems (@fehmer)

frontend/src/styles/core.scss, frontend/src/ts/modals/edit-result-tags.ts, frontend/src/ts/pages/settings.ts
tooltip pop-ups were reappearing on click when interacting with various clickable elements (e.g., tags in results table, test result buttons, account page actions).
=> fix(tooltips): prevent hover pop-up reappearance on click (@byseif21)

frontend/src/ts/commandline/commandline.ts
* When leaving a theme item to a non‑theme item inside the mixed commandline list, the preview theme temporarily applied after closing the commandline without selecting it. so switched back to clearPreview() as it was,
* and to fix the preview flashing issue that the false was added for, in custom themes included setCustomThemeId with changeTheme in the check , so custom theme hovers are now treated as the same preview context and no longer clear the preview between items.
=> fix(commandline): prevent false theme apply during perview (@byseif21)

frontend/src/ts/constants/default-snapshot.ts, frontend/src/ts/db.ts, frontend/src/ts/pages/account.ts, frontend/src/ts/test/test-logic.ts, frontend/src/ts/utils/debug.ts, frontend/src/ts/utils/results.ts
Introduced in #6865, caused by account button reacting to the `snapshotUpdate` triggered by `addXp` function.
Fixed by merging result related snapshot functions into one and adding a `noDispatchEvent` param to `setSnapshot` and using it in the new function and `addXp`. This works because result and alerts panel both call the `XPBar.update` directly to animate the xp gain.
=> fix(navigation): level up animation showing wrong level (@miodec)
