monkeytypegame/monkeytype

frontend/webpack/config.base.js
frontend/webpack/config.dev.js
frontend/webpack/config.prod.js

Refactor webpack configs

---

backend/src/api/controllers/result.ts
backend/src/dal/leaderboards.ts
frontend/src/ts/elements/leaderboards.ts

Disabled time typing requirement on dev

---

frontend/webpack/config.base.js

we are manually rebuilding so we shouldn't inject
Closes #3172

fix webpack reloading twice

---

frontend/webpack/config.base.js

Fix webpack config

---

frontend/src/ts/elements/account-button.ts
frontend/src/ts/elements/leaderboards.ts
frontend/src/ts/elements/profile.ts
frontend/src/ts/ready.ts
frontend/src/ts/utils/misc.ts

Fix leaderboard avatars

---

frontend/src/ts/account/pb-tables.ts

Fix consistency bug

---

frontend/webpack/config.base.js
frontend/webpack/config.dev.js
frontend/webpack/config.prod.js

Webpack configs housekeeping

---

frontend/src/ts/elements/profile.ts

Refactor some code

---

backend/src/documentation/public-swagger.json

remove monkeytype-js from the docs

---

backend/__tests__/dal/user.spec.ts
backend/__tests__/utils/misc.spec.ts
backend/src/api/controllers/user.ts
backend/src/api/routes/users.ts
backend/src/dal/user.ts
backend/src/types/types.d.ts
backend/src/utils/misc.ts
frontend/src/styles/popups.scss
frontend/src/ts/ape/endpoints/users.ts
frontend/src/ts/controllers/badge-controller.ts
frontend/src/ts/elements/leaderboards.ts
frontend/src/ts/popups/edit-profile-popup.ts
frontend/src/ts/types/types.d.ts
frontend/static/html/popups.html

Still need to update inventory correctly on the backend

Inventory badge selection

---

backend/__tests__/utils/misc.spec.ts
backend/src/dal/leaderboards.ts

Fix leaderboard update bug

---

frontend/static/quotes/english.json

Add quotes by Pierce Brown from [Goodreads](https://www.goodreads.com/author/quotes/6474348.Pierce_Brown)

Add quotes by Pierce Brown

---

backend/src/dal/leaderboards.ts

Fix all time lb again

---

frontend/src/styles/popups.scss

fix popup style inconsistencies

---

backend/src/dal/user.ts

- Removed various UpdateResult that were not being used
- Optimized update name operation by reducing round trips

Refactor Users DAL

---

frontend/src/ts/controllers/badge-controller.ts

Badge for note-worthy content creators:
Taeha Types
Alexotos
Glarses
etc.

Add content creator badge

---

frontend/src/styles/popups.scss
frontend/src/ts/controllers/captcha-controller.ts
frontend/src/ts/popups/quote-report-popup.ts
frontend/src/ts/popups/quote-submit-popup.ts
frontend/static/html/popups.html
frontend/static/main.html

doesn't actually work because recaptcha is a joke. should we try v3?
Closes #3152

rework captcha

---

frontend/static/quotes/code_python.json

Add 20 more Python quotes (id: 9-28)

---

frontend/static/quotes/code_c++.json

Add 30 more C++ quotes (id: 3-32)

---

frontend/src/ts/popups/custom-text-popup.ts
frontend/src/ts/popups/quote-report-popup.ts
frontend/src/ts/popups/simple-popups.ts

remove fullstops from alerts

---

backend/jest.config.ts
backend/package-lock.json
backend/package.json
backend/private/script.js
backend/src/api/routes/ape-keys.ts
backend/src/api/routes/configs.ts
backend/src/api/routes/leaderboards.ts
backend/src/api/routes/presets.ts
backend/src/api/routes/psas.ts
backend/src/api/routes/quotes.ts
backend/src/api/routes/results.ts
backend/src/api/routes/users.ts
backend/src/app.ts
backend/src/constants/base-configuration.ts
backend/src/constants/monkey-status-codes.ts
backend/src/middlewares/ape-rate-limit.ts
backend/src/middlewares/auth.ts
backend/src/middlewares/error.ts
backend/src/middlewares/rate-limit.ts
backend/src/types/types.d.ts
backend/src/utils/error.ts

Add new rate limiting flow

---

frontend/static/quotes/spanish.json

I added some legendary carl sagan quotes about earth, in spanish

Added spanish quotes

---

frontend/static/layouts/_list.json

As defined on https://workmanlayout.org/
Adds the workman for programmers layout.

Added prog_workman layout

---

frontend/static/quotes/french.json

Added one quote to the french list of quotes

Added 1 french quote

---

backend/src/middlewares/auth.ts

Refactor auth

---

backend/package.json
backend/src/version.ts
frontend/package.json
frontend/webpack/config.prod.js

Add version commit hash

---

backend/src/constants/profanities.ts
backend/src/utils/validation.ts

- Precompute profanity patterns

Add minor optimization

---

QUOTES.md

changed "languages" to "quotes"

fixed a typo

---

backend/src/api/schemas/config-schema.ts

remove quickTab and swapEscAndTab from config-schema

---

README.md

update tool badges

---

frontend/static/languages/catalan.json
frontend/static/languages/catalan_1k.json
frontend/static/languages/spanish_10k.json

Catalunya -> Cataluña

---

backend/jest.config.ts

Bump coverage

---

frontend/static/languages/spanish_10k.json

remove dupe

---

frontend/static/quotes/filipino.json

- Add several more Filipino quotes
- Modify first source to be "Sa Aking mga Kabatà" by Rizal (_falsely attributed_ instead of _disputed_)
- Set dashes to be only one hyphen long (`-` instead of `--`)

add more Filipino quotes; changed Rizal quote to falsely attributed

---

frontend/static/quotes/english.json

fixed typo in newly added quote

---

frontend/src/styles/popups.scss
frontend/static/html/popups.html

* In the 'Edit profile' popup:
- Change the Github and Twitter input positions, to match the same position in the profile page.
- Add static Github and Twitter URL before their inputs ("prevents" user insert the whole URL, causing nesting URL errors such as `https://github.com/https://github.com/<username>`)
| Before | After |
| --------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/48109548/180617833-dbe34b32-05ad-4c0d-98f0-4c9e9ecbb2a0.png) | ![image](https://user-images.githubusercontent.com/48109548/180617813-f9c7465b-06e9-423d-97b1-c6463273c4fa.png) |
- Idea: Add a regex similar to the website input to extract the username from Github and Twitter input URL. What do you guys think?

Changes in the profile

---

frontend/static/languages/britishenglish.json
frontend/static/languages/indonesian_1k.json

Test Project

---

frontend/static/quotes/german.json

Added new german quotes

---

backend/__tests__/dal/user.spec.ts
backend/src/dal/user.ts

It resets the xp when the user resets their account

resets the xp when reseting account

---

CONTRIBUTING_ADVANCED.md
frontend/src/styles/footer.scss
frontend/src/ts/elements/version-check.ts
frontend/src/ts/popups/version-popup.ts
frontend/static/html/bottom.html

Version of #3381 
Clicking on the indicator will close it without opening the list of versions. If you `git reset HEAD^` you can see what it's like when an X shows on hover, but I think it's better without showing X on hover
.

Added version indicator option 3

---

.github/workflows/pr-check.yml
backend/jest.config.ts

Housekeeping

---

frontend/static/quotes/albanian.json

Added 5 new Albanian Quotes

---

frontend/static/quotes/dutch.json

This PR adds 15 new Dutch quotes :)

Add 15 new Dutch quotes

---

QUOTES.md

Corrected typo on QUOTES.md

---

frontend/package-lock.json
frontend/src/ts/test/test-logic.ts

Refactors punctuateWord function to no longer capitalize the first letter of a sentence in Georgian, as their writing system does not use capitalization.
Closes #3414

Fixes bug with capitalization in Georgian (#3414)

---

frontend/static/themes/_list.json
frontend/static/themes/modern_dolch_light.css

Adds a new theme based on GMK Modern Dolch Light keycap set

New Theme: Modern Dolch Light 

---

backend/src/api/routes/configuration.ts
backend/src/api/routes/index.ts

Add endpoint for getting server config

---

frontend/static/languages/portuguese.json

just adding words often used in Portuguese to enrich the project!
Closes #
Nothing

Adding words to portuguese

---

frontend/src/ts/controllers/input-controller.ts

- Adding TS typing
- Changed some equality from loose to strict. I didn't change equalities that had to do with `Config`,
like `Config.mode == "zen"`, because I wasn't sure if it was intentional or not.
- Other small changes like the use of `startsWith` and a spelling error.

refactoring input controller (strict equality & TS typing)

---

frontend/static/quotes/code_c++.json

FIX: typo in c++ quote (id 32): extra \t after ;

---

frontend/static/quotes/english.json

Add quotes from Destiny & Destiny 2. Also edited the sources for the existing D2 quotes to be more specific.

Add quotes from Destiny & Destiny 2

---

frontend/src/ts/elements/commandline.ts

fix(commandline): adding toggle functionality for ctrl+shift+p command

---

CONTRIBUTING.md

Added information about the purpose of Redis.

Added basic information about redis.

---

frontend/static/quotes/english.json

Quote added: "I am prepared to die" by Nelson Mandela

add quote "I am prepared to die" by Nelson Mandela

---

frontend/src/ts/test/test-logic.ts

[untitled.webm](https://user-images.githubusercontent.com/42677093/188327426-a65b8c61-f082-4ce6-aaa0-b9bc8ed8d063.webm)

Unexpected appearance of numbers fix

---

backend/__tests__/dal/user.spec.ts
backend/__tests__/utils/daily-leaderboards.spec.ts
backend/__tests__/utils/misc.spec.ts
backend/__tests__/utils/monkey-mail.spec.ts
backend/src/api/controllers/result.ts
backend/src/constants/base-configuration.ts
backend/src/dal/user.ts
backend/src/jobs/announce-daily-leaderboards.ts
backend/src/types/types.d.ts
backend/src/utils/misc.ts
backend/src/utils/monkey-mail.ts

Reward daily leaderboards and refactor mail API

---

frontend/src/ts/popups/quote-report-popup.ts
frontend/src/ts/test/test-logic.ts
frontend/static/languages/_groups.json
frontend/static/languages/_list.json
frontend/static/languages/hungarian_2k.json

Closes # [Improve language checking #3493](https://github.com/monkeytypegame/monkeytype/issues/3493)

language checks use startsWith()

---

frontend/static/themes/_list.json
frontend/static/themes/viridescent.css

Added a theme by the name of Viridescent.
Mainly based around the green tint hence the name.
Closes #

add viridescent theme

---

backend/__tests__/utils/daily-leaderboards.spec.ts
backend/src/constants/base-configuration.ts
backend/src/dal/user.ts
backend/src/jobs/announce-daily-leaderboards.ts
backend/src/types/types.d.ts
backend/src/utils/misc.ts

Adds xp reward overrides for specific ranks

Add xp reward overrides

---

frontend/static/quotes/english.json

I added three new quotes from The Lord of the Rings and The Hobbit to the English quotes list.

add quotes from LOTR

---

frontend/src/ts/elements/modes-notice.ts

Was told to separate PRs, so here's a mini one 🙌 
Closes #3487

#3487 - Remove language mode notice in zen mode

---

backend/src/dal/user.ts

Sets rewards to an empty array.

Clear rewards

---

frontend/src/ts/controllers/badge-controller.ts

This role could be awarded to people that have significant contributions but aren't a collaborator.

Add contributor role

---

frontend/src/ts/ape/utils.ts

Closes #3545
Sample usage:
```ts
const callback = async () => await Ape.users.get();
const response = await withRetry(callback);
if (response.status !== 200) {
...
}
```

Add retry utility for ape

---

frontend/static/quotes/english.json

added a new quote

---

backend/src/api/schemas/config-schema.ts
frontend/src/ts/commandline/lists/sound-on-click.ts
frontend/src/ts/config.ts
frontend/src/ts/controllers/sound-controller.ts
frontend/src/ts/types/types.d.ts
frontend/static/html/pages/settings.html
frontend/static/quotes/english.json

Closes #
https://user-images.githubusercontent.com/58147810/192158983-d81e599b-1ed6-417e-9291-18699ba37f3d.mov

yyyriyriy ppp[i6riy

---

backend/src/constants/base-configuration.ts
frontend/src/ts/pages/account.ts
frontend/src/ts/pages/profile.ts

Closes #
https://user-images.githubusercontent.com/58147810/192109424-d99decfe-7fcd-44e0-a881-486aae22385d.mov

Replace profile URI to use username

---

frontend/static/quotes/english.json

Added quotes from Xenoblade Chronicles to `english.json`. I hope I did it correctly!
- `Long ago, the world was nothing more than an endless sea cloaked in a boundless sky, reaching as far as could possibly be imagined. Then two great titans came into existence. The Bionis and the Mechonis. The titans were locked in a timeless battle. Until at last... Only their lifeless corpses remained.`
- `Next time you have a vision, you tell us. We bear the burden together, as a team. You have a vision you don't like, we'll change the future together.`
- `I can't kill you, but I can stop your blade. And I'll do it over and over again, until... we understand each other. OK?`

Added quotes from Xenoblade Chronicles

---

frontend/static/languages/code_luau.json

I added all the documented global luau libraries to the luau language file. This will help me practice as these are widely used by luau programmers.

Add luau libraries

---

frontend/static/languages/code_lua.json
frontend/static/languages/code_luau.json

Fix errors and add more syntax to both languages

More luau fixes + lua fixes

---

frontend/static/quotes/english.json

Add quote from the song 46 & 2 by Tool
Closes #
N/A

Add lyric quote from the song 46 & 2 by Tool

---

frontend/static/quotes/english.json

Adds 5 quotes from the Dungeons & Dragons Player's Handbook.

add d&d quotes

---

backend/__tests__/utils/validation.spec.ts
backend/redis-scripts/purge-results.lua
backend/src/api/controllers/user.ts
backend/src/utils/daily-leaderboards.ts

Purge from dailies

---

frontend/static/quotes/spanish.json

Added two quotes to Spanish Json, from Alexandre Dumas, The Count of Monte Cristo
Closes #

Adding Quotes

---

frontend/src/ts/elements/notifications.ts

This looks for banners asking to refresh and gives them an event listener that refreshes on click.

Update banner refresh

---

frontend/static/quotes/code_python.json

Added some python quotes
Closes #

Add some python quotes

---

frontend/static/quotes/vietnamese.json

Fix spelling errors in Vietnamese quotes

---

frontend/src/ts/test/test-logic.ts

Fixed the issue that uppercase and camel-case words from code_ languages are converted to lowercase and that words with symbols (HTML tags, or words with underscores) are skipped.
Closes #

Preserve case and symbols in code_ languages

---

frontend/static/quotes/code_csharp.json

As a programmer learning to type using Canary, I enjoyed revising my data structures and algorithms on [SpeedCoder.net](https://www.speedcoder.net/race/), and I believe that such quotes should be made available on monkeytype as well. The quantity of code quotes is quite lacking on monkeytype, and this is a useful and fun way to increase the quote count.
Added the following quotes:
1. Hello World
2. Factorial
3. Find the nth Fibonacci Number Recursively
4. Binary Search
5. Insertion Sort
6. Selection Sort
7. Bubble Sort
8. Merge Sort
9. Quick Sort
10. Quick Select
About correctness: I have ran the algorithms and they pass my sorting tests.
Note: the sorting algorithms are the same as those in Java, just that `arr.length` -> `arr.Length`, `System.out.println` -> `Console.Writeline` and all …

Add data structures and algorithm quotes for C#

---

frontend/static/quotes/code_java.json

As a programmer learning to type using Canary, I enjoyed revising my data structures and algorithms on [SpeedCoder.net](https://www.speedcoder.net/race/), and I believe that such quotes should be made available on monkeytype as well. The quantity of code quotes is quite lacking on monkeytype, and this is a useful and fun way to increase the quote count.
Added the following quotes:
8. Find the nth Fibonacci Number Recursively
9. Binary Search
10. Insertion Sort
11. Selection Sort
12. Bubble Sort
13. Merge Sort `// this one is quite long at 874 chars`
14. Quick Sort
15. Quick Select `// also pretty long at 738 chars`
About correctness: I have ran the algorithms and they pass my sorting tests.
- typo in Java quote `id: 7`: Head First ~Obiject~ Object-Oriented Analysis and Design

Add data structures and algorithm quotes for Java

---

frontend/static/languages/polish_10k.json
frontend/static/languages/polish_20k.json
frontend/static/languages/polish_40k.json
frontend/static/languages/polish_5k.json

Added attribution to polish 5k, 10k, 20k, 40k
Closes #

Add attribution to polish 5k, 10k, 20k, 40k

---

THEMES.md
frontend/static/themes/_list.json
frontend/static/themes/earthsong.css

Adding new theme earthsong and fixing typo on THEMES.md

---

frontend/src/styles/core.scss
frontend/static/fonts/_list.json

are you ready for the worst pull request youve ever seen?
pretty simple, this adds the fonts "ubuntu" and "ubuntu mono" as options. im not sure if it even works (i havent tested it lmao, my computer just died while setting it up) so i hope it does.

Add Ubuntu and Ubuntu Mono fonts

---

backend/src/api/routes/results.ts
backend/src/middlewares/ape-rate-limit.ts
backend/src/middlewares/rate-limit.ts

Refactor ape rate limiter

---

frontend/static/html/pages/settings.html

add spacing between sentences

---

backend/src/utils/misc.ts

Fix weekly leaderboard timestamp logic

---

backend/src/api/controllers/result.ts
backend/src/api/routes/results.ts
backend/src/dal/result.ts
backend/src/documentation/public-swagger.json

Added an onOrAfterTimestamp parameter to /results, edited documentation to include.

Add timestamp filter for results

---

backend/src/jobs/announce-daily-leaderboards.ts

adding the WPM to the daily leaderboard message

---

.github/workflows/monkey-ci.yml
frontend/static/html/pages/settings.html

House keeping

---

frontend/static/quotes/code_javascript.json

JS Quote 24 didn't have tabs, so i  added some

Add tabs to js quote 24

---

frontend/static/quotes/code_javascript.json

In #3880, I forgot to update the length of the quote. You were so quick merging, CI didn't have time to complete :)

correct  length for js quote 24

---

frontend/static/themes/_list.json
frontend/static/themes/note_dark.css

Created a new theme with a few small additions
Features:
- a notepad style overlay on the background (it will overlay background images too)
- error strike-through instead of underline
- fun little dot transformation on already typed text
- some more rounded corners

create new theme: note dark

---

frontend/static/fonts/_list.json
frontend/static/languages/latin.json
frontend/static/quotes/latin.json

Added some more latin vocab, new json file with 4 latin quotes(longer than previous pull request), and new font, Georgia.

More Latin vocab and more

---

frontend/static/themes/_list.json
frontend/static/themes/dark_note.css

Features
* note overlay
*  Dot animation 
* rounded corners on buttons and the test setup.

add new theme: dark note

---

frontend/static/quotes/english.json

Quote added

---

frontend/static/languages/britishenglish.json

Adds flavors -> flavours to `britishenglish.json`

Add flavours to British English

---

frontend/static/quotes/spanish.json

Added quote to spanish.json with ID=193

---

frontend/static/languages/britishenglish.json

Adds catalog -gs -ger -gers -ged -ging, uncataloged to British English

Add Catalog and related declensions to British

---

backend/src/constants/base-configuration.ts

Add stricter typing to configuration

---

backend/private/script.js
backend/src/api/routes/configuration.ts
backend/src/middlewares/api-utils.ts
backend/src/types/types.d.ts

Added a middleware that only applies an array of middlewares based env variable

Allowing configuration endpoint access if user is configuration mod

---

frontend/static/quotes/spanish.json

My bad, i found some typos on the quotes I posted, i should have checked more before commiting

Typos i made

---

frontend/static/quotes/english.json

**Contains Portal 2 Spoilers!**
- Cave Johnson - Lemons rant:
- "All right, I've been thinking. When life gives you lemons? Don't make lemonade. Make life take the lemons back! Get mad! I don't want your damn lemons! What am I supposed to do with these?! Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am?! I'm the man who's gonna burn your house down! With the lemons! I'm gonna get my engineers to invent a combustible lemon that burns your house down!"
- GLaDOS - Test results:
- "Well done. Here come the test results: \"You are a horrible person.\" That's what it says: a horrible person. We weren't even testing for that."
- GLaDOS - Differences:
- "Okay. Look. We both said a lot of things that you're going to regret. But …

Three Portal 2 quotes

---

frontend/static/quotes/latin.json

Additional Latin quotes.

---

frontend/static/quotes/spanish.json

Added 7 spanish quotes and deleted a word from a previous quote which made no sense. Also i'm not too sure about last quote's format

Added 7 quotes on spanish

---

frontend/src/ts/account/all-time-stats.ts

Nit: These 2 if statements can be combined

Nit: Update all-time-stats.ts 

---

frontend/static/quotes/estonian.json

Added Estonian quotes and proverbs.

added estonian quotes

---

frontend/static/quotes/english.json

Added a new quote for English.

quote - NaD

---

frontend/static/quotes/english.json

Added one English quote

---

frontend/src/ts/elements/profile.ts

This indicates, that the linked resources belong to the person, that the current page is about.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/me
Related discussion: https://github.com/monkeytypegame/monkeytype/discussions/4014

Add `rel="me"` attributes to links on profile page

---

frontend/src/styles/popups.scss
frontend/src/ts/popups/word-filter-popup.ts
frontend/static/html/popups.html

Add a preset generator that populates the word filter include and exclude forms.
Closes #
#3620

Add word filter presets

---

frontend/static/quotes/german.json

Added quotes 544 - 548 in the german.json file

Added quotes 544 - 548

---

frontend/src/ts/popups/custom-text-popup.ts

uncomment text = text.trim();
test breaks if you add leading or trailing or both
Closes #

Remove leading and trailing spaces in custom popup

---

frontend/static/html/popups.html

Fix grammar in popups.html

---

frontend/static/quotes/code_c.json

Added two quotes to the code_c language.

Added quoters (id: 10, id 11) to code_c.JSON

---

backend/src/api/controllers/result.ts
backend/src/api/controllers/user.ts
backend/src/api/routes/users.ts
backend/src/dal/user.ts
backend/src/middlewares/rate-limit.ts
backend/src/types/types.d.ts
frontend/src/styles/settings.scss
frontend/src/ts/ape/endpoints/users.ts
frontend/src/ts/db.ts
frontend/src/ts/elements/leaderboards.ts
frontend/src/ts/elements/profile.ts
frontend/src/ts/pages/settings.ts
frontend/src/ts/popups/simple-popups.ts
frontend/src/ts/types/types.d.ts
frontend/static/html/pages/settings.html

Added ability to opt out of leaderboards

---

frontend/static/quotes/english.json

Added a single new English quote. Unknown source but allegedly it was said by Socrates.

added one new quote in English

---

frontend/static/security-policy.html

Remove comma in security policy page
Closes #

Remove comma

---

frontend/static/quotes/english.json

Added 9 quotes from RWBY and 3 quotes from The Legend of Vox Machina (season 2) to english.json.
From ID 6771 to ID 6782.

Added 12 quotes to english.json - 6771-6782

---

frontend/src/ts/controllers/chart-controller.ts
frontend/src/ts/test/result.ts

Organize imports to remove duplicate imports

---

frontend/static/quotes/english.json

add two quotes from Strong Towns & one from Walt Disney

Add three quotes to English

---

frontend/static/themes/_list.json
frontend/static/themes/cherry_blossom.css

cherry blossom theme (surprised this isn't a thing yet..)

added cherry blossom theme

---

frontend/static/quotes/spanish.json

I have added three quotes from different poems in Spanish by different authors, among them are:
> Manuel Jiménez, Máximo Fonseca, Rafael Otero López and Luis Aguirre Pinto

Added 3 quotes to spanish.json

---

frontend/static/languages/britishenglish.json
frontend/static/languages/english_5k.json

Change spelling of neighbouring to neighboring

Change spelling of neighbouring to neighboring

---

backend/src/api/controllers/result.ts
backend/src/constants/funbox.ts
frontend/src/ts/test/funbox/funbox-list.ts
frontend/static/funbox/_list.json

Adds plus three funbox.
Closes #4071

Added plus three funbox

---

frontend/src/ts/controllers/chart-controller.ts
frontend/src/ts/pages/account.ts

Fix pb line

---

.eslintrc.json
backend/src/api/controllers/result.ts
backend/src/dal/new-quotes.ts
backend/src/dal/user.ts

Require `===` and `!==` in Backend

---

frontend/static/quotes/english.json

Add Mr. Rogers quote, because everything with quotes needs one from Mr. Rogers:
> You are a very special person. There is only one like you in the whole world. There's never been anyone exactly like you before, and there will never be again. Only you. And people can like you exactly as you are.
you just can't not merge a quote like that :)

add mr.rogers quote

---

backend/src/api/controllers/admin.ts
backend/src/api/routes/admin.ts
backend/src/api/routes/index.ts
backend/src/dal/admin-uids.ts
backend/src/middlewares/api-utils.ts
backend/src/middlewares/auth.ts

Added support for future admin endpoints
(in production, admin-uids collection is read only)

Admin auth

---

frontend/static/languages/czech_10k.json
frontend/static/languages/czech_1k.json

- "m", "tý" - not a word
- "cm", "č." - abbreviations

Update Czech words

---

frontend/static/quotes/german.json

Adding german quotes 559 - 562

Add German Quotes

---

frontend/static/quotes/english.json

Reverts monkeytypegame/monkeytype#4128

Revert "Remove duplicate quote and fix quote `id` increment"

---

frontend/static/quotes/english.json

Fixed inconsistent source names for Avatar quotes

Fixed Inconsistencies with Avatar Quotes

---

frontend/static/privacy-policy.html

None, I am changing a static file
This commit changes:
"Advertisements on Monkeytype are optional. This section only applies to you if you've have not disabled them." To:
"Advertisements on Monkeytype are optional. This section only applies to you if you have not disabled them."
Closes #4137

Typo: Fixes #4137

---

frontend/static/quotes/code_lua.json

Adding code_lua.json file for quotes section, with lua snippets from
https://github.com/nvim-telescope/telescope.nvim
https://github.com/ThePrimeagen/harpoon

Add code lua quotes

---

frontend/static/layouts/_list.json

Added the xenia keyboard to _list.json

Add Xenia Layout

---

frontend/static/quotes/english.json

Changes made in this PR are:
- Added new english quotes
- Fixed indentation problem from [this](https://github.com/monkeytypegame/monkeytype/pull/4148) PR.
Closes #

Added english quotes & fixed indentation

---

frontend/static/quotes/english.json

after 10 years of learning how to use GitHub, learning the proper formatting for MT and kind-of understanding the workflow, I present my opus magnum, a singular quote from my beloved anime 
tl;dr synced fork, fixed formatting for the 10th time, and reduced the amount of ellipses to a minimum that would still give off the quotes original meaning

New english quote "_"

---

frontend/static/languages/hinglish.json

Removed the incorrect spelling of "zyada" which was in the word list ("zada"). The correct spelling is already present.
Fixed another spelling ("suru" -> "shuru")

Fix spelling and remove misspelt repeated word

---

frontend/static/html/pages/about.html

Just saw it while using the site, tiny one-letter fix

Fix About Page Leaderboard Typo

---

frontend/static/quotes/french.json

Adding the famous monologue from Otis, a character from the 2002 French movie Astérix et Obélix : Mission Cléopatre.

Add Otis' monologue quote

---

frontend/static/quotes/spanish.json

add: new quotes from The Knight in Rusty Armour

add: new quotes from The Knight in Rusty Armour

---

.github/workflows/pretty-fix.yml
.github/workflows/stale-pr.yml

Upgrade actions in workflows

---

backend/__tests__/utils/daily-leaderboards.spec.ts
backend/src/constants/base-configuration.ts
backend/src/server.ts
backend/src/types/types.d.ts
backend/src/utils/daily-leaderboards.ts

Remove daily lb cache

---

frontend/static/quotes/italian.json

Added five quotes to the italian.json file

Added Italian Quotes

---

frontend/src/styles/popups.scss
frontend/src/ts/popups/share-custom-theme-popup.ts
frontend/src/ts/settings/theme-picker.ts
frontend/src/ts/utils/url-handler.ts
frontend/static/html/popups.html

**Description:**
This PR introduces the ability for users to share their background image data via the theme URL. The URL encodes a JSON object containing the theme's color scheme and optional background image data.
Significant changes were made in the theme-controller, theme-picker, and the new share-custom-theme-popup modules. The URL handling mechanism was also updated to support the new JSON format.
Details of changes:
Updated popups.html to include the html for the background option popup box.
Updated url-handler.ts to support both JSON formats.
Updated theme-picker.ts to make Share button activate popup.
Updated popups.scss for popup css.
Created share-custom-theme-popup.ts to handle URL Generation.

Backgrounds in Theme URLs

---

frontend/static/quotes/portuguese.json

Added portuguese quote with id 67.

Added portuguese quote

---

frontend/static/quotes/italian.json

I added 6 quotes from different italian books to the 'italian.json' file under in the static assets of the frontend folder. I made sure to follow the quote guidelines.

added six italian quotes

---

frontend/static/quotes/spanish.json

Added two quotes from Pablo Escobar

Two New Spanish quotes

---

frontend/static/quotes/english.json

removed some duplicate quotes from english.json with the following IDs (original-->duplicate):
4231-->5577
1841-->6156
6359-->6715
2553-->6763
1874-->6826

removed duplicates

---

frontend/static/quotes/french.json

I changed "vraiment ,toi" to "vraiment, toi".

Just fixed a simple typo

---

frontend/static/quotes/english.json

fixed some quote's sources and removed some more duplicate quotes from english.json with the following 
IDs (original-->duplicate):
6822-->6846
5315-->6694
6211-->6540
262-->6366
1681-->6280

more duplicates removed

---

frontend/static/quotes/spanish.json

Removed quote with ID=58 from spanish.json as it was identical to quote with ID=50.

removed duplicate spanish quote

---

frontend/static/quotes/german.json

Removed quote with ID=235 from german.json as it was identical to quote with ID=217.

removed duplicate german quote

---

frontend/src/ts/elements/leaderboards.ts

solve this bug
https://github.com/monkeytypegame/monkeytype/issues/4331

solve Yesterday appear in all time leaderboard #4331

---

frontend/static/quotes/italian.json

Added four quotes to italian.json.
These are the translations:
138: How stupid we are, how many rejected invitations, how many unspoken words, how many unrequited looks. Many times life passes us by and we don't even notice it.
139: If in the world we all became scientists, who unloads the cash registers here at the markets?
140: You spend your life being told you're too young, then you're too old. There will be a middle stage where one has to run, right?
141: If we're not here too, they'll set up the republic for you in no time. If we want everything to stay as it is, everything must change.

added more italian quotes

---

frontend/static/languages/_groups.json
frontend/static/languages/_list.json

My PR is just adding an almost complete spanish dictionary with 646k words, including conjugated verbs. Plurals are not included at all.

Adding Spanish 646K language json

---

frontend/static/quotes/english.json

I added 6 quotes by Prophet Muhammad for the Quotes section in Monkeytype.
They are 44, 53, 58, 80, 101, and 138 characters long.

I added 6 quotes of Prophet Muhammad for Monkeytype.

---

frontend/static/quotes/english.json

- Added 30 quotes
- Replaced duplicate quote with non-duplicate quote
- Fixed incorrect quotation marks

Josiah quotes

---

backend/__tests__/utils/validation.spec.ts

- Adding tests for isTagPresetNameValid
- Increasing test coverage
Closes #
- N/A

Adding tests for isTagPresetNameValid

---

frontend/src/ts/pages/login.ts

This pull request adds a new feature to the sign-up process that checks if the provided email address is a school email address (.edu domain). It also includes an indicator to notify users to consider using a personal email address for better email functionality.
https://github.com/monkeytypegame/monkeytype/assets/88141521/2e2b3ab2-6e26-41fd-8758-8d1e05adca5e
Closes #4393

Notify users for school email address (.edu | .ac | .sch)

---

frontend/static/quotes/code_ruby.json

Creates an initial quotes file with 27 quotes for code_ruby language. I've tested the text of each quote by running locally and typing each quote for Ruby.
Closes n/a

Create initial quotes for code_ruby language

---

frontend/static/quotes/esperanto.json

Added quotes for Esperanto
Closes #

Create quotesfile (esperanto.json)

---

frontend/static/quotes/english.json

This PR adds a quote for Bertrand Russell in English Quotes file. ID of 6983 value is selected.

Add Quote by Bertrand Russell

---

frontend/static/quotes/english.json

Added quote

---

frontend/static/quotes/english.json

Just adding better sources for certain quotes that I noticed while using monkeytype.
Thanks all!

Improving quote sources

---

frontend/src/ts/elements/result-word-highlight.ts

Fixed last word(s) highlight not showing up

Fixed last word(s) highlight not showing up

---

frontend/src/ts/test/result.ts

Fix a small typo in cpm graph label

fix typo in cpm graph label

---

frontend/static/layouts/_list.json

Adds the Middlemak and Middlemak-NH keyboard layouts:
Middlemak: https://github.com/KeyboardLayout2/Middlemak
Middlemak-NH: https://github.com/KeyboardLayout2/Middlemak-NH
Closes #

added middlemak and middlemak-nh

---

frontend/static/quotes/code_go.json

Add golang quotes
Sources
- https://github.com/aws/aws-sdk-go-v2/blob/ae835ecd/service/iam/api_op_GetRole.go
- https://github.com/helm/helm/blob/50c22ed7/pkg/downloader/chart_downloader.go
- https://github.com/helm/helm/blob/50c22ed7/pkg/engine/files.go
- https://github.com/helm/helm/blob/50c22ed7/pkg/engine/funcs.go
- https://github.com/helm/helm/blob/50c22ed7/pkg/plugin/plugin.go
- https://github.com/kubernetes/kubernetes/blob/3b18e80/pkg/client/conditions/conditions.go
- https://github.com/kubernetes/kubernetes/blob/3b18e80/pkg/controller/garbagecollector/graph_builder.go
- https://github.com/tmrts/go-patterns/blob/64a6757/concurrency/bounded_parallelism.go
All these quotes are licensed under Apache-2.0
I read https://github.com/monkeytypegame/monkeytype/blob/master/CONTRIBUTING.md#quot …

Add golang quotes

---

frontend/src/ts/commandline/lists/live-wpm.ts
frontend/src/ts/commandline/lists/min-burst.ts
frontend/src/ts/commandline/lists/min-wpm.ts
frontend/src/ts/commandline/lists/pace-caret.ts
frontend/src/ts/config.ts
frontend/src/ts/elements/modes-notice.ts
frontend/src/ts/pages/settings.ts
frontend/src/ts/test/test-timer.ts
frontend/static/html/pages/settings.html

Duplicate of #4501, this one DOESN'T change anything that is NOT user facing, making it much smaller.
Not sure which one i wanna go with yet.
Closes #3785

Renamed live wpm to live speed, min wpm to min speed (no non-user facing changes)

---

frontend/static/layouts/_list.json

Adds @ThePrimeagen's [Programmer Dvorak](https://github.com/ThePrimeagen/keyboards) layout

add ThePrimeagen's Programmer Dvorak layout

---

backend/src/api/schemas/config-schema.ts
frontend/src/styles/settings.scss
frontend/src/styles/test.scss
frontend/src/ts/commandline/lists/highlight-mode.ts
frontend/src/ts/config.ts
frontend/src/ts/test/test-ui.ts
frontend/src/ts/types/types.d.ts
frontend/static/html/pages/settings.html

Add three more highlight modes: 
- next word
- next two words
- next three words

Added highlight modes next word, next two words and next three words

---

backend/package-lock.json
backend/package.json

chore: Upgrade types to Node 18

---

frontend/static/quotes/code_csharp.json

The link to where the quote is from is [here](https://www.geeksforgeeks.org/array-getvalue-method-in-csharp-with-examples-set-3/#:~:text=the%20current%20Array.-,Example%201%3A,-C%23). (It's the `for` loop at the end of "Example 1")
I added a quote from [Geeks for Geeks](https://geeksforgeeks.org) on `Array.GetValue();` in the C# language.
**I'm new at contributing to monkeytype so let me know if I did something wrong. If there is something that needs to be corrected, let me know so I can fix it.**

feat(quote): add C# quote

---

CONTRIBUTING_ADVANCED.md

Updated node version mentioned in the contributing advanced documentation.

docs: contributing advanced docs updated

---

frontend/static/quotes/english.json
frontend/static/quotes/german.json
frontend/static/quotes/indonesian.json
frontend/static/quotes/italian.json
frontend/static/quotes/polish.json

Remove duplicate quotes.
- german:
- removed 523, duplicate with 343
- indonesian:
- removed 20,25 duplicate with 6
- removed 112, duplicate with 5
- removed 179, duplicate with 175
- italian:
- removed 6, duplicates with 60
- removed 51, duplicates with 8
- removed 52-59, duplicates with 15-23
- polish:
- removed 122, duplicates 27
- english:
- removed 11, duplicate with 2864
- removed 752, duplicate with 19 
- removed 31, duplicate with 659
- removed 159, duplicate with 786
- removed 227, duplicate with 741
- removed 4052, duplicate with 294
- removed 367, duplicate with 1164
- removed 378, duplicate with 1770
- removed 447, duplicate with 1649
- removed 488, duplicate with 1172
- removed 3674, duplicate with 570
- removed 2692, duplicate with 574
- removed 593, duplicate with 2621
- …

fix(quote): remove duplicate quotes

---

frontend/src/ts/test/funbox/funbox.ts
frontend/static/funbox/crt.css

Closes #4553 
- detect safari version 16.5 or earlier and don't activate CRT funbox
- converted nested css into plain in  `crt.css`

fix: crt funbox causes webkit browsers to go into refresh loop (fehmer)

---

frontend/src/ts/ape/adapters/axios-adapter.ts
frontend/src/ts/ape/endpoints/ape-keys.ts
frontend/src/ts/ape/endpoints/configs.ts
frontend/src/ts/ape/endpoints/leaderboards.ts
frontend/src/ts/ape/endpoints/presets.ts
frontend/src/ts/ape/endpoints/psas.ts
frontend/src/ts/ape/endpoints/public.ts
frontend/src/ts/ape/endpoints/quotes.ts
frontend/src/ts/ape/endpoints/results.ts
frontend/src/ts/ape/endpoints/users.ts
frontend/src/ts/ape/types/ape.d.ts
frontend/src/ts/ape/utils.ts
frontend/src/ts/db.ts
frontend/src/ts/elements/psa.ts
frontend/src/ts/pages/login.ts

Adds a generic to the endpoint type, allowing the api data to be properly typed

refactor: add response data generic type

---

frontend/package-lock.json
frontend/src/ts/test/funbox/funbox.ts
frontend/src/ts/utils/misc.ts
frontend/static/challenges/sourcecode.txt

* ran npm install in frontend, and the lock file got updated 
* refactored to use slice instead of substr

refactor: replace 'substr' with 'slice'

---

frontend/src/styles/popups.scss
frontend/src/ts/popups/quote-search-popup.ts
frontend/static/html/popups.html

Added page navigation to the quotes search page.
Screenshots
| Default | Last Page | No result |
| - | - | - |
| ![image](https://github.com/monkeytypegame/monkeytype/assets/34833095/8f8b4052-5c6a-4b39-9dab-79c7780f06fe) | ![image](https://github.com/monkeytypegame/monkeytype/assets/34833095/8424f2db-77c3-49a2-8856-3be4eaa0f5f8) | ![image](https://github.com/monkeytypegame/monkeytype/assets/34833095/f5eb284d-fe98-47ef-973b-f81603600c68) |

impr(quote search): add pagination to search results (Shuja-Mahmood)

---

frontend/static/layouts/_list.json

impr(layout): add hungarian layout (BarniExe)

---

frontend/static/quotes/english.json

impr(quote): add quote (Technet8394)

---

frontend/static/quotes/english.json

I've added a new quote for Simon Sinek. [Source](https://youtu.be/lFMrrIxOU4Q?si=tVh7VNlXRvTR2yMW&t=425)
Here is the added quote:
```json
{
"text": "If you want to be an elite warrior, you better get really, really good at helping the person to the left of you and helping the person to the right of you.",
"source": "Simon Sinek",
"length": 155,
"id": 6990
}
```

impr(quote): Add a quote

---

frontend/src/ts/controllers/chart-controller.ts
frontend/src/ts/pages/account.ts

impr(account page): change time typing unit to minutes on the activity chart (fehmer)

---

frontend/static/quotes/english.json

impr(quote): add quote (drdilyor)

---

frontend/src/ts/test/caps-warning.ts

fix: inconsistent caps lock warning message (fehmer)

---

frontend/static/quotes/english.json

Duplicate of [4636](https://github.com/monkeytypegame/monkeytype/pull/4636)
Added a quote from the YouTube video titled "www.blind" from the creator Boisvert. [Source](https://youtu.be/2cgU_bsQPPs?si=0WkdKCz_WuZnrdHT)
```JSON
{
"text": "Pertaining to a speaker and a listener. There have been many empty rooms, but that is not what we are here to talk about today. I have heard a heartbeat out of a crashed application, and it has gone on for many hours. We restarted every system. We rechecked every gateway, every access point. And there was but one breach, and it was accounted for. And so it must be said unto the listener. Stop this immediately. Control yourself. There is so much more to your fundamental construction than what will be given credit for. Hold yourself until another approaches. …
```

impr(quote): add thicc english quote

---

frontend/static/layouts/_list.json

Layout from: Dvorak by Nizo
https://github.com/theNizo/DvorakByNizo
Closes #

feat: Added german_dvorak_imp layout

---

frontend/static/layouts/_list.json

Add the  [noted layout](https://www.neo-layout.org/Layouts/noted/) (neo-family of German keyboard layouts)

impr(layout): add noted layout (dariogoetz)

---

frontend/static/quotes/english.json

Fixed English quote
[source](https://www.gutenberg.org/cache/epub/67098/pg67098-images.html#:~:text=%22Oh!%22%20said%20Pooh.%20%22So%20it%20is,%22)

fix(quote): fix english quote

---

frontend/static/quotes/code_java.json

fix(quote): delete unecessary double tabs in Java quote (alyoro)

---

frontend/static/quotes/french.json

I added some quotes for the French language

impr(quotes): add french quotes (johan-perso)

---

frontend/static/quotes/english.json

I have added six English quotes to the project.
My pull request includes six quotes that I found during a search, and they are in English.

impr(quotes): add 6 quotes (aikooo7)

---

frontend/static/quotes/english.json

added quote from guilty gear? idk if the text length is correct, if it's too short i'll just make it the song quote instead of game quote

impr(quotes): add guilty gear quote (remalucard)

---

frontend/static/themes/nord.css

Regression fix `nord.css` syntax error.

chore: fix nord.css syntax error (ridemountainpig)

---

frontend/src/ts/controllers/theme-controller.ts

impr: add notification for automatically turning off auto switch theme

---

frontend/static/quotes/french.json

I've added some quotes for the French
> Si le Président remporte la moitié des voix, c'est que les deux tiers de la France en voulaient pas. 
> If the President wins half the vote, it's because two-thirds of France didn't want him.
> Tous nos leaders ont échoué, ils seront détruits par la bête qu'ils ont créée.
> All our leaders have failed; they will be destroyed by the beast they have created.
> Les gens les plus intelligents sont pas toujours ceux qui parlent le mieux.
> The most intelligent people are not always the ones who speak best.
> Les hommes politiques doivent mentir sinon tu voterais pas pour eux.
> Politicians have to lie or you wouldn't vote for them.
> On soignera jamais la dépression comme on soigne un rhume
> Mais dis-toi que tu pourras compter sur moi le temps qu'ça …

impr(quotes): Add 6 Orelsan's Quotes

---

frontend/static/languages/britishenglish.json

Add `emphasise` and related words to British English
~~Closes #~~

impr: add `emphasise` and related words to British English (Cucumberrbob)

---

frontend/package.json
frontend/webpack/config.base.js
frontend/webpack/config.dev.js
frontend/webpack/config.prod.js

fix development mode detection not working on windows

fix: development mode detection on windows

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
CONTRIBUTING_ADVANCED.md
CONTRIBUTING_BASIC.md
LANGUAGES.md
README.md

A lot of typos and grammatical errors are fixed and updated.

docs: fix typos and grammatical errors (theranjitraut)

---

CONTRIBUTING.md

I was reading through contributing.md and saw "Dont include swear words."
I changed this to "Don't include expletives" for the sake of professionalism.

docs: change wording (Warrobot10)

---

frontend/static/quotes/finnish.json

Added finnish quotes. Quotes are from classic Finnish literature Kalevala and Tuntematon sotilas.
Checked that there are finnish language but there wasn't any finnish quotes yet.
Closes #

feat(quotes): add finnish quotes (imtone1)

---

frontend/static/quotes/english.json

Hi, this is my first PR on monkeytype I'm just learning how to get involved. For this I added one English quote "Just as a snake sheds its skin, we must shed our past over and over again". 
- [No] Adding a language or a theme?
- [No] If is a language, did you edit `_list.json`, `_groups.json` and add `languages.json`?
- [No] If is a theme, did you add the theme.css?
- [No] Check if any open issues are related to this PR; if so, be sure to tag them below.

impr(quotes): add one English quote (ryanlundqvist)

---

frontend/static/quotes/italian.json

I fixed an incomplete quote and added some other quotes I like.
"text": "Imperfection is beauty, madness is genius and it is better to be absolutely ridiculous than absolutely boring.",
"source": "Marilyn Monroe",
"id": 76
"text": "Where I can ever have read that condemned to death that, an hour before execution, he says or think that if he could live on top of a rock, on a platform so close that he can only keep the two feet, with around the abyss, the ocean, the eternal darkness, eternal solitude and eternal procella, and remain motionless on that space of a square meter for a lifetime, for a thousand years, for eternity, well, it would prefer to live thus rather than that Dying in that instant? In order to live, live, live! Live in any way, but to live! ... What truth, Lord God, what a …

impr(quotes): add Italian quotes (ormai)

---

frontend/static/quotes/english.json

impr(quotes): add English quotes (LifeAdventurer)

---

frontend/static/quotes/english.json

Added a new English quote from Talos Principle found here: [Talos Principle Wiki Link](https://talosprinciple.fandom.com/wiki/Singularity_discussion104.html)
It's 694 characters long and a relatively easy quote in terms of language and character/symbol variety

impr(quotes): add English quote (Saccade)

---

backend/src/dal/leaderboards.ts

Fixes all time leaderboards missing raw and consistency.

fix: Leaderboards missing raw and consistency (fehmer)

---

frontend/static/languages/code_c++.json

add new words (some STL containers) to code_c++.json
Closes #

impr(languagues): add new words in language code_c++  (LifeAdventurer)

---

frontend/static/quotes/spanish.json

Add spanish quotes: id[142-147]
I have added some quotes in Spanish, from philosophers such as Marcus Aurelius, Epictecus and Seneca and an extra bonus of a dialogue from the movie Gladiator.
Quotes i added for you to check integrity
The true way to take revenge on an enemy is not to resemble him.
If it is not convenient, don't do it; if it is not true, don't say it. Be master of your inclinations.
All things are intertwined with each other and their common bond is sacred and almost none is strange to the other, because they are all coordinated and contribute to the order of the same world.
My name is Maximus Decimus Meridius, Commander of the armies of the North, General of the Felix legions, Loyal servant of the true emperor Marcus Aurelius, Father of a murdered son, Husband of a …

impr(quotes): add Spanish quotes [zft9xgy]

---

backend/src/api/routes/quotes.ts
backend/src/middlewares/api-utils.ts

- add request validation for headers
- add option to allow unknown fields during validation
- move validation error message to validation options

impr: Add header validation, allow validation to accept unknown fields  (fehmer)

---

frontend/static/quotes/english.json

I submitted English quote #5510 with one part of the first sentence missing, so I've included the missing bit.

fix(quotes): english quote 5510 (brainandforce)

---

backend/__tests__/dal/leaderboards.spec.ts
backend/__tests__/dal/public.spec.ts
backend/src/dal/leaderboards.ts

Add test coverage for leaderboard update.

test: Add test coverage for leaderboard update  (fehmer)

---

.github/pull_request_template.md

Fix wording of pull request template.

docs: fix pr template wording (unrealapex)

---

frontend/static/layouts/_list.json

feat(layouts): add semimak jqc (MasterRon)

---

frontend/src/ts/test/test-stats.ts

refactor: char counting

---

frontend/static/languages/code_fsharp.json

I added F# basic types and `bigint`

impr(language): add more F# words (kacperwyczawski)

---

frontend/static/layouts/_list.json

https://github.com/sunaku/engrammer

feat(layouts): add engrammer (KaelWD)

---

frontend/static/quotes/english.json

impr(quotes): Added English quote. (julianbarg)

---

frontend/static/layouts/_list.json

Added graphite_angle_kp layout to layout emulator

feat(layouts): add graphite_angle_kp

---

frontend/src/ts/test/replay.ts

Fixed type error was getting when clicked on un typed letters in time test mode while replaying.
Closes #
closes #4906

fix: TypeError while Replay 

---

frontend/static/quotes/english.json

Added English quote by Abraham Lincoln.

impr(quotes): add english quote

---

frontend/static/quotes/english.json

Revert "impr(quotes): add english quote"

---

frontend/static/quotes/english.json

Added a long and infamous question from the 2014 Abu Dhabi Grand Prix Thursday pre-race press interview. Source: https://www.fia.com/news/2014-abu-dhabi-grand-prix-thursday-press-conference

impr(quotes): add 1 English quote (ProBottler)

---

frontend/static/quotes/romanian.json

Quotes:
8. Don't it make you sad to know that life is more than who you are?
9. The people with ideas have no power and the people with power have no ideas.
10. You must take life the way it comes at you and make the best of it.
11. If you have to ask, you will never know. If you know, you need only ask.
12. I'm sure there are things you know that you don't even know you know.
13. You can't use the fire exit because you're not made of fire.
14. The person that has the most to do with what happens to you is you!
15. There are darknesses in life and there are lights, and you are one of the lights, the light of all lights.
16. If you only do what you can do, you will never be more than who you are now.
17. If I have to hear one more time that you did this for the family...
18. And in the …

feat(language): add romanian quotes

---

frontend/__tests__/tsconfig.json

Fix frontend tests showing errors in vscode

fix: errors shown in frontend tests in vscode (fehmer)

---

backend/src/utils/logger.ts

enhances the code clarity by integrating the assignment of color = infoColor within the switch statement.

refactor: intergrate default statement in switch  for readability (b22790188)

---

frontend/src/ts/popups/simple-popups.ts
frontend/src/ts/test/custom-text.ts

fix(custom text): saving a book mode test completely breaking saved book mode tests

---

frontend/static/languages/code_luau.json

Simply adds 'buffer' to the list of Luau keywords as it is specified to exist [in the Luau language](https://luau-lang.org/library#buffer-library) as a library.

impr(language): add 'buffer' to list of keywords in luau language (adammehaney)

---

backend/__tests__/tsconfig.json
frontend/__tests__/tsconfig.json
monkeytype.code-workspace

test: fix typescript setup in tests (fehmer)

---

frontend/static/quotes/french.json

It should be "À cet instant" not "A cet instant"

fix(lang): Fixes a singular grammar mistake in french quotes (alexkar598)

---

frontend/static/quotes/code_css.json

I have added CSS quotes and fixed the issue I had with the id numbers.

impr(quotes): added css quotes (ruanbuhr)

---

frontend/static/themes/_list.json
frontend/static/themes/tangerine.css

feat(theme): added tangerine theme (devdenisalex)

---

frontend/src/ts/test/caps-warning.ts

Fix error 
```
caps-warning.ts:30 Uncaught TypeError: _b.getModifierState is not a function
at HTMLDocument.update (caps-warning.ts:30:26)
at HTMLDocument.dispatch (jquery.js:5145:1)
at elemData.handle (jquery.js:4949:1)
```

fix: unknown function called in capsLock detection (fehmer)

---

frontend/package-lock.json
frontend/package.json
frontend/src/ts/ape/adapters/axios-adapter.ts
frontend/src/ts/commandline/index.ts
frontend/src/ts/commandline/lists/custom-themes-list.ts
frontend/src/ts/commandline/lists/presets.ts
frontend/src/ts/commandline/lists/quote-length.ts
frontend/src/ts/commandline/lists/random-theme.ts
frontend/src/ts/commandline/lists/tags.ts
frontend/src/ts/config.ts
frontend/src/ts/controllers/account-controller.ts
frontend/src/ts/controllers/route-controller.ts
frontend/src/ts/db.ts
frontend/src/ts/elements/account-button.ts
frontend/src/ts/elements/alerts.ts
frontend/src/ts/elements/leaderboards.ts
frontend/src/ts/elements/modes-notice.ts
frontend/src/ts/firebase.ts
frontend/src/ts/pages/settings.ts
frontend/src/ts/popups/quote-search-popup.ts
frontend/src/ts/popups/simple-popups.ts
frontend/src/ts/settings/theme-picker.ts
frontend/src/ts/test/result.ts
frontend/src/ts/test/test-logic.ts
frontend/src/ts/test/test-ui.ts

Getting 403 while trying to get the rank for `null` user.

refactor: null-safe usage of Auth.currentUser (fehmer)

---

backend/__tests__/dal/leaderboards.spec.ts
backend/src/dal/leaderboards.ts
frontend/src/ts/elements/leaderboards.ts
shared-types/types.d.ts

fixes scrolling breaking if a leaderboard entry has no consistency

fix: leaderboard consistency being null (fehmer)

---

frontend/static/quotes/spanish.json

I added a couple spanish quotes by Anónimo

impr(quotes): Added Spanish quotes (devdenisalex)

---

frontend/static/themes/_list.json
frontend/static/themes/macroblank.css

- Create macroblank.css
- Update _list.json
colorful mode
normal

feat(theme): Add macroblank theme (TheExploration)

---

frontend/static/quotes/code_javascript.json

I came across this code on [GeeksforGeeks](https://www.geeksforgeeks.org/selection-sort/) for selection sort, but it had some mistakes. I've added the fixed version.

impr(quotes): add JavaScript quote (NipulM)

---

frontend/src/ts/controllers/quotes-controller.ts
frontend/src/ts/test/british-english.ts
frontend/src/ts/utils/misc.ts

replace jQuery `getJson`  with `fetch`.
Closes #5106

impr: remove usage of jQuery getJSON (fehmer)

---

frontend/src/ts/controllers/input-controller.ts

fix: ctrl+backspace replay bug (ashinberish)

---

frontend/src/ts/test/pace-caret.ts

fix: fix wrong usage of DB.getLocalPB

---

frontend/src/ts/db.ts

fix: PB pace caret is always zero

---

frontend/src/ts/elements/leaderboards.ts

fix: fix two percentage symbols in leaderboard (fehmer)

---

frontend/src/html/header.html
frontend/src/html/pages/login.html
frontend/src/ts/ape/server-configuration.ts
frontend/src/ts/pages/login.ts
frontend/src/ts/ready.ts

impr: hide login/signUp button if user signup is disabled (fehmer)

---

backend/docker/compose.db-only.yml
backend/docker/compose.yml
backend/package.json
frontend/docker/compose.dev.yml
frontend/package-lock.json
frontend/package.json

fix docker compose files
- use `docker compose` instead of the outdated `docker-compose`
- fixed port mapping
- don't share `node_modules`  directories outside docker to prevent permission issues
- fix frontend not able to build if root directory `node_modules` missing

chore: improve docker files for local development (fehmer)

---

frontend/static/quotes/english.json

impr(quotes): add one english quote (MordecaiO)

---

frontend/src/ts/controllers/account-controller.ts
frontend/src/ts/pages/login.ts

Fix login buttons still disabled after logout.

fix: login disabled after logout

---

frontend/static/quotes/french.json

> No, I'm listening to you, I'm listening to you, only I'm warning you, I'm telling you, I'm going to get you down to the jail with a pitcher of water and a piece of stale bread. I'm sorry, I don't know what to do, I can't see any other option. And I think that it will give you an opportunity to... to think about it with a clear mind, to take a step back on things because Bohort, you don't wake your king up in the middle of the night for stuff like that, and not twice in a row...
> No, that's only us. Because you need to be able to look like an idiot in record time. No, on this we have a considerable lead.
> No, I think you need to stop trying to say stuff. You, for one, get tired, and for the others, you don't realize...
> You, you should stop smilling. I swear, it's becomming sickening. …

impr(quotes): add French quotes (Mintoo200)

---

frontend/src/ts/elements/notifications.ts

fix(notifications): clear all notifications from the command line not hiding clear all button (NadAlaba)

---

frontend/src/html/pages/login.html
frontend/src/html/pages/settings.html
frontend/src/ts/controllers/account-controller.ts
frontend/src/ts/pages/settings.ts
frontend/src/ts/popups/simple-popups.ts

feat(authentication): add signin with github (fehmer)

---

frontend/static/quotes/french.json

Fixing typos in a previously added quote (mission uppercase and approstrophe)

impr(quotes): Fix typo in previously added french quote (Mintoo200)

---

frontend/src/ts/test/test-ui.ts

(Stop on error = letter) + (Indicate typos = below) ==> undefined hints.
This PR redefines them.

fix(indicate typos): undefined hints in stop on letter (NadAlaba)

---

frontend/static/themes/_list.json
frontend/static/themes/incognito.css

Add incognito theme based on the keycap set DCS Incognito.
Screenshots:
- normal  
- colorful 
- flipped 
- flipped, colorful

feat: add incognito theme (fehmer)

---

frontend/static/quotes/english.json

Added 5 English quotes.
Closes #

impr(quotes): add English quotes (JornTumrongwit)

---

frontend/static/themes/_list.json
frontend/static/themes/discord.css

Made a theme, "discord". I wanted to match the Discord aesthetic, so I did what I could do recreate it!

feat(theme): add discord (sithydev)

---

frontend/static/quotes/english.json

Added 2 quotes.
(I'm not exactly sure how this part works)
Closes N/A

impr(quotes): Add 2 quotes (everypizza1)

---

frontend/static/quotes/english.json

impr(quotes): add English quotes (cute-catgirl)

---

backend/src/api/schemas/result-schema.ts
backend/src/utils/validation.ts
frontend/src/html/popups.html
frontend/src/styles/popups.scss
frontend/src/styles/z_media-queries.scss
frontend/src/ts/commandline/lists/bail-out.ts
frontend/src/ts/controllers/challenge-controller.ts
frontend/src/ts/controllers/input-controller.ts
frontend/src/ts/modals/custom-text.ts
frontend/src/ts/modals/mobile-test-config.ts
frontend/src/ts/modals/word-filter.ts
frontend/src/ts/popups/share-test-settings-popup.ts
frontend/src/ts/test/british-english.ts
frontend/src/ts/test/custom-text.ts
frontend/src/ts/test/practise-words.ts
frontend/src/ts/test/result.ts
frontend/src/ts/test/test-logic.ts
frontend/src/ts/test/test-timer.ts
frontend/src/ts/test/test-ui.ts
frontend/src/ts/test/timer-progress.ts
frontend/src/ts/test/words-generator.ts
frontend/src/ts/types/types.d.ts
frontend/src/ts/ui.ts
frontend/src/ts/utils/misc.ts
frontend/src/ts/utils/url-handler.ts
frontend/static/challenges/_list.json
shared-types/types.d.ts

Rework the custom text logic and UI.

refactor: custom text

---

backend/src/api/schemas/result-schema.ts
frontend/src/ts/test/test-logic.ts
frontend/src/ts/test/words-generator.ts
frontend/src/ts/test/wordset.ts
frontend/src/ts/types/types.d.ts

Slightly simply word generation, quote mode no longer requires so many special cases.
Store language and wordset inside word generation module to avoid the need to pass it in as a parameter all the time.
Stopping test if dynamic word generation fails.
Also fixes #5326

refactor: word generation

---

frontend/static/themes/_list.json
frontend/static/themes/cy_red.css

Once again, I remade my PR about the new theme cy_red. I learned plenty much about my mistakes, and fixed them. The error color of my theme is now blue, so hopefully it gets approved. (that rhymes a little) I might have messed up on a thing or two, but I just added a new theme, not that big of an impact. Thanks!
Closes #

impr(themes): added and Created theme cy_red (StickminBruv)

---

frontend/static/themes/_list.json
frontend/static/themes/floret.css

feat(theme): add floret (hurrrsh)

---

frontend/src/ts/account/result-filters.ts

feat: Add "no funbox" filter to the account page (fehmer)

---

frontend/static/layouts/_list.json

I added the swedish colemak layout (based on https://github.com/motform/colemak-se)

feat(layout): add Swedish Colemak (kevinalavik)

---

backend/__tests__/api/controllers/user.spec.ts
backend/__tests__/dal/blocklist.spec.ts
backend/__tests__/global-setup.ts
backend/__tests__/setup-tests.ts
backend/__tests__/utils/misc.spec.ts
backend/package-lock.json
backend/package.json
backend/src/api/controllers/user.ts
backend/src/api/routes/admin.ts
backend/src/dal/blocklist.ts
backend/src/server.ts
backend/src/types/types.d.ts
backend/src/utils/discord.ts
backend/vitest.config.js
frontend/src/privacy-policy.html

On deletion of a banned user keep a list of hashed username, email and optional discordId and prevent those user to signup and link discord.

feat: maintain blocklist of banned usernames and email (fehmer)

---

frontend/src/ts/controllers/theme-controller.ts
frontend/src/ts/pages/settings.ts

feat: detect custom background image not available (fehmer)

---

frontend/scripts/fontawesome.mjs
frontend/src/styles/fontawesome-5.scss
frontend/src/styles/fontawesome-6.scss
frontend/src/styles/inputs.scss
frontend/src/styles/test.scss

Fix regular icons not working
Update font name for easier swapping

fix: font awesome regular not working

---

backend/src/api/controllers/user.ts
frontend/src/ts/db.ts

Type mismatch between backend and frontend.
Fixes #5485

fix: unable to rename freshly created theme (fehmer)

---

frontend/src/html/pages/settings.html
frontend/src/styles/settings.scss
frontend/src/ts/controllers/theme-controller.ts
frontend/src/ts/pages/settings.ts

Add a button to remove the theme background instead of having the user to remove the text and hit save.

impr: add button to remove custom theme background (@fehmer)

---

frontend/src/html/popups.html
frontend/src/styles/inputs.scss
frontend/src/styles/popups.scss
frontend/src/ts/elements/character-counter.ts
frontend/src/ts/modals/edit-profile.ts
frontend/src/ts/modals/quote-report.ts
frontend/src/ts/modals/quote-submit.ts
frontend/src/ts/modals/user-report.ts

I noticed a backend error when submitting a keyboard description that was too long (75 max), so I thought it would be nice to prevent backend errors and provide some kind of feedback about the number of characters left before submitting a value.

impr: added character-counter component to show how many characters are left in bio and keyboard fields on profile-edit page (theiereman)

---

backend/__tests__/api/controllers/user.spec.ts
backend/src/api/controllers/user.ts
backend/src/api/routes/users.ts
backend/src/documentation/public-swagger.json
backend/src/middlewares/rate-limit.ts

feat: add test activity and streak into to the apekey endpoints (@fehmer)

---

frontend/static/quotes/spanish.json

ID	| translation (deepl)
----|------------
165 | I do not regret this love even if it costs me my heart to love is a miracle and I loved you as I never imagined
166 | Once upon a time there was a little girl in a village, the prettiest little girl you ever saw; her mother was crazy about her and her grandmother even more so. This good woman had had a red riding hood made for her, and it suited her so well that everyone called her Little Red Riding Hood.
167 | Perhaps he didn't intend to hit him, but unfortunately he hit him precisely on the head, so that poor Cricket barely had the strength to say cri-cri-cri, remaining right there stiff and stuck to the wall.
168 | A hungry fox, seeing some bunches of grapes hanging on a vine, wanted to seize them and could not. Leaving, she said to …

impr(quotes): add Spanish quotes (Omaeda)

---

frontend/static/quotes/english.json

impr(quotes): add English quotes (connorcarey)

---

frontend/src/ts/test/practise-words.ts

Repeating the same word multiple times in a row is far from realistic practice. This PR changes the order of words in practice (missed, slow, both) to be randomized.
- Also, please add a screenshot of the theme, it would be extra awesome if you do so!

impr(practice): random shuffle words in all practice modes (grzebiel)

---

frontend/src/html/popups.html
frontend/src/styles/notifications.scss
frontend/src/ts/modals/dev-options.ts

Instead of modifying the element's opacity, we modify the alpha value of the background color. Thus giving us the transparency effect, but also have the desired blur effect.
Closes #5512

fix: notification message readability on hover (navazjm)

---

frontend/src/ts/utils/misc.ts
frontend/static/themes/_list.json
frontend/static/themes/terrazzo.css

Add terrazzo theme inspired by terrazzo floors and the upcoming [keycap](https://geekhack.org/index.php?topic=123215.0) set.
normal 
colorful
flipped
colorful flipped

feat(theme): add terrazzo (@fehmer)

---

frontend/src/ts/elements/test-activity.ts

fix: error when loading account page and quickly navigating to another page (@fehmer)

---

frontend/src/ts/test/test-logic.ts
frontend/src/ts/test/test-ui.ts

refactor: move word wrapper class assignent to a function
refactor: make sure to update word wrapper classes when changing some settings

impr(test ui): changing tape mode no longer restarts the test

---

frontend/static/quotes/english.json

added an english quote from the series invincible

impr(quotes): add English quotes (Tempest76)

---

frontend/static/quotes/spanish.json

add spanish quote from Kevinme789

impr(quotes): add spanish quote (@Kevinme789)

---

frontend/__tests__/elements/test-activity-calendar.spec.ts
frontend/src/html/pages/account.html
frontend/src/styles/account.scss
frontend/src/ts/elements/test-activity-calendar.ts
frontend/src/ts/elements/test-activity.ts
frontend/src/ts/types/types.d.ts

impr: add total tests to test activity chart (@fehmer)

---

frontend/static/quotes/english.json

Adds an English quote from song "Musician".

impr(quotes): add english quote (Ramen2X)

---

frontend/scripts/font-preview.mjs
frontend/src/ts/commandline/commandline.ts
frontend/src/ts/commandline/lists/font-family.ts
frontend/src/ts/pages/settings.ts
frontend/src/ts/types/types.d.ts

Also fixes Comic Sans not working in the settings page.

fix: preview fonts not working correctly in the commandline 

---

frontend/src/ts/elements/alerts.ts
frontend/src/ts/elements/profile.ts

fix: xp bar not updating when claiming rewards (@fehmer)

---

frontend/static/quotes/english.json

feat(quotes): add the walking dead quote (@mxz7)

---

frontend/static/quotes/code_cuda

I browsed GitHub to get CUDA codes and that's all I got, one repo.
- I filtered out the repo with less than 100 stars.
- I did not tried to include source under other licenses than GPL3 or public domain license.
- I did not take learning resources.
- I did not take code without license.
- I did not take few physics-simutlation repos, I wanted data structures or Deep Learning related code.
I am looking forward to see more CUDA quotes, no matter the source =)
Repo source: https://github.com/nosferalatu/SimpleGPUHashTable
It has Unlicense license

impr(quotes): add CUDA quotes (mufusachan)

---

frontend/scripts/font-preview.ts
frontend/scripts/fontawesome.ts
frontend/scripts/tsconfig.json
frontend/vite.config.js

convert font-preview and fontawesome build scripts to use typescript

impr: use typescript for font-preview and fontawesome scripts (@fehmer)

---

THEMES.md

Added the part at the end about adding the thing to _list.json. Pretty much made it, so people will know what to actually add when you do themes. I don't know if this change will matter.
Changed the part in theme.md to add more things, when I made a theme I was asked to add more things to the _list. Idk if the docs: part is correct, or maybe i should've put "other" instead.
Closes #

docs: Updated themes.md (StickminBruv)

---

.github/dependabot.yml

ci: configure dependabot (@fehmer)

---

frontend/static/languages/_groups.json
frontend/static/languages/_list.json

Reverts monkeytypegame/monkeytype#5648

Revert "feat(languages): add portuguese 320k (@jeffersonjpr)"

---

.github/workflows/monkey-ci.yml
frontend/static/languages/_groups.json
package.json

ci: add prettier check in the assets job

---

frontend/static/quotes/spanish.json

I fixed all (hopefully) grammatical errors in Spanish quotes.  I also noted all the changes made and its justifications. 
Fixed IDs:
ID 145:
**Original:** "Me llamo Maximo Décimo Meridio, Comandante de los ejércitos del Norte, General de las legiones felix, Leal servidor del verdadero emperador Marco Aurelio, Padre de un hijo asesinado, Marido de una mujer asesinada y alcanzaré mi venganza en esta vida o en la otra." 
**Fixed:** "Me llamo Máximo Décimo Meridio, comandante de los ejércitos del Norte, general de las legiones Félix, leal servidor del verdadero emperador Marco Aurelio, padre de un hijo asesinado, marido de una mujer asesinada y alcanzaré mi venganza en esta vida o en la otra."
"Maximo" replaced by "Máximo" because that's the correct spelling in spanish. 
"Comandante" replaced …

fix(quotes): grammatical errors in spanish quotes (Dagio2406)

---

backend/src/api/controllers/quote.ts
backend/src/api/controllers/result.ts
backend/src/api/controllers/user.ts
backend/src/dal/leaderboards.ts
backend/src/dal/logs.ts
backend/src/dal/user.ts
backend/src/init/configuration.ts
backend/src/jobs/delete-old-logs.ts
backend/src/middlewares/error.ts
backend/src/utils/logger.ts
backend/src/workers/email-worker.ts

impr(server): store some logs forever (@miodec)

---

.github/pull_request_template.md
.github/workflows/semantic-pr-title.yml

impr(ci): verify pr titles include author name (@rizwanmustafa)

---

.github/workflows/monkey-ci.yml
backend/src/server.ts

Reverts monkeytypegame/monkeytype#5727

Revert "ci: run time improvements (@miodec)"

---

.eslintignore
backend/__tests__/global-setup.ts
frontend/__tests__/global-setup.ts
frontend/vitest.config.js

Make sure tests run in UTC timezone

chore: fix tests using machine timezone (@fehmer)

---

.github/workflows/monkey-ci.yml

ci: fix prettier failing on removed files (@fehmer)

---

backend/__tests__/api/controllers/ape-key.spec.ts

cover fix in 77c9cc423f288aec08d729a56c41edceef16ff7f

chore: add test case for apekey permission bug (@fehmer)

---

frontend/static/languages/english_1k.json

English_1k is actually 999 words. So, I've added one more English word "universe".
Resolves #
Issue #5756

fix(language): add one thousandth word to english 1k (@avick-saha)

---

frontend/static/quotes/german.json

chore: add 3 Paulo Coelho qutoes to german.json (@neinja007)

---

.github/workflows/monkey-ci.yml
backend/src/server.ts

impr(ci): add ability to run ci on draft pull requests (@miodec)

---

frontend/__tests__/utils/config.spec.ts
frontend/src/ts/commandline/lists.ts
frontend/src/ts/config.ts
frontend/src/ts/controllers/preset-controller.ts
frontend/src/ts/db.ts
frontend/src/ts/modals/import-export-settings.ts
frontend/src/ts/utils/config.ts

Migration of legacy config values was removed by accident with pr #5763
Fixes #5787

fix: legacy values in config not getting migrated (@fehmer)

---

frontend/src/ts/modals/share-test-settings.ts

This PR refactors the updateURL function to improve maintainability and readability.
Changes:
- Replaced if-statements with a settingsMap and forEach loop. This way, adding or removing settings is as simple as modifying the settingsMap array.
- Introduced lazy evaluation for share setting values using arrow functions on the `settingsMap` array. Now, values are only computed when they are actually needed, not when the settingsMap is created. Also, values that depend on the current state of the app such as the `getMode2(Config, currentQuote)` function can always get the most up-to-date value.
-  Created a separate updateShareModal function to handle UI updates for better separation of concerns.
I also tested the changes locally to make sure it worked just as before.
- Also please add a …

refactor: updateURL function for improved maintainability (@anthonypz)

---

frontend/src/ts/controllers/input-controller.ts
frontend/src/ts/test/test-ui.ts

A continuation of what was done in c3274f0

refactor: determine active word based on logical value, not DOM class (@NadAlaba)

---

frontend/__tests__/test/misc.spec.ts
frontend/src/ts/constants/default-config.ts
frontend/src/ts/constants/default-result-filters.ts
frontend/src/ts/elements/account/result-filters.ts
frontend/src/ts/test/result.ts
frontend/src/ts/test/test-logic.ts
frontend/src/ts/test/test-stats.ts
frontend/src/ts/utils/misc.ts
frontend/src/ts/utils/results.ts

feat(dev): add deepclone util function (@miodec)

---

frontend/src/styles/test.scss
frontend/src/ts/test/test-ui.ts

Reverts monkeytypegame/monkeytype#5879

revert: use css for heatmap colors (@fehmer)

---

frontend/src/ts/commandline/commandline.ts

Adds `<Ctrl-p>` and `<Ctrl-n>` binds to the command-line. These are from Emacs, but you can navigate up and down menus all over macOS and its apps with these keybinds.
Refactor that removed the binds: https://github.com/monkeytypegame/monkeytype/pull/5180
adding "vim keybinds": https://github.com/monkeytypegame/monkeytype/pull/4019
Confirmed working on macOS (safari, firefox, and chrome). On windows, `<Ctrl-n>`: opening a new window takes priority, but that's expected behaviour.
Closes issue discussed in discord.

impr: add <Ctrl-p> and <Ctrl-n> binds to command-line (@xaskii)

---

frontend/static/quotes/english.json

Add the song Transdermal Celebration by the band Ween as a quote. Specifically part from the first verse that goes "Transdermal celebration, caused a slight mutation in the rift. It toppled down a nation, and left the people running for the hills."

impr(quotes): Add Transdermal Celebration by Ween to english.json (@CoolerFred)

---

frontend/static/quotes/spanish.json

Added Litany Against Fear quote from Dune in Spanish.
Quote id: 176
Spanish: "No debo tener miedo. El miedo mata la mente. El miedo es la pequeña muerte que conduce a la destrucción total. Afrontaré mi miedo. Permitiré que pase sobre mí y a través de mí. Y cuando haya pasado, giraré mi ojo interior para escrutar su camino. Allá donde haya pasado el miedo ya no habrá nada. Solo estaré yo."
English: "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to past over and through me. And when it has gone past, I will turn my inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain."
Closes #

impr(quotes): add Spanish quote (@luis-cvqz)

---

frontend/static/quotes/english.json

Added a quote from Critical Role's Caduceus. It's one of my favorite moments of the campaign.
Youtube clip for reference: https://www.youtube.com/watch?v=9YXdtF3nQG4.

impr(quotes): add English quote (@theendlesswatch)

---

frontend/static/languages/toki_pona.json
frontend/static/languages/toki_pona_ku_lili.json
frontend/static/languages/toki_pona_ku_suli.json

toki pona was missing the words ale, and its less used pronunciation variant ali.

fix: adding missing toki pona word (@anakojm)

---

frontend/src/html/pages/about.html

Paragraph under heading "keybinds" did not follow punctuation patterns of other paragraphs on the site. This has been fixed in this commit.
Closes #

chore(about): small typo (@weather7774)

---

frontend/static/quotes/spanish.json

I added phrases from texts I found in an [old language book][1] at home. The translations were made with deepl, but as they are old texts and use language in a poetic way the translations can be imprecise.
|ID|spanish|english|
|--|--|--|
|177|Su traje era sencillo, de bota a la inglesa, pantalón y chaqueta de paño fino azul, sombrero redondo, sin más distintivo que el sable y la faja de malla de seda de color carmesí|His costume was simple, with English-style boot, pants and jacket of fine blue cloth, round hat, with no other distinguishing feature than the sabre and the crimson silk mesh sash.|
|178|El que desea llegar, no encuentra impedimento en el engaño de la niebla|Those who wish to arrive find no impediment in the deception of the fog.|
|179|Junto a la casa cerrada están en flor …

impr(quotes): add spanish quotes (@omaeda)

---

frontend/static/layouts/_list.json

a layout made for Turkish by TÜBİTAK between 2011 and 2014.
added Turkish E layout made by TÜBİTAK made in 2014.
@jirmu 
Closes #

feat(layouts): added Turkish E layout (@jirmu)

---

frontend/static/languages/english_10k.json

fix(language): remove british spelling of `counselling` from english 10k (@aoi-buh)

---

frontend/static/quotes/english.json

Added a new quote to the database:
"Aren't past and future just as real, sometimes even more real, than the present? After all, the past determines who we are, as well as how we perceive and behave in the present. And our goals determine which actions we take in the present."
Source: 'The Power Of Now' (ID: 7615, Length: 239)
This PR adds a new quote to the database from the book "The Power Of Now." 
Translations are not included in this PR as they were not part of the change scope.
- [ x] Adding quotes?
- [x ] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x ] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for …

impr(quotes): add English quotes (@kennethlg)

---

packages/contracts/src/users.ts

"underscare" typo fixed to.
Closes #6119

chore: fix typo (@m4dd0c)

---

frontend/static/quotes/english.json

Related: https://github.com/monkeytypegame/monkeytype/discussions/6054

impr(quotes): grammar fix for English quote 192 (@mak448a)

---

frontend/static/quotes/dutch.json

Added Dutch quotes.
Dutch quotes translation:
- "Give all your money to the poor people... If they do the same maybe you'll get it back tomorrow."
- "Remove the word 'me' from the language use and the whole humanity is perplexed and has panic sweat on their forehead."
- "A James Bond novel is stupid but exciting, while a masterpiece of Flemish literature is equally stupid but boring as well."
- "I am absolutely against the purity of the language. If it brings something essential, you should cultivate Anglicisms, Germanisms and Gallicisms immediately. I do not believe in the thinned-out, which is presented as the only Dutch, I am irritated by the Dutch domination."
- [X ] Adding quotes?
- [X ] Make sure to include translations for the quotes in the description (or another comment) so we …

impr(quotes): added dutch quotes (@petieken)

---

frontend/src/ts/config.ts
frontend/src/ts/test/test-ui.ts

impr: center mini stats when using tape mode (@notTamion)

---

frontend/static/quotes/english.json

Monkeytype already has several Star Trek quotes, but it's missing this one from Kirk, this PR adds it:
> If change is inevitable, predictable, beneficial; doesn't logic demand that you be a part of it?
([source](https://www.imdb.com/title/tt0708438/quotes/?item=qt5409859))

impr(quotes): Add Star Trek quote from Kirk about change (@ItsDrike)

---

frontend/src/ts/test/words-generator.ts
packages/funbox/package.json
pnpm-lock.yaml

fix: funbox plus x not working with custom text using pipe delimiter (@fehmer)

---

frontend/static/quotes/french.json

Removes catched english quotes in the french quotes file

fix(quotes): remove english quotes in french file (@raffaeldp)

---

frontend/static/quotes/german.json

feat: Add a quote of Patent Ochsner in the file.
Just add one quote from Patent Ochsner to lighten up everybody's day (translation):
"A glass to love and one to the full life. And one to that which we cannot hold. One gate opens and another closes. You stay in my heart, even when it starts to hurt."

feat: Add quote to german.json (@boessu)

---

frontend/package.json
pnpm-lock.yaml

Upgrade to vite 6. Closes #6201.

chore: upgrade to vite 6 (@miodec)

---

frontend/static/quotes/english.json

impr(quotes): add English quote (@zev18)

---

frontend/static/themes/_list.json
frontend/static/themes/github.css

Added new theme "github" with colors used from GitHub.
Theme screenshots:

feat(theme): add github (@KevinRnbrg)

---

frontend/static/languages/english_10k.json

This word does not appear in Oxford English Dictionary, Merriam-Webster dictionary, dictionary.com or any other dictionary as a real word. Even the windows spelling checker feature marks it as a wrong spelling. I'm not sure how it even found its way into here.
removed "techrepublic" from the corpus
stop-png
Closes #

impr(english_10k): remove "techrepublic" (@stop-png)

---

frontend/static/quotes/vietnamese.json

Taken from TV show "Gặp nhau cuối năm" or more commonly referred to as "Táo Quân".
Translations (sorted by ID)
---------------------------------
- 101: Giàu thì nó ghét, đói rét thì nó khinh, thông minh thì nó tìm cách tiêu diệt.
_(If you're rich, they hate you; if you're poor, they despise you; if you're intelligent, they try to destroy you.)_
- 102: Nước trong thì không có cá, mà người tốt quá thì không ai chơi.
_(Clear water has no fish, and a person who is too good has no friends.)_
- 103: Cống rãnh mà đòi sóng sánh với đại dương, kênh mương mà đòi tương đương với thủy điện.
_(A gutter dares to compare itself with the ocean, and a canal dreams of being equal to a hydroelectric dam.)_
- 104: Đã làm thì không nói không, không nói khó, không nói có mà lại không làm. Chỉ bàn làm chứ không …

impr(quotes): add Vietnamese quotes (@freshleaf1095)

---

monkeytype.code-workspace

Setting was renamed by vscode https://code.visualstudio.com/docs/getstarted/settings

refactor: update setting automaticallyOpenTestResults in workspace file (@fehmer)

---

frontend/src/styles/index.scss
frontend/src/styles/vendor.scss

Move normalize.css and fontawesome to vendor.scss

refactor: move normalize and fontawesome to vendor.css (@fehmer)

---

frontend/src/styles/fonts.scss

fix(font): CommitMono not working (@fehmer)

---

backend/package.json
backend/redocly.yaml
pnpm-lock.yaml

Use latest version to get rid of the configuration warnings.

chore: update @redocly/cli (@fehmer)

---

backend/src/api/routes/docs.ts

Latest update of redocly cli changed the cdn domain.

fix: fix csp entries for redocly (@fehmer)

---

frontend/static/quotes/english.json

impr(quotes): add English quotes (@thedev0ps)

---

frontend/src/ts/modals/simple-modals.ts
frontend/src/ts/utils/simple-modal.ts
packages/contracts/src/users.ts

alternative approach for 535700f0c5861171bb4bad5538c8f699f154ca3f

refactor: use validation on email update modal (@fehmer)

---

backend/src/workers/email-worker.ts
backend/src/workers/later-worker.ts

impr: Log failed worker queue jobs (@fehmer)

---

frontend/src/ts/test/words-generator.ts

The `·` (U+00B7, middle dot or "ano teleia") is a valid punctuation mark in Greek. However, it has fallen into disuse in contemporary times. Most people know it's meaning but very rarely use it in texts. They opt for period (`.`) or commna(`,`) depending on context.
There's a practical reason for removing it too. You can't easily input it. There isn't a dedicated key on a keyboard for it.
On Windows, you have to use `Alt`+`0183` AND have a numpad. If you have eg a 75% keyboard you can't use that.
Keeping this punctuation mark makes the "punctuation mode" totally unusable for training touch typing.
PS: I hope I did the changes in the correct place. I didn't actually "compile" the project to test if it  works.
- Also please add a screenshot of the theme, it would be extra awesome if you do …

fix: Remove seldomly used punctuation mark from Greek lang (@sledgehammer999)

---

frontend/src/ts/pages/account.ts

Account page:
* remove unnecessary &
* build punctuation and number strings only if they're going to be used

fix(account page): tidy up highest wpm description (@cosmatevs)

---

frontend/src/ts/utils/url-handler.ts

Some people have old links with test settings we should support.

fix: handle legacy test settings urls (@fehmer)

---

frontend/static/quotes/english.json

Added two quotes: the introduction sequences from the games Undertale and Deltarune.

impr(quotes): add English quotes from Undertale and Deltarune (@HotDog640)

---

frontend/__tests__/elements/test-activity-calendar.spec.ts
frontend/__tests__/utils/date-and-time.spec.ts
frontend/__tests__/vitest.d.ts
frontend/src/html/pages/account.html
frontend/src/styles/account.scss
frontend/src/ts/db.ts
frontend/src/ts/elements/test-activity-calendar.ts
frontend/src/ts/elements/test-activity.ts
frontend/src/ts/pages/test.ts
frontend/src/ts/utils/date-and-time.ts

feat(account page): start test activity graph on the users first day of the week (@fehmer)

---

frontend/vite.config.prod.js

minify json files for prod build

chore: minify json files (@fehmer)

---

frontend/static/quotes/lithuanian.json

Translations:
Lithuanian: `Pelėsiais ir kerpe apaugus aukštai Trakų štai garbinga pilis! Jos aukštus valdovus užmigdė kapai, O ji tebestovi dar vis.`
English: `Overgrown with mold and lichen, the high and venerable castle of Trakai is here! Its high rulers have fallen asleep in tombs, And it still stands.`
Lithuanian: `Ko ko, bet kvailių visur yra daugiau, negu reikia. Kiekviena tauta jų turi ir sau, ir eksportui pakankamai, lygiai kaip kiekviena tauta turi nuosavus latrus ir šventuosius.`
English: `Whatever, there are more fools everywhere than necessary. Every nation has enough of them for itself and for export, just as every nation has its own saints and saints.`
Lithuanian: `Lietuva, Tėvyne mūsų Tu didvyrių žeme, Iš praeities Tavo sūnūs Te stiprybę semia.`
English: `Lithuania, our …

impr(quotes): add lithuanian quotes (@Kurbamit)

---

frontend/src/ts/pages/settings.ts

When changing the layoutfluid settings via cmdline the settings page did not update.
This also happens on prod so it is not directly related to the change #6445

fix(settings): Update layoutfluid on config change (@fehmer)

---

frontend/static/themes/_list.json
frontend/static/themes/vesper.css

Adds Vesper theme. Based on Vesper for VSCode theme from [Rauno Freiberg](https://github.com/raunofreiberg/vesper)

feat(theme): add Vesper theme (@SameerJS6)

---

frontend/src/ts/commandline/lists.ts
frontend/src/ts/pages/settings.ts

Dropdowns for layoutfluid and polyglot were not rendered correctly after logout/login

fix(settings): fix dropdown not rendered correctly (@fehmer)

---

frontend/static/themes/_list.json
frontend/static/themes/sunset.css

Just added a new theme (I tried my best to not make this similar to any themes, but if it is similar to one, please tell me!)

feat(theme): Add sunset theme (@catdogdonkey)

---

frontend/src/ts/elements/settings/settings-group.ts
frontend/src/ts/pages/settings.ts

fix(settings): fix error when setting keymap layout (@fehmer)

---

frontend/static/quotes/polish.json

Added 50 quotes from books in polish
Translations:
And believe me, although you will see many wonders while wandering around the world, you will not find a river like the Vistula or a city like Warsaw anywhere. - "id":151
Above all, however, one must be able to win people's hearts. Understanding and tolerance are the best way to do this. - "id":152
Don't laugh, my friend, at someone else's downfall, because then no one will regret you either! - "id":153
In a distant and wild land you will find what others will search for in vain. When you do, you will gain a best friend who will never say a word... - "id":154
He does not deserve pity who has no pity himself. - "id":155
However, you must understand that obedience does not mean limiting your independence. - "id":156
The mind needs books …

impr(quotes): 50 new quotes for polish language from books (@sobczaktm)

---

frontend/src/ts/commandline/lists/result-screen.ts
frontend/src/ts/test/screenshot.ts
frontend/src/ts/test/test-screenshot.ts
frontend/src/ts/test/test-ui.ts

This Pull Request introduces the functionality to download the result screenshot directly as a PNG file, in addition to the existing option to copy it to the clipboard.
This is achieved by:
1.  Refactoring the screenshot logic in `test-ui.ts`.
2.  Adding a new `Download screenshot` command to the result screen command list.
**Changes Made:**
*   **`frontend/src/ts/test/test-ui.ts`**:
*   Created an internal function `generateScreenshotCanvas` that encapsulates UI preparation, canvas generation with `html2canvas`, and UI restoration.
*   Modified the exported `screenshot` function to use `generateScreenshotCanvas` and **only** handle copying the resulting Blob to the clipboard (with the fallback of opening in a new tab).
*   Added a new exported function `getScreenshotBlob` that uses …

feat(commandline): add download screenshot command (@torturado)

---

frontend/__tests__/utils/config.spec.ts
frontend/src/ts/utils/config.ts

Handle legacy values for indicateTypos.
Fixes FRONTEND-MJ

fix(settings): handle boolean values for indicateTypos (@fehmer)

---

frontend/src/ts/test/test-ui.ts

fix(wordsInput): adjust #wordsInput position to be on the active word for chinese (@NadAlaba)

---

frontend/src/html/popups.html
frontend/src/privacy-policy.html
frontend/src/ts/controllers/analytics-controller.ts
frontend/src/ts/cookies.ts
frontend/src/ts/index.ts
frontend/src/ts/modals/cookies.ts
frontend/src/ts/ready.ts
frontend/src/ts/sentry.ts

Also refactors cookie modal and cokie local storage a little bit.
closes #6557

chore: update privacy policy to mention sentry (@miodec)

---

frontend/src/html/pages/account.html
frontend/src/ts/elements/account/result-filters.ts
frontend/src/ts/pages/account.ts

Stacking event listeners go brrrrrrr

perf: fix account page getting slower with every load (@miodec)

---

frontend/src/ts/constants/default-result-filters.ts
frontend/src/ts/controllers/account-controller.ts
frontend/src/ts/elements/account/result-filters.ts
packages/contracts/src/schemas/users.ts

Merge with default filters to ensure all languages and funboxes are present in the result filter.

fix(account): fix not all results shown if result has a funbox unknown to stored filter (@fehmer)

---

frontend/static/languages/code_common_lisp.json

fix(language): Common Lisp Function Typo (@hikettei)

---

frontend/src/ts/elements/xp-bar.ts

Only show accPenalty if it's relevant. Still need to build and test :)
Closes #

fix(xp-bar): don't show attribute if it's 0 (@jackrosenberg)

---

frontend/src/ts/controllers/input-controller.ts
frontend/src/ts/test/test-ui.ts

fix(zen): remove input length check to prevent jump to hidden line (@byseif21, @NadAlaba)

---

frontend/static/quotes/polish.json

Description
15 polish movie quotes
Checks
Translations:
Grzegorz Brzęczyszczykiewicz. Chrząszczyrzewoszczyce, Łękołody County.- "id":201
I am reporting obediently, Colonel, I caused this war completely unintentionally. - "id":202
Everyone can help their luck, everyone can win today. Black loses, red wins. One, two, three... - "id":203
He died on the way, certainly from his wounds.  - It wasn't from his wounds, sir! The plum brandy!- "id":204
You, come here. Where are you going? Come here to the master. How good! What a pretty lady he has! Only she's so serious... And why is she so serious, huh? Fat... Well, come on. What, some good peppers? Eat, eat. If you don't eat, the lady will lock you up in a hole like us here. - "id":205
Darkness, I see darkness, I see darkness. - "id":206
Saved! …

impr(quotes): 15 polish movie quotes for polish language (@sobczaktm)

---

frontend/src/ts/pages/profile.ts

fix(profile): remove previous error message on page load (@fehmer)

---

frontend/src/ts/config.ts
frontend/src/ts/controllers/route-controller.ts
frontend/src/ts/test/funbox/list.ts
frontend/src/ts/test/test-logic.ts
packages/contracts/src/schemas/configs.ts
packages/funbox/src/list.ts

feat(funbox): add no quit (@miodec)

---

frontend/static/quotes/polish.json

Description
15 polish proverbs and other quotes for polish language
Checks
Translations:
Agreement is reached when one party pretends to believe the nonsense told by the other. - "id":216
Only six people in the Galaxy knew that the president's job was not to wield power, but to distract from it. - "id":217
I have become death, the destroyer of worlds. - "id":218
If something is impossible to do, let the Poles do it.- "id":219
It's not how long you live, but how wisely you live. It's never too late to learn and grow. Wisdom is priceless, regardless of age. - "id":220
Don't waste time, for it is the stuff life is made of. - "id":221
You praise others, you do not know your own, you do not know what you have. - "id":222
Don't argue with a fool because he will drag you down to his level and …

impr(quotes): 15 polish proverbs and other quotes for polish language (@sobczaktm)

---

frontend/src/ts/config-metadata.ts
frontend/src/ts/config.ts

refactor(config meta): split into its own file (@miodec)

---

frontend/static/quotes/code_java.json

Fixes some compilation issues in the java quotes.

fix(quotes): code_java compilation fixes (@nafets-st)

---

docker/example.env

Improved the `docker/example.env` file to make it more beginner-friendly and easier to configure for self-hosters.
Changes made:
- Added section headers for clarity (e.g. Required Config, Firebase Config, etc.)
- Clarified which settings are optional (Firebase, email, ports)
- Added better inline comments explaining each env variable
- Improved formatting and spacing for better readability
---
---
N/A

docs(example.env): improve clarity of docker/example.env config for self-hosting (@nitin-is-me)

---

frontend/src/ts/controllers/account-controller.ts

fix(login): clear data on logout (@fehmer)

---

frontend/src/ts/pages/settings.ts

fix(settings): dismiss tooltips on funbox buttons after click (@byseif21)

---

frontend/__tests__/root/config-metadata.spec.ts
frontend/__tests__/root/config.spec.ts
frontend/src/ts/config-metadata.ts
frontend/src/ts/config.ts
frontend/src/ts/controllers/account-controller.ts
frontend/src/ts/controllers/preset-controller.ts
packages/funbox/src/validation.ts
packages/funbox/tsconfig.json

fix: config applying issues (@miodec, @fehmer)

---

frontend/src/styles/media-queries-blue.scss

in the smaller screens it's not looking the best 
* now

impr(settings-page): responsive local font button style (@byseif21)

---

frontend/static/themes/8008.css

the 8008 theme had a duplicate `--sub-alt-color` set to `#000000`
- Make sure to follow the [themes documentation](https://github.com/monkeytypegame/monkeytype/blob/master/docs/FONTS.md)
- [O] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [O] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [O] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

fix: 8008 theme duplicate sub-alt-color (@tboex)

---

frontend/src/html/pages/about.html

Changed punctuation in the about page. We can also make the text in the parenthesis a standalone sentence by just removing the parenthesis.

chore: Changed punctuation (@Leonabcd123)

---

frontend/src/ts/utils/url-handler.ts

fix for https://www.reddit.com/r/monkeytype/comments/1n0p9fk/custom_timer_changes_to_number_of_words_when/

fix(testSettings): link with custom limit not applied correctly (@fehmer)

---

frontend/src/ts/elements/input-validation.ts
frontend/src/ts/modals/simple-modals.ts
frontend/src/ts/pages/login.ts
packages/contracts/src/users.ts
packages/schemas/src/users.ts

fix: password validation rules (@fehmer)

---

frontend/src/ts/test/result.ts

The result chart burst axis maximum Y value needs to be updated after adding the personal best line to keep the chart scale the same as the wpm and raw lines.
- Make sure to follow the [themes documentation](https://github.com/monkeytypegame/monkeytype/blob/master/docs/FONTS.md)
Closes #
#6979

fix: Set result chart burst Y axis max after adding PB line (@Ed-k)
