monkeytypegame/monkeytype

public/themes/bliss.css, public/themes/list.json
Add a theme based off of 'SA Bliss'
=> Add theme 'Bliss'

public/js/commandline.js
Return theme sorting to alphabetical order after the theme refactor.
=> Fix theme sorting

public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
Resolves #102 
Added timer bar hide functionality
Toggling works, changing from settings works, set to "on" by default.
Let me know if there is anything that can be improved, I am 10000% open to suggestions and critique. First time contributing to Open Source :)
=> Hide timer bar

public/css/style.scss, public/themes/9009.css, public/themes/bingsu.css, public/themes/botanical.css, public/themes/list.json
Adds 3 Themes:
* Botanical
* Bingsu
* 9009
Trying some different things with some, feel free to change as you see fit but I think they all free pretty good.
=> Add themes

public/themes/vaporwave.css
May have gotten a few colors mixed up, so sorry about that and will try to fix once I can see it :p
=> GMK Vaporwave

public/css/style.scss
fixed issue #177
This is my first contribution to a project. So I'm sorry if I did something wrong
=> fixed issue #177

public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js, public/themes/aether.css, public/themes/froyo.css, public/themes/future_funk.css, public/themes/list.json, public/themes/milkshake.css, public/themes/retrocast.css
Added Aether, FroYo, Milkshake, Future Funk, and Retrocast color themes.
Added a setting to change the opacity of the live WPM text.
=> added various color themes and timer opacity setting

public/themes/graen.css, public/themes/list.json
https://geekhack.org/index.php?topic=105244.0
=> Added Graen theme

public/themes/list.json, public/themes/watermelon.css
[GMK Watermelom](https://geekhack.org/index.php?topic=107464.0)
=> added watermelon theme

public/index.html
Remove "space" as a key to restart test
=> Update Restart Shortcut text

public/themes/deku.css, public/themes/ishtar.css, public/themes/list.json, public/themes/mashu.css
wanted to add some more variety for the themes on the site
=> added GMK Ishtar, Deku, and Mashu themes

public/css/style.scss, public/index.html, public/js/commandline.js, public/js/fonts.json, public/js/script.js, public/js/settings.js, public/js/userconfig.js
Fixes #111, Font Customization
Added Roboto Mono, Source Code Pro, IBM Plex Mono, Inconsolata, and Fira Code.
Fonts are sourced from [Google Fonts](https://fonts.google.com/)
=> added font customization

public/themes/cafe.css, public/themes/list.json
[GMK Café](https://cannonkeys.com/products/gb-gmk-cafe)
=> added cafe theme

public/funbox/list.json, public/js/misc.js, public/js/script.js
random numbers with a length between 1-7
=> added 58008 to funbox

public/themes/alpine.css, public/themes/list.json
Added theme for GMK Alpine
[GMK Alpine](https://geekhack.org/index.php?topic=107618.0)
=> alpine theme

public/themes/list.json, public/themes/superuser.css
https://geekhack.org/index.php?topic=106829.0
=> added superuser

public/css/style.scss, public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
Add a new behavior mode that hides the next two words.
=> Add read ahead mode.

public/css/style.scss, public/index.html, public/js/settings.js, public/js/userconfig.js
Preview: https://i.imgur.com/hKmWLe1.gif
Warning: untested from a logged-in user's perspective since I don't have my environment fully set up yet.
Feel free to either wait for me to set it up or merge it in if it looks ok.
=> added reset settings button

public/js/script.js
Sorry, my bad for introducing this bug. High priority since custom tests don't work past 60 words.
=> fixed a bug with custom tests not getting leftToRight properly

public/index.html
This commit fixes the incorrect spelling of "changes" ('chages') in the settings menu.
=> Fix spelling error

public/js/commandline.js
Just something handy that I've been wanting for quite some time :) Wanting to change to a different random theme one-off instead of changing every test session.
=> Added randomiseTheme to commandline

public/css/style.scss, public/index.html, public/js/userconfig.js
Another handy one specially when random themes are enabled so you'll know the names of potential favorites :)
=> Display theme below the version

public/js/account.js
https://discord.com/channels/713194177403420752/713195089303830548/759446697742434314
=> Fix result chart for accuracy when start at zero is disabled

CONTRIBUTING.md
I wrote some short instructions for new contributors, as I had trouble getting the CSS to work as someone who is new to open source. I think that this edit will make the instructions more clear so that anyone who wants to contribute can just go trough the instructions step by step, without any extra google-ing.
=> Added instructions to setup SASS compilation with Easy Sass.

public/css/style.scss
https://discordapp.com/channels/713194177403420752/713195115275091969/762797016346132510
=> Fix for typo getting cut off at the bottom lines

public/themes/lil_dragon.css, public/themes/list.json
Added theme for Lil Dragon
[Lil Dragon](https://geekhack.org/index.php?topic=108950.0)
=> Lil Dragon Theme

public/index.html, public/js/commandline.js
=> Command for views

public/themes/list.json, public/themes/paperColor.css
Ported from [vim paperColor-theme ](https://github.com/NLKNguyen/papercolor-theme)
Preview:
=> add "paperColor" theme

public/themes/drowning.css, public/themes/list.json
=> Added drowning theme

public/css/style.scss, public/js/fonts.json
=> changed IBM Plex Mono to IBM Plex Sans

public/css/style.scss
Instead of using id's to select keys to hide, use nth-child so it's universal.
(on the right is live, and on the left is the commit, both are set to dvorak)
=> Fixed certain keymaps in matrix mode

public/css/style.scss, public/index.html, public/js/settings.js
=> Added option to import and export using JSON

functions/index.js, public/css/style.scss, public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
make the layouts save when selected (wouldnt save after 1 or 2 refreshes). and make it so when layoutfluid is off, highlight the correct layout as being the selected one (visual fix).
=> Saved layout fix and settings visual fix

public/index.html, public/js/commandline.js, public/js/script.js, public/js/settings.js, public/js/userconfig.js
=> added change highlight mode

public/themes/darkmagicgirl.css, public/themes/list.json, public/themes/magicgirl.css
hello! lmk if this looks okay or if i need to make any changes. ty <3
=> adds magic girl and dark magic girl css color themes

package-lock.json, src/js/commandline.js, src/js/script.js
- smaller keymap name
- added enable ads to command line
=> added enable ads to command line

src/js/account.js
I wasn't able to view the accounts page, as logging in on the local copy was giving me some trouble. But given the simplicity of the change I suspect it should be fine. I would appreciate someone verifying it behaves as expected.
=> Added hover text to graph button

static/index.html
=> added quick navigation shortcuts to  settings page

src/js/commandline.js, static/themes/list.json, static/themes/onedark.css
Added result page options to the commandline, so you don't have to take your hands off of the keyboard after a test.
=> Added result options to commandline

src/js/script.js, static/index.html
Countdown timer popping at typing page only
=> Fix countdown timer in memory mode

src/js/account.js, src/js/commandline.js, src/js/db.js, src/js/leaderboards.js, src/js/script.js, src/js/settings.js, src/js/userconfig.js
Removing commented code makes it easier to see what's actually going on.
=> Removing code comments

src/js/script.js
=> fix caret position inconsistency caused by enabling hide extra letters

src/js/script.js
Semicolon in punctuation mode. Part of #539.
=> Add semicolon in punctuation

src/js/layouts.js
Bépo is a new layout optimised for french language
=> Added Bépo, an optimised layout for french

README.md
=> Updated README.md - Added monkeytype artwork

src/js/script.js
Added
single quotes ''
parentheses ()
braces {}
brackets []
to the punctuation mode
=> Punctuation mode updated

static/privacy-policy.html
number of times sounds better than the amount of times.
=> Updated the quantifier in privacy page

static/languages/swedish.json, static/languages/swedish_1k.json
Turns out it was a JSON syntax error :facepalm:
=> Fixed issue #712 about Swedish erroring out out.

static/themes/lavender.css, static/themes/list.json
Added theme for **GMK Lavender**. Have updated `list.json` as needed. Let me know if there are any required changes!
=> Added theme for GMK Lavender

src/js/script.js
=> Revert "Ignore keys with Alt modifier"

static/languages/indonesian.json
forgot to remove `,` at line 275
=> excess comma cause errors in indonesian.json

src/js/account.js, src/js/db.js, src/js/monkey.js, src/js/userconfig.js
Fixed some build warnings:
- Fixed warning for `db.js` at line 273
- Fixed warning for `db.js` at line 289
- Fixed warning for `monkey.js` at line 21
- Fixed warning for `monkey.js` at line 30
- Fixed like 100 of the big long list of index.js
=> Fixed some of the build warnings

CONTRIBUTING.md, src/js/account.js, src/js/script.js
currently, if you visit the website on a browser that doesn't support the api's used by the screenshot api you just an error message or, you're not allowed to do this in firefox.
this pr allows you to open the image in a new tab if we fail to copy it to your clipboard.
=> allow the screenshot feature in other browsers 

static/languages/code_go.json, static/languages/list.json
Added [Golang keywords](https://golang.org/ref/spec#Keywords).
=> Added Go language

static/themes/list.json, static/themes/sonokai.css
This is an amazing theme similar to monokai.
[Also, a screenshot of the new theme](https://i.imgur.com/xSC844h.png)
=> Added the sonokai theme

src/js/commandline.js
Introduced by my own #750, I missed the last `else`. This fixes it by wrapping it inside another `if`, I hope it's fine like that!
=> Fix swapEscAndTab sometimes failing on Esc

src/js/commandline.js, src/js/script.js
[Again](https://github.com/Miodec/monkeytype/pull/803#issuecomment-756371873), sorry for the PR spam about this and not testing them well enough
=>  Have Esc always close commandline/leaderboards (final fix)

src/js/commandline.js
Can now move selection with Alt + J and Alt + K  :)
An option to decide whether or not to judge these keys by position or value could also be added, or a way to choose a custom set of keys for this dynamically, because layouts are gonna move these around.
Personally I'm fine with just this for now though.
=> Add Alt+ Vi-like bindings to command line

README.md, src/js/account.js, src/js/commandline.js, src/js/db.js, src/js/global-dependencies.js, src/js/script.js, static/index.html
Now you can use your average speed as your pacemaker speed. #370 
I do it with the 10 last speeds because I think it is better than with all time scores. If you think that it would be better with all time scores let me know.
=> Added an personal average pace maker

src/js/script.js
=> Revert punctuation/numbers after practice

static/themes/list.json, static/themes/stealth.css
=> Add the stealth theme

src/js/script.js
Fixes quick tab on result screen
=> Don't try to focus on result screen

src/js/script.js
Made default behavior
Video:
https://user-images.githubusercontent.com/21978144/104644920-2b31e600-568d-11eb-9fb0-cb2b76f4fe39.mp4
=> Update live accuracy on keypress

.prettierignore
the file is moved so it should also be renamed in `.prettierignore`
=> FIX: the english_quotes.json is moved to quotes as english.json

static/quotes/english.json
=> fixed one quote - English

static/quotes/english.json
=> fixed quote typo

static/languages/swedish.json
=> removed 'mr' from swedish.json

src/js/layouts.js
https://sites.google.com/alanreiser.com/handsdown#h.7vp2l0jfbr5z
=> added handdown alt layout

static/quotes/english.json
=> fixed 3 quote bugs

static/languages/_list.json
=> English 450k

src/js/script.js
Fixes problem introduced by #905 where keyboard is always ignored
=> Fix isTrusted check on keyboard events

src/js/script.js
=> Fix nospace simulated space events getting ignored

static/quotes/indonesian.json
add quotes from Indonesian figures
=> add quotes from Indonesian figures

src/js/script.js
fixed PrintScreen being inserted as text like Pause in #941
=> fixed PrintScreen key being inserted as text

static/quotes/dutch.json
Added a couple of Dutch quotes
=> Added Dutch quotes

CONTRIBUTING.md
Just ran through the setup and had to do this extra step to use localhost while logged in.
=> Add firebase auth setup to contributing guide.

static/quotes/dutch.json
=> Added quotes

static/quotes/code_rust.json
All the quote are taken from programming-idioms.org
- Alternative implementation  of each idiom is split to a new quote.
=> Add code_rust quotes from programming-idioms.org

CONTRIBUTING.md
Dev server does not work without enabling firebase firestore. I've added the step to CONTRIBUTING.md so that future contributors do not have this issue.
=> Added enable firebase firestore step to contributing.md

src/js/script.js, src/sass/style.scss, static/index.html
Quote search redone, Table now produces 200 results and is scrollable
=> Quote Search V2.0

static/quotes/indonesian.json
Removed a quotation mark
Added some full stops
---
=> Fix typos in Indonesian Quotes

static/quotes/indonesian.json
Fixes :
- Changed `2 ½` to `dua setengah` so user can type it
- Added missng first name and missing spaces
_Quotes source : jagokata.com (Top 100 quotes)_
----
=> Added more quotes in Indonesian and few fixes

static/index.html
Literally says it all :)
I just wanted to add this as a small touch.
I mainly was irritated by the test in "Restart test" not being capitalized (I don't know if it isn't supposed to be capitalized but it does look more neat).
And added one smily (Got carried away)
=> Added a few Capitalizations

.firebaserc_example, static/quotes/portuguese.json
Added 18 new quotes to portuguese.json file since there
only were two.
Talked with @Miodec about some changes it made to package-lock.json when running npm install. Hope there isn't any problem with the code.
=> Added new quotes to portuguese language

static/quotes/polish.json, static/quotes/vietnamese.json
I would like to add a few quotes in Polish. I also noticed an error in the file structure for the Vietnamese language.
=> added some quotes in Polish

static/themes/_list.json, static/themes/grand_prix.css
=> feat: add Grand Prix Theme

src/js/quote-search-popup.js, src/js/settings.js, src/js/word-filter.js, src/sass/style.scss
Added word filter to custom text mode
Fixed custom fonts
=> Words Filter

src/js/commandline-lists.js
=> fix `changeQuoteLengthAll` command

src/js/config.js, src/js/settings.js, src/js/theme-controller.js, src/sass/style.scss, static/index.html
Added option in settings to have custom background images.
=> Custom Background Images

src/js/commandline-lists.js, src/js/config.js, static/index.html
added change custom background to command line
=> Custom Background to Command Line

src/js/commandline-lists.js, src/js/commandline.js, src/js/config.js
changed the custom background input on the command line to auto input the current background image URL
=> command line input autofill

static/themes/_list.json, static/themes/mountain.css
Add support for Mountain theme (https://github.com/pradyungn/Mountain)
=> Add mountain theme

gulpfile.js, src/js/config.js, src/js/popups/custom-background-filter.js, src/js/settings.js, src/js/theme-controller.js, src/sass/style.scss, static/index.html
Added custom background image filter options on sliders
added option to fit background image from corner to corner
=> Custom background image filter

src/js/input-controller.js
From
```
if on test page && not command line
restart
else
go to test page and restart
```
to
```
if not command line
if on test page
restart
else
go to test page and restart
```
=> Don't quick tab restart when command line is open

static/quotes/english.json
=> Added Maze Runner quotes

static/privacy-policy.html
=> Link monkeytype logo to main page

src/js/config.js
Hopefully should satisfy ebe7f02593f47498bdea1f1dfe9e46594107b1f2 and closes #1161
=> Disables pb caret when not signed in

src/js/settings.js
=> Fix layout buttons on the settings page

static/quotes/lithuanian.json
Is there a file or a folder which I also have to edit to add new quotes file?
=> Lithuanian quote list.

src/js/misc.js, src/js/popups/word-filter-popup.js
The first error allowed to enter two spaces, so each word passes the regular expression test.
=> fix words filter

static/quotes/code_javascript.json, static/quotes/code_python.json, static/quotes/french.json
Added quotes to : french.json, code_javascript.json.
Created quotes/code_python.json
=> New quotes for : python - javascript - french

static/quotes/lithuanian.json
Fixed the en dash and added a quote.
=> Fixed the en dash.

static/quotes/french.json
I thought I removed the "œ" from this quote but I hadn't. Sorry about that...
(there's no easy way to type "œ" with the French layout)
=> replaced œ by oe in french quote

static/languages/portuguese_3k.json
There was an empty word in the portuguese_3k list. I apologize for that.
=> Empty word removed.

src/js/commandline.js, src/js/theme-controller.js
This commit fixes #1326. The code to check if commands changed the theme is not relevant when random theme is on, so I added a condition to check if the theme is random.
=> Fixed command line random theme bug #1326

src/js/commandline.js
The last pr didn't address the hover or scroll functions which can also change the active theme.
=> Command Line interferring with the random theme fully fixed

static/quotes/turkish.json
Most of the short ones are idioms. Most of the medium sized ones are from well known Turkish poems. Long ones are from well known Turkish stories and a couple from Harry Potter series.
=> 39 Turkish quotes of various lengths added

static/themes/_list.json, static/themes/midnight.css
=> Midnight Theme

static/languages/english_25k.json
This should be a self-explanatory change.
=> Remove offensive word from English 25k

static/themes/_list.json, static/themes/communism.css
Added a simple yellow and red classic communist theme.
=> Communism Theme

src/js/settings.js
Fixed #1404, my bad, didn't give myself enough time to test the code when implementing the preset features.
=> Fixed #1404 tags appearing to be active

src/sass/style.scss
=> Fixed issue with accent colors

src/js/replay.js, src/js/test/test-ui.js
=> Update replay timer on text click and lint warning fix

static/themes/_list.json, static/themes/blueberry_dark.css, static/themes/blueberry_light.css
=> Blueberry light and dark theme

README.md
Adding a language or a theme? For languages, make sure to edit the `_list.json`, `_groups.json` files, and add the `language.json` file as well. For themes, make sure to add the `theme.css` file. It will not work if you don't follow these steps!
=> Removed unnecessary hyphen

README.md, static/index.html
Adding a language or a theme? For languages, make sure to edit the `_list.json`, `_groups.json` files, and add the `language.json` file as well. For themes, make sure to add the `theme.css` file. It will not work if you don't follow these steps!
=> Made sign in text more contextual

functions/index.js, src/js/test/pace-caret.js, src/js/test/test-logic.js, src/js/test/test-ui.js
Added #1369. This will work with both failed and successful tests that are repeated. However it will use the previous value with restarted quotes with repeat quotes in typing.
P.S It is a bit of a mess.
=> Added repeat caret pace

.github/ISSUE_TEMPLATE/bug_report.md
=> Made version more clear

src/js/commandline-lists.js, src/js/config.js, src/js/settings.js, src/js/test/pace-caret.js, src/js/test/test-logic.js, src/js/test/test-ui.js, static/index.html
This works just as before except you have to enable it in settings first. I wonder if you want to make the mode just take the wpm of the previous test regardless of whether it was repeated. The pace caret mode in the settings is now quite long but I wasn't sure what to do about that so I left it.
=> Added repeat mode to settings

src/js/account.js, src/js/chart-controller.js, src/sass/style.scss
Had a go at implementing #1409. There are still a few issues with this implementation, namely, you have to click exactly on the dot which can be difficult/frustrating. I thought about if the user could select the tooltip/dialogue box instead. Also, the selected test is given a class to show the user that it was the one they selected but this class in never removed which may become confusing.
=> Added click on account graph to scroll down to the test

src/js/settings.js
=> Expand settings group on quick navbar click

static/themes/_list.json, static/themes/fledgling.css
Added a theme for SA Fledgling
=> Add Fledgling theme

src/js/commandline.js
Fixed the bug found in #1453. Code could probably be made more concise, but it is more flexible so I left it.
=> Fixed search filter bug

static/languages/lithuanian_1k.json, static/languages/lithuanian_3k.json
changed word "spoetas" to "sportas".
=> Fixed a typo in lithuanian_1k/3k

static/quotes/english.json
Hey! I added 4 of my favorite quote from my favorite series, Steins;Gate, and I was wondering if you could add them to Monkeytype.
=> Add 4 Steins;Gate quotes

static/quotes/english.json
Adding a language or a theme? For languages, make sure to edit the `_list.json`, `_groups.json` files, and add the `language.json` file as well. For themes, make sure to add the `theme.css` file. It will not work if you don't follow these steps!
Please reference any issues and or PRs related to your pull request.
Resolves #
=> Added Martin Fowler quote

src/js/layouts.js
Thank you very much for your work! 
I believe it'd be great to add Arno’s Engram keyboard layout.
https://engram.dev/
https://github.com/binarybottle/engram
=> Add engram layout

.github/pull_request_template.md
Fixed links
Adding a language or a theme? For languages, make sure to edit the `_list.json`, `_groups.json` files, and add the `language.json` file as well. For themes, make sure to add the `theme.css` file. It will not work if you don't follow these steps!
Please reference any issues and or PRs related to your pull request.
Resolves #
=> Fixed link

src/js/account/result-filters.js, src/js/commandline-lists.js, src/js/config.js, src/js/input-controller.js, src/js/route-controller.js, src/js/settings.js, src/js/test/funbox.js, src/js/test/test-logic.js, src/js/test/test-stats.js, src/js/test/test-timer.js, src/js/test/test-ui.js, src/js/ui.js
Resolves #1479
The funbox state is now in config and is saved to DB, localStorage, etc.
=> Added funbox to config

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md
Updated comments throughout the templates and made some minor changes.
- [] If my PR is a new language or theme I modified the appropriate files to incorporate the language or theme
=> Updated templates

CONTRIBUTING.md
`Node v10` --> `Node < 14`
As Node 15 and 16 seem to break node-sass
=> Change node version in CONTRIBUTING.md

static/quotes/english.json
Looks like some white-space inconsistencies were automatically fixed by husky as well.
=> Fixed "The Tudors - Wolsey's Last Prayer" quote error

src/js/config.js, src/js/settings.js, src/js/simple-popups.js
Added the reset settings and unlink discord popups to simple-popup.js in order to make them styled. Checked reset settings and it works, but I wasn't sure how to test the unlink discord popup.
- [] I checked if my PR has any bugs or other issues that could reduce the stability of the project
Resolves #1468
=> Styled Reset and Unlink Discord Popups

static/quotes/english.json
Fixes grammar errors in Fahrenheit 451 quote.
=> fix english quote error

static/quotes/english.json
=> Added 25 new quotes

static/languages/lithuanian_3k.json
=> Fixed a typo in lithuanian_3k

static/security-policy.html
Simple typo fix in link on security page
=> Fix typo in link

static/quotes/french.json
Addition of eighty two new quotes for French with sources and length. The quotes are taken from a random selection of wikiquote articles.
<details>
<summary>Names of the random articles</summary>
- François Schuiten
- Gloria
- Alan Kay
- Vertu
- Évolution
- René Branquart
- François-Xavier Bellamy
- Maxime Rovère
- ZAD
- Camille Saint-Saëns
- Roschdy Zem
- Roy Lewis
- Portal
- Roger Lambelin
- Brian Aldiss
- Névrose
- Mordecai Roshwald
- La Porte des anges
- Divorce
- Jacques Ellul
- Michaël Buffat
- Robert Dautray
- Dictionnaire égoïste de la littérature française
- Mode
- Alan Moore
- Les Vitelloni
- Boubou Hama
- Félix Houphouët-Boigny
- Vol de nuit
- Publius Syrus
- Manning Johnson
- Lecteur
- Malcolm Muggeridge
- Jean Mermoz
- Les Maîtres sonneurs
- Philippe Leclerc de Hauteclocque
- …
=> 82 new French quotes

src/js/commandline-lists.js
Renamed the setting name in the command line from `toggleTimerBar` to `toggleTimerProgressBar`. I'm not sure if changing the id will cause any bugs, but I didn't see the id being referenced in any files.
=> Renamed command line setting timer-progress bar

src/js/layouts.js
Add new keymap for `boo` layout.
=> Add boo layout keymap

static/quotes/german.json
As I told on Discord I added all the quotes I could find myself and the ones that were already recommended by others. 
I don't know whether it is all good now and if there are still any typos I (and word :)) missed. But if there are some I will hopefully find them while typing and then I will change them in the list. 
If the format is in any way wrong please tell me, as I am not into coding yet and don't see this stuff myself.
=> New German quotes

static/quotes/dutch.json
=> Add more Dutch quotes

static/quotes/german.json
Got another 100 (I think) brand new quotes and hope that this time the code is not that bad shattered with mistakes...
For the fixes I am not sure, whether that are all the mistakes, but I hope so.
=> Another 100 new quotes and first typo fixing German

src/js/test/weak-spot.js
Comments for weakmode constants
=> Comments for weakmode constants

static/quotes/german.json
I fixed 2 typos in german.json:
- "Kerbs" to "Krebs"
- "–" to "-"
=> Fix typos in german.json

static/quotes/german.json
=> Fix a typo in german.json

static/quotes/german.json
I replaced all "–" with "-" in the quotes, because the big hyphen is not on the keyboard, or at least I can't find it.
=> Fix hyphens in german.json

static/index.html
- [] I have read the [`CODE_OF_CONDUCT.md`](https://github.com/Miodec/monkeytype/blob/master/CODE_OF_CONDUCT.md) and the [`CONTRIBUTING.md`](https://github.com/Miodec/monkeytype/blob/master/CONTRIBUTING.md)
- [] I checked if my PR has any bugs or other issues that could reduce the stability of the project
- [] I understand that the maintainer has the right to reject my contribution and it may not get accepted.
- [] If my PR is a new language or theme I modified the appropriate files to incorporate the language or theme   
Resolves #
=> Added the scroll up button that was missing in the About page

src/js/account.js, src/sass/style.scss, static/index.html
Added the possibility to sort by different categories (wpm, accuracy, consistency ...) when clicking on table headers at the bottom of the account page
Resolves #1602
=> Sort history on click

static/index.html
Moved footer icons inside anchor tags 
Resolves #
=> Moved footer icons into anchors

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
- Simple corrections of grammar and syntax errors and inconsistincies within the .md files.
=> Proofreading of .md Files

static/index.html
"Updates once every second" is inaccurate since live accuracy updates each character is typed. Therefore, I removed this sentence.
=> Remove "Updates once every second"

static/quotes/german.json
I just briefly updated some quotes that I found some mistakes in during typing them. I don't know, if that are all now, because I might have not typed all the 200 new ones yet, but I hope that's all for now.
=> German Quotes update

static/quotes/german.json
I found another 100 German Quotes and also fixed ones again some old typos. I may be getting to the 500 Quotes and then stop for the time being. As I ones more found all these Quotes in the internet I did not check them all by hand, but rather have, as usual, a piece of paper and a pen next to me while typing them and correct them all together at one time.
I hope the code is written the propper way and you guys don't have to do that much.
=> Another 100 Quotes again

static/quotes/icelandic.json
=> Added quotes for Icelandic

static/quotes/german.json
=> Update german quotes

static/quotes/english.json
=> Fixed Typo in quote ID:5065

static/languages/turkish.json, static/quotes/turkish.json
Added 15 new quotes.
Fixed a typo in the [static/languages/turkish.json](https://github.com/Yultax/monkeytype/commit/645a2d7f1d5ac253f3220f8cf8b527a1320e346b#diff-70d470fec6630995c2afb21dfab6ec0c2581e223bf09186d282b2f4fd1338601), the word "tabi" is even has a meaning too but it's not common used in Turkish language(not even in most common 1000 Turkish words) and probably it meant to be "tabii"(means "of course"). I'm not sure is this even a problem now but i wanted to fix this that.
=> Added some quotes and fixed a typo.

gulpfile.js, src/js/test/test-logic.js, src/js/test/weak-spot.js, src/js/test/wordset.js, static/funbox/_list.json
**NOTE:** I'm not sure whether this is a good idea. It seemed fun so I thought I'd share it, but it's totally up to you whether to do anything with it.
Generates random words using ngram distributions from the current language. The result is gibberish (I originally called it "gibberish" before I realized that was already the name of a funbox mode) but with similar patterns to real language.
=> Pseudolang funbox mode - gibberish, but more wordlike

backend/api/controllers/result.js, backend/dao/bot.js, src/js/challenge-controller.js, src/js/test/test-logic.js, static/challenges/_list.json
Challenge roles will now be auto-assigned by the bot (if applicable)
=> Auto-assigning challenge roles for discord (corey <-- real)

static/quotes/irish.json
=> Add Irish quotes

static/themes/_list.json, static/themes/godspeed.css
Adding the popular keyset color scheme Godspeed! Below are some screenshots:
Keyset:
Website screenshots:
=> feat: Add Godspeed theme

static/languages/_groups.json
delete the duplicate tmail from `_groups.json `
the issue is fixed
=> fix tmail duplicate

static/funbox/_list.json
Layoutfluid's code already works like this, but isn't described like this when you hover over it.
=> Modify layoutfluid description

static/quotes/italian.json
=> update italian json

static/themes/_list.json, static/themes/witch_girl.css
* adds [witch girl](https://twitter.com/mintlodica/status/1428394756510339074) as a theme
=> adds witch girl theme css and to theme list

static/quotes/thai.json
Add thai language quotes from united nation human right
Closes #
=> Add thai quotes

static/privacy-policy.html, static/security-policy.html, static/terms-of-service.html
- Made the text of the Terms of Service more internally consistent and corrected some typos.-
- Corrected typos on the Privacy Policy and Security Policy pages.
=> Cleaned up terms and policy pages

static/quotes/vietnamese.json
fixed typos in vietnamese.json
=> fixed typos

static/quotes/code_javascript.json
added 3 more javascript quotes
=> added more javascript quotes

static/quotes/german.json
Fixed capitalization of the first word of a sentence.
=> Fix capitalization

static/quotes/german.json
Added another 70 new quotes to put it to a total of 500 over all. Don't know whether or not it is all in the right format, but I hope so. Also fixed some typos as I was already on it.
=> New German Quotes+Typos

static/themes/_list.json, static/themes/soaring_skies.css
Added color theme based on the keycap set "KAM Soaring Skies"
Link to IC: https://geekhack.org/index.php?topic=112897.0
Screenshot:
=> added theme colors for KAM Soaring Skies

static/themes/_list.json, static/themes/chaos_theory.css
Uses a dark background and pink main color with many flipped words and letters, modifies the default caret with an image from the set and adds a logo to the theme picker.
[Link to GH post](https://geekhack.org/index.php?topic=114642.0)
=> Chaos Theory Theme

static/quotes/german.json
Spelling error, where"Frucht" means fruit, but it should be "Furcht", because it means fear.
Additional source: http://www.worte-projekt.de/herbert.html
=> Fix spelling error in german.json

src/js/tribe/tribe.js
got reported a few times (and ignored) in the discord so might have been intentional but it was triggering me 🙃
=> Fixed typo that was triggering me (settigns)

src/js/commandline-lists.js, src/js/config.js, src/js/input-controller.js, src/js/misc.js, src/js/popups/custom-text-popup.js, src/js/replay.js, src/js/settings.js, src/js/test/caps-warning.js, src/js/test/caret.js, src/js/test/layout-emulator.js, src/js/test/shift-tracker.js, src/js/test/test-logic.js, src/js/test/test-stats.js, src/js/test/test-ui.js, src/sass/style.scss, static/index.html
[Preview page](https://seerlite.github.io/monkeytype/issue/531-input-rewrite/)
Fixes #531
Fixes #36
Fixes #1297
Fixes #1403
Fixes #1902
Also I'm pretty sure this should be enough in order to start working on an input mode for "grouped character" languages.
As always feel free to request any changes you feel necessary and just ask if there's anything unclear/confusing.
=> Rewrite input system to use <input> content

src/js/input-controller.js
=> Update keymap when using layout emulator too

src/js/input-controller.js
Fixes a bunch of funky things happening when layout emulator is on
=> Fix layout emulator issues

static/languages/britishenglish.json
Noticed that mobilise wasn't in the britishenglish.json, so added it, noticed a couple of duplicates, so removed them.
=> remove duplicates, add mobilise

src/js/layouts.js
Added another keyboard layout, the Portuguese(Brazil, Nativo). Not widely used, but surely a great layout for people that write in Portuguese.
=> Add brasileiro nativo layout

src/js/input-controller.js
Reverts Miodec/monkeytype#2062
=> Revert "Incement accuracy even for trailingComposeChars"

static/quotes/german.json
Still trying to get rid of these nasty copy and pasting mistakes word did not find.
Probably doing some progress, as we ar woring on it as three persons, but don't know if it is over soon (especially if new ones come with the suggest quotes feature).
Sorry to still bother you with me at this one point not being willing to go through all the work.
Hope no errors in it, even thoug I would not know where they could come from.
Thanks for all the work of yours Mio
=> Another typo fix German

static/themes/_list.json, static/themes/comfy.css
Added Infinikey Comfy theme
Closes #
=> Added Infinikey Comfy theme

static/quotes/spanish.json
=> i added 8 new spanish quotes

gulpfile.js, src/js/test/test-logic.js, src/js/test/wikipedia.js, static/funbox/_list.json
Added wikipedia mode to funbox. In this mode you get random sentences from wikipedia articles, using wikipedia's [API](https://www.mediawiki.org/wiki/API:Main_page).
Closes #
#306
=> Added wikipedia mode to funbox

static/themes/_list.json, static/themes/tiramisu.css
Added  GMK Tiramisum
[Screenshots](https://imgur.com/a/5RrKwFJ)
=> Added GMK Tiramisu

src/js/test/test-logic.js
Adds a conditional in test-logic.js to change the label to 'cpm' when `alwaysShowCPM` is `true`.
Closes #2103
=> Added condition to change tooltip label to cpm if always show CPM is on

static/index.html
I noticed that there was a disparity between the website's list of contributors and github's list. As such, I have updated the data using the github api.
=> Updated contributors list with nov 2021 data

static/themes/modern_ink.css
Not close to any other monkeytype theme as far as I can see.
Here's a photo:
This is a theme based on GMK Modern Ink. It's color scheme is red, white, midnight blue and black. I didn't include any midnight blue in the theme because it barely shows in the keycap set itself.
=> Added GMK modern ink theme

src/js/test/test-logic.js
=> Allow numbers without punctuation mode

static/languages/estonian_10k.json, static/languages/estonian_1k.json
=> Fix Estonian 1k/10k resetting to English

static/index.html
Fixed image issue where mtsocial.png wouldn't show on Discord or Twitter.
=> Fix Image Issue

static/themes/_list.json, static/themes/moonlight.css
Screenshot:
inspired by GMK MOONLIGHT 
edited the colors and tweak the top icons just a bit...
=> Adding Moonlight theme

src/js/layouts.js
=> added octa8 layout

src/js/config.js, src/js/input-controller.js, src/js/test/funbox.js, src/js/test/test-logic.js, src/js/test/test-stats.js, src/js/test/test-ui.js, src/sass/test.scss, static/funbox/_list.json
- arrow funbox added to list.json
- WSAD and Arrowkey input
- random arrows generator
- arrow icons in test
- non repeating arrows
=> feat: initial arrow funbox

static/index.html
Added noscript so the user will be warned if JS is not enabled.
=> Add noscript

.gitignore, CONTRIBUTING.md
* Fixes a typo in `CONTRIBUTING.md`. (Missing whitespace.)
* Adds `.gitkeep` under `backend/credentials` so users don't have to create the directory themselves.
The `.gitkeep` change is up for debate, since that's not an official Git thing. Many projects add a `.gitkeep` file to push directories required for development, though. In my opinion, it'd be nice since the directory is required anyway. Let me know if you want me to remove that commit, though. (freeCodeCamp article on the topic: https://www.freecodecamp.org/news/what-is-gitkeep/)
=> chores: fix typo and push backend/credentials directory

src/js/input-controller.js
Interpret an ellipsis (…) as 3 periods (...).
Just let me know if there's anything wrong with this solution.
Closes https://github.com/Miodec/monkeytype/issues/2218
=> feat: interpret ellipsis as 3 periods

src/js/test/test-logic.js
Uses British English replacement as the final word creation step before pushing to wordlist.
Closes #2213
=> Allow British English to replace words in weakspot funbox

CONTRIBUTING.md
Removes that the `credentials` directory must be created, as this is no longer the case.
Just noticed that I forgot to remove that. ^-^'
=> chore: remove create directory from contributing guide

static/quotes/filipino.json
- Adds several quotes for the Filipino language, mostly from leftist literature that I have lying around
- Changed the source for the first quote to be "José Rizal (disputed)" since [he didn't write that](https://newsinfo.inquirer.net/45479/did-young-rizal-really-write-poem-for-children)
- Corrected some lengths for previous quotes
=> Adding Filipino quotes

static/quotes/german.json
Hey Mio,
sorry to bother you with this shit again, but in my hollidays I now got the time to look through the entire code and tried to find all the mistakes still missing. As I am actually not that good with grammar ( for a native atleast) I don't know for sure whether or not I got them all now.
But I hope I got them all now, or at least there are like one or two minor ones left and I hope the code is still working.
Happy new year if you got to see it then otherwise get good into the new year.
Thanks for all the work you do with the website.
=> German Quotes fix

static/index.html
`index.html` was trying to get the `css/media-queries.css` stylesheet, which does not exist. I removed the line from `index.html` that was requesting it.
=> remove css/media-queries.css

src/js/test/test-ui.js
I increased the default screenshot padding in test-ui.js. This was done to patch the issue with the screenshot content exceeding the width of the image. I also made the html2canvas element's position get calculated by two padding variables.
Closes #2054
(This is my first pull request with code to a public repository ever, so please tell me if I need to do anything different) :)
=> Implemented screenshot fix

src/js/layouts.js
Adds Spanish QWERTY and Dvorak keyboard layouts.
=> Add Spanish Dvorak and Spanish QWERTY layouts

src/js/commandline-lists.js, src/js/sound.js
This PR previews click sounds on mouse-hover / arrow-up / arrow-down / tab / shift-tab of the sound options in the command line.
=> Preview click sounds in the command line

static/quotes/english.json
Added new quotes from Naruto Shippuden. Quotes are of Madara Uchiha from the 4th Great Ninja War.
=> Added  new quotes from Naruto Shippuden

CONTRIBUTING.md, THEMES.md, Themes.md
I felt as there wasn't much documentation for people who are completely new to coding but they wanted to add themes. So I created THEMES.md which explains to new coders how to add themes. I feel like some more stuff could be added so let me know if there is anything I should change or add. I also offered a little bit of information for forking repos and whatnot.
=> Add More Theme Documentation

src/js/layouts.js
Remove outdated and little-used APTx
Update APT to current version in author's repo
Add row-stagger angle-mod variant
=> Fix APT layouts

static/quotes/english.json
Fixed typo for quote id 5701 (gave -> have)
=> Fixed Typo

static/themes/_list.json, static/themes/fruit_chew.css, static/themes/fruitchew.css
Added in the ePBT Fruit Chew Theme. This is based on @adii-n's pr (#1857). @batsoup804 created the new updated theme version and he mentioned it in that pr. (He provides the screenshots)
=> ePBT Fruit Chew Theme (Updated)

static/funbox/space_balls.css
"A long, long time ago in a galaxy far, far away..." and the following text is always in yellow, with a space galaxy background. You can find them all here.
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.inafarawaygalaxy.com%2F2013%2F08%2Fthe-text-of-every-star-wars-crawl.html&psig=AOvVaw0l3URlf_Ur6huJS0SwfNo8&ust=1642615476042000&source=images&cd=vfe&ved=0CAkQjhxqFwoTCPiFqdLxu_UCFQAAAAAdAAAAABAO
I also thought there was nothing wrong with the background gif so I took the comment off it.
Changes made include the text color in the spaceballs funbox mode and the gif background un-commented.
=> Updated text color to match star wars intro

static/sw.js, static/themes/_list.json, static/themes/trance.css
=> Add Trance Theme

static/quotes/english.json
=> add new quotes

CONTRIBUTING.md
Fixed an unclosed bracket in `CONTRIBUTING.md` and updated the line for Grammar enhancement.
=> Grammar Enhancement: Fixed a Typo + Minor Updates

src/js/layouts.js
Adding latam layout
Just added new item to layouts array.
=> Adding latam layout

backend/api/routes/index.js, backend/server.js
Refactored the way API routes are added to the express app.
=> Refactor routing configuration

src/js/account-controller.js
After enabling google authentication, a notification pops up containing a typo. This PR fixes that.
=> fix(addGoogleAuth): fix a typo

static/funbox/_list.json, static/themes/_list.json, static/themes/fleuriste.css
here are some screenshots of Fleuriste!
This PR adds the Fleuriste theme. It features a beige, dark green and plum colorway based off flowers and vases. The group buy is live right now and you can check it out [here.](https://kono.store/collections/keycap-sets/products/gmk-fleuriste?)
=> Added GMK Fleuriste theme

backend/api/controllers/quotes.js, backend/api/routes/quotes.js, backend/dao/report.js, backend/middlewares/apiUtils.js, gulpfile.js, src/js/input-controller.js, src/js/popups/quote-report-popup.js, src/js/popups/quote-search-popup.js, src/js/popups/rate-quote-popup.js, src/js/test/result.js, src/js/test/test-logic.js, src/js/test/test-ui.js, src/sass/inputs.scss, src/sass/popups.scss, src/sass/test.scss, static/index.html
I have designed the reporting system to be extensible/generic. Such that if we want to support reporting for another feature on the site, we can easily set that up.
closes: #1158
=> Add quote reporting feature

static/languages/britishenglish.json
"civilized" is in 4 quotes
"civilization" is in 24 quotes
Add British English spellings of civilized/civilised and civilization/civilisation.
=> Add "civilise" to British English

backend/api/controllers/new-quotes.js, backend/api/controllers/quote-ratings.js, backend/api/routes/quotes.js, backend/middlewares/api-utils.js, src/js/popups/quote-rate-popup.js
- Added middleware to check configuration for routes.
- Adopted `asyncHandlerWrapper` across the quote endpoints.
- Default to sending a 204 status if headers are not sent and no data is returned by a handler.
=> Refactor Quote Endpoints

backend/constants/base-configuration.js, backend/dao/configuration.js, backend/handlers/logger.js, backend/init/db.js, backend/init/mongodb.js, backend/server.js, backend/worker.js
- Added additional logic to correctly handle arrays in the config.
- Added new Db client
=> Update Configuration to handle arrays/ Add new db client

static/index.html
I added a comma to statc/index.html line number 1925 to make the sentence look more correct.
Closes #
=> Added a comma in the "Discord integration paragraph"

src/sass/inputs.scss, static/index.html
Added the cursor styles for the hover and active states for the range inputs thumb like so:
```
&:hover{
cursor:grab;
}
&:active{
cursor:grabbing;
}
```
=> Added grabbing to the range input

CONTRIBUTING.md
Link to "THEMES.md" in "CONTRIBUTING.md" wasn't right so  I changed it
=> fix link in CONTRIBUTING.md

backend/api/controllers/config.js, backend/api/controllers/leaderboards.js, backend/api/controllers/new-quotes.js, backend/api/controllers/preset.js, backend/api/controllers/quote-ratings.js, backend/api/controllers/quotes.js, backend/api/controllers/result.js, backend/api/controllers/user.js, backend/api/routes/config.js, backend/api/routes/leaderboards.js, backend/api/routes/preset.js, backend/api/routes/quotes.js, backend/api/routes/result.js, backend/api/routes/user.js, backend/middlewares/api-utils.js, backend/middlewares/auth.js, backend/middlewares/context.js, backend/server.js
- Added request schema validation for leaderboards/preset endpoints.
- Changed `req.context` -> `req.ctx`
- Moved `decodedToken` into `req.ctx`
- Re-wrote authentication middleware for future extensibility/enabling public routes.
- Sorry Mio D;
Related to: #2375
=> Endpoint schemas/Improved Auth Middleware

src/js/popups/quote-search-popup.js
=> Fix report popup focusing on test ui

backend/api/controllers/result.js, backend/api/routes/result.js, backend/api/schemas/result-schema.js
- Added endpoint request validation to the result endpoints.
Related to: #2375
=> Add results schema validation

static/themes/_list.json, static/themes/snes.css
Added a SNES theme. Gradient menu buttons, switching to grey when typing.
Home:
Default settings:
Colorful mode:
=> added snes theme

.eslintrc.json, .github/pr-check.yml, backend/api/controllers/leaderboards.js, backend/api/controllers/preset.js, backend/api/controllers/result.js, backend/api/controllers/user.js, backend/dao/bot.js, backend/dao/config.js, backend/dao/leaderboards.js, backend/dao/psa.js, backend/dao/quote-ratings.js, backend/handlers/error.js, backend/jobs/update-leaderboards.js, backend/worker.js, package-lock.json, package.json
- Added a lint/style check for pull requests.
=> Setup PR check action

bin/install.sh
=> Fix install command

frontend/static/themes/_list.json, frontend/static/themes/passion_fruit.css
Added a theme meant to resemble a passion fruit.
=> Passion Fruit Theme

THEMES.md, frontend/static/themes/_list.json
Just fixed a typo and updated the paths in THEMES.md. If there is anything else I missed that I should fix let me know.
=> Fixed a typo and update paths in THEMES.md

frontend/src/js/test/layouts.js
whorfmax and whorfmax_ortho layouts are added
=> whorfmax and whorfmax_ortho layouts are added

frontend/.eslintignore, frontend/gulpfile.js, frontend/package-lock.json, frontend/package.json, frontend/src/js/axios-instance.ts, frontend/src/js/elements/commandline-lists.js, frontend/src/js/modules.d.ts, frontend/src/js/pages/settings.js, frontend/tsconfig.json, package-lock.json, package.json, ts.eslintrc.json
=> Compile both JS and TS

frontend/src/js/misc.js, frontend/src/js/ui.ts
Even though I have converted this file to typescript. I don't know of any instances where it is being used or imported in the project.
=> Frontend Typescript: Convert ui.js to typescript

frontend/package-lock.json, frontend/package.json, frontend/webpack-production.config.js, frontend/webpack.config.js
=> Webpack fix

.github/workflows/stale-pr.yml, bin/install.sh, frontend/gulpfile.js, frontend/package-lock.json, frontend/package.json, frontend/webpack-production.config.js, package-lock.json, package.json
- Moved some root dependencies into frontend dependencies.
- Added a GitHub action to mark stale PRs.
=> Move dependencies

frontend/static/quotes/code_python.json
Bubble sort and Linear Search code from geeksforgeeks.
=> New Quote: Python

frontend/static/quotes/english.json
=> Remove quote

backend/api/controllers/preset.js, backend/api/controllers/result.js, backend/api/routes/configs.js, backend/api/routes/presets.js, backend/api/routes/results.js, backend/api/routes/users.js, frontend/src/scripts/ape/endpoints/configs.ts, frontend/src/scripts/ape/endpoints/leaderboards.ts, frontend/src/scripts/ape/endpoints/presets.ts, frontend/src/scripts/ape/endpoints/psas.ts, frontend/src/scripts/ape/endpoints/quotes.ts, frontend/src/scripts/ape/endpoints/results.ts, frontend/src/scripts/ape/endpoints/users.ts, frontend/src/scripts/ape/index.ts, frontend/src/scripts/ape/types/ape.d.ts
- Changed the client's api, i.e. usage: `ape.users.create()` instead of `ape.createUser()`
- Updated routes to follow REST conventions
- Added all API endpoints
- Next PR will be migrating from using the axios instance to the ape client
=> Complete Ape Client

frontend/src/scripts/ape/endpoints/presets.ts, frontend/src/scripts/ape/endpoints/users.ts, frontend/src/scripts/ape/index.ts, frontend/src/scripts/ape/types/ape.d.ts, frontend/src/scripts/config.js, frontend/src/scripts/db.js, frontend/src/scripts/elements/psa.ts, frontend/src/scripts/popups/edit-preset-popup.ts, frontend/src/scripts/types/types.d.ts, frontend/tsconfig.json, package.json
- Migrated some code to use ape
=> Frontend ape client migration p1

frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/misc.ts, frontend/src/scripts/test/british-english.ts, frontend/src/scripts/test/funbox.js, frontend/src/scripts/test/test-logic.js
Capitalizes the first letter of each word in the string instead of just the first letter
=> capitalize the first letter of each word in the string

backend/api/routes/configs.js, backend/api/routes/users.js, backend/middlewares/rate-limit.ts, backend/package-lock.json, backend/package.json, backend/types/types.d.ts
- Made rate limited requests message appear
=> Fix rate limit

frontend/src/scripts/misc.ts, frontend/src/scripts/ready.ts
Adds the only root file that's still js, ready.ts.
Closes #
=> Add root files

frontend/static/quotes/english.json
=> Fixed grammar in quote 5698

frontend/src/scripts/controllers/account-controller.js, frontend/src/scripts/db.ts, frontend/src/scripts/popups/result-tags-popup.ts, frontend/src/scripts/popups/simple-popups.ts, frontend/src/scripts/test/test-logic.js
- Mirage results endpoints to use Ape
=> Ape migration p4

backend/api/routes/users.js, frontend/src/scripts/ape/endpoints/users.ts, frontend/src/scripts/ape/types/ape.d.ts, frontend/src/scripts/controllers/account-controller.js, frontend/src/scripts/controllers/verification-controller.ts, frontend/src/scripts/db.ts, frontend/src/scripts/popups/edit-tags-popup.ts, frontend/src/scripts/popups/simple-popups.ts
- Migrated some users endpoints to use the ape client
=> Migrate some users endpoints to Ape

frontend/static/privacy-policy.html
Data is now stored in MongoDB, so I updated the privacy policy to reflect this change. 
Also updated the "last updated" date.
=> Update privacy-policy to reflect mongodb

README.md
=> Add TypeScript to the README

frontend/src/scripts/test/test-timer.js
=> Warn users on edge about disabling efficiency mode

frontend/static/themes/_list.json, frontend/static/themes/blue_dolphin.css
Adds the Blue Dolphin theme based on the [VSCode Blue Dolphin theme](https://marketplace.visualstudio.com/items?itemName=21BlueDolphins.bluedolphin)
=> Add Blue Dolphin theme

.eslintignore, package-lock.json, package.json
=> remove run-script-os and change the script back

frontend/src/scripts/index.ts, frontend/src/scripts/misc.ts, frontend/src/scripts/popups/simple-popups.ts, frontend/src/scripts/types/types.d.ts, package.json
- Create interfaces for `String` prototype and the `global` object
- Fix function signature of `objectToQueryString`
Part of the little fixes in #2431.
=> Remove some `@ts-ignores` in frontend scripts

backend/api/controllers/user.js, backend/handlers/captcha.js
Fix some errors due to mutated variables.
Closes #
=> Fix some backend errors

backend/api/controllers/config.ts, backend/api/controllers/leaderboards.ts, backend/api/controllers/preset.ts, backend/api/controllers/psa.ts, backend/api/controllers/quotes.ts, backend/dao/report.js, backend/middlewares/api-utils.ts
- Migrated some of the controller files
- Made response optional for AsyncHandler
- Needs @Miodec 's notice since quote report controls are being read from the server config.
- Related to #2430
=> Migrate some controller files

backend/api/schemas/config-schema.ts, frontend/src/scripts/config.ts, frontend/src/scripts/controllers/account-controller.js, frontend/src/scripts/controllers/input-controller.ts, frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/elements/keymap.ts, frontend/src/scripts/test/caps-warning.ts, frontend/src/scripts/test/layout-emulator.js, frontend/src/scripts/test/shift-tracker.js, frontend/src/scripts/types/types.d.ts, frontend/static/index.html
Adds a dynamic keymap legend style so that when using CapsLock or Shift, the casing changes accordingly.
The only minor issue with this now should be a very slight lag when changing shift or caps state and typing. Very minimal though and is hard to notice even on high refresh rates.
=> Add dynamic keymap legend style

frontend/src/scripts/test/test-config.ts
fixes mio's prod breaking change
Closes #
=> GOOD JOB MIO

frontend/src/scripts/ape/types/ape.d.ts, frontend/src/scripts/misc.ts, frontend/src/scripts/test/funbox.ts, frontend/src/scripts/test/lazy-mode.ts, frontend/src/scripts/test/poetry.ts, frontend/src/scripts/test/test-logic.ts, frontend/src/scripts/test/test-words.ts, frontend/src/scripts/types/types.d.ts
=> Add test-logic.ts

backend/api/controllers/ape-keys.ts, backend/api/routes/ape-keys.ts, backend/api/routes/index.ts, backend/constants/base-configuration.ts, backend/middlewares/auth.ts, backend/middlewares/rate-limit.ts, backend/package-lock.json, backend/package.json, backend/types/types.d.ts
- Added ApeKeys routing and configuration
- Upgraded firebase-admin package
=> Add ape keys routing and configuration

frontend/static/index.html
* Improves "Randomize Theme" setting coherence between description and options (option is called _favourite_ and not _fav_)
=> Simple coherence fix in theme randomizing settings

backend/middlewares/error.ts
=> Fix errors

frontend/src/scripts/ape/endpoints/ape-keys.ts, frontend/src/scripts/ape/endpoints/index.ts, frontend/src/scripts/ape/index.ts, frontend/src/scripts/ape/types/ape.d.ts
- Registers the ape keys API to the frontend client.
=> Add ape keys API to ape client

backend/api/controllers/ape-keys.ts, backend/constants/base-configuration.ts, backend/middlewares/auth.ts, backend/types/types.d.ts
- Implements ape key authentication
- Adds configuration points for Ape key generation
=> Add ape key authentication

frontend/static/quotes/portuguese.json
Adding a quote from the book The Power of Habit, by Charles Duhigg in portuguese.
=> add quote in portuguese.json

frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/elements/commandline.ts, frontend/src/scripts/popups/simple-popups.ts
=> remove evals

backend/swagger.json
=> Add summaries for api

frontend/static/languages/english_25k.json
Commented out some words for easier review and reinstatement. 
Capitalized some words that should be capitalized. 
Removed or commented on some abbreviations.
Added comments to words removed and some not removed. If there is a criteria for inclusion/exclusion, words might be found more quickly. (i.e. remove all demonyms)
=> Remove potentially offensive words, capitalization

backend/api/controllers/user.ts
- Somehow this got overseen lol
=> Remove artifact

backend/package-lock.json, backend/package.json
- Removing mongo types since mongodb provides its own types.
=> Remove mongo types

backend/api/controllers/ape-keys.ts, backend/dao/ape-keys.ts, backend/middlewares/auth.ts, backend/types/types.d.ts
=> Add last used on logic

frontend/src/scripts/ape/endpoints/ape-keys.ts, frontend/src/scripts/ape/types/ape.d.ts, frontend/src/scripts/db.ts, frontend/src/scripts/pages/settings.ts, frontend/src/scripts/popups/ape-keys-popup.ts, frontend/src/scripts/popups/simple-popups.ts, frontend/src/scripts/types/types.d.ts, frontend/src/styles/inputs.scss, frontend/src/styles/popups.scss, frontend/static/index.html
Added popup for generating, enabling/disabling, renaming and deleting ape keys
=> Added Ape Keys Popup

frontend/src/scripts/popups/custom-text-popup.ts, frontend/src/scripts/popups/saved-texts-popup.ts, frontend/src/scripts/popups/simple-popups.ts, frontend/src/scripts/test/custom-text.ts, frontend/src/styles/popups.scss, frontend/static/index.html
=> Add Custom Text Storage

backend/api/controllers/ape-keys.ts, backend/api/controllers/quotes.ts, backend/api/controllers/user.ts, backend/constants/monkey-status-codes.ts, backend/dao/ape-keys.ts, backend/dao/result.js, backend/dao/user.js, backend/middlewares/api-utils.ts, backend/middlewares/auth.ts, backend/middlewares/error.ts
- Addresses incorrect 500 status codes when a bad request is sent.
- Some error status codes house-keeping.
=> Add error handling for bad requests

backend/api/controllers/ape-keys.ts, backend/api/controllers/user.ts, backend/api/routes/ape-keys.ts, backend/dao/ape-keys.ts, backend/dao/user.js, backend/middlewares/auth.ts, backend/types/types.d.ts
- Moved ape keys to separate collection
=> Update ape keys data model

backend/api/controllers/ape-keys.ts, backend/constants/monkey-status-codes.ts, backend/dao/ape-keys.ts, backend/documentation/public-swagger.json, backend/middlewares/auth.ts
- Removed the uid field from the generated ApeKey
- Added a note on rate limit rates
=> Final touches/tuning for ApeKeys

backend/api/routes/ape-keys.ts, backend/types/types.d.ts, frontend/src/scripts/popups/ape-keys-popup.ts
- Adds ape key controls for ape key management
=> Add user permissions for ape keys

frontend/src/scripts/popups/quote-search-popup.ts, frontend/src/scripts/utils/strings.ts
- Fixes quote search issue in safari
=> Quote search safari fix

frontend/static/languages/code_csharp.json
=> Fix `even` to `event` in code csharp

backend/middlewares/error.ts
- Includes errorId for unexpected errors.
=> Include error id

CONTRIBUTING.md, LANGUAGES.md, README.md, SECURITY.md, THEMES.md
Edits for spelling, grammar, and general clarity in repository documentation files.
=> Documentation edits

frontend/static/quotes/english.json
Song lyric from Avicii - The Nights
=> Added Quote - 5917 -> Avicii - The Nights

frontend/static/index.html
- Fixes ApeKeys management modal being visible to unauthorized users.
- Closes #2687
=> Fix ApeKeys management for unauthed users

frontend/static/quotes/english.json
=> modify quotes

frontend/src/scripts/controllers/quotes-controller.ts, frontend/src/scripts/popups/quote-report-popup.ts, frontend/src/scripts/popups/quote-search-popup.ts, frontend/src/scripts/test/test-logic.ts, frontend/src/scripts/test/test-words.ts, frontend/src/scripts/utils/misc.ts
=> Add logic to prevent repeated random quotes

frontend/static/quotes/english.json
- What do I do?
- Sesame seeds
=> Add silicon valley quotes

frontend/src/scripts/test/focus.ts
Corresponds to [this issue](https://github.com/Miodec/monkeytype/issues/2702)
And for [this reason](https://streamable.com/k7x2s4)
=> Unfocus when mouse moves >5px

frontend/src/scripts/ape/endpoints/results.ts
=> Add client version header to save results

frontend/webpack/config.prod.js
=> Change client version formatting

frontend/src/scripts/controllers/quotes-controller.ts
- Fixes a minor bug where users who had a variation of a language (english1k, etc) could not see quotes.
=> Fix quotes controller

backend/api/routes/leaderboards.ts
- Removes generic validation message from leaderboards endpoints
=> Remove generic validation message

frontend/package-lock.json, frontend/package.json
- Removes gulp sass related plugins
=> Remove unused dependencies

.github/workflows/pr-check.yml
- Updates action to run on PR to dev branch
=> Include dev branch in CI

CONTRIBUTING.md, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/webpack/config.base.js, frontend/webpack/config.dev.js, package.json
- Uses Webpack dev server with live reloading
https://user-images.githubusercontent.com/58147810/159149022-bb224da5-87c7-4e33-adb2-4c1c22852ed4.mov
=> Enable live reloading

backend/api/routes/index.ts, backend/server.ts, backend/utils/misc.ts, backend/utils/prometheus.ts, backend/version.ts
- Adds a metric for server version
=> Server version

frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/elements/commandline.ts, frontend/src/scripts/types/types.d.ts, frontend/static/index.html
- Adds a command to open the quote search popup
=> Add quote search command

backend/api/schemas/config-schema.ts, frontend/src/scripts/config.ts, frontend/src/scripts/constants/default-config.ts, frontend/src/scripts/db.ts, frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/elements/last-10-average.ts, frontend/src/scripts/elements/modes-notice.ts, frontend/src/scripts/pages/settings.ts, frontend/src/scripts/test/pace-caret.ts, frontend/src/scripts/test/test-logic.ts, frontend/src/scripts/types/types.d.ts, frontend/static/index.html
=> Add Show Average Accuracy and Make Show Average Speed Show CPM

backend/api/controllers/result.ts, backend/api/controllers/user.ts, backend/constants/base-configuration.ts, backend/example.env, backend/init/redis.ts, backend/jobs/update-leaderboards.ts, backend/package-lock.json, backend/package.json, backend/server.ts, backend/tasks/george.ts, backend/types/types.d.ts
- Adds a Redis client
- Adds a bull queue for george tasks
- Adds a configuration to control whether or not we add tasks into bull queue
=> Add Redis client and george task queue

frontend/static/quotes/english.json
Just some unusual whitespace someone found, not really much to say. 
https://discord.com/channels/713194177403420752/713195115275091969/956620736204791878
=> Removed unusual whitespace from quote 5905

backend/init/redis.ts, backend/server.ts, backend/tasks/george.ts, backend/utils/misc.ts
=> Optional redis

frontend/src/scripts/test/english-punctuation.ts, frontend/src/scripts/test/test-logic.ts, frontend/static/languages/english_punctuation.json
Closes #2753 
New punctuation functionality as described in issue #2753. Mostly just copied things from BritishEnglish function, because I myself am not that experienced so I'm hoping for some feedback.
All in All I just created a json file with the possible pairs, added a new test file just like the BritishEnglish one, added a check function to check if the word is present in the list so it can be changed.
Keep in mind I freestyled it all so I'm not expecting this to actually work
=> New punctuation functionality allowing words to end with -n't

backend/init/configuration.ts, backend/init/redis.ts, backend/jobs/update-leaderboards.ts, backend/middlewares/context.ts, backend/server.ts, backend/tasks/george.ts
- Re-writes configuration client and redis client to not use class syntax.
=> Re-write redis client and configuration client from class syntax

frontend/webpack/config.base.js
- Refactors multiple usage of html webpack plugin
=> Refactor plugin code

frontend/static/languages/english_5k.json
=> Fix typo: English 5k British "offence" to American "offense"

frontend/static/quotes/portuguese.json
Small correction, there was a period where it was supposed to be a comma.
Closes #
=> changed: period->comma

frontend/static/themes/_list.json, frontend/static/themes/mexican.css
=> Add Theme - Mexican

README.md
=> Remove JavaScript and CSS from the README

frontend/src/scripts/test/wikipedia.ts
=> Reformatting wikipedia.ts

backend/api/controllers/user.ts, backend/api/routes/users.ts, backend/dao/user.ts, backend/types/types.d.ts, backend/utils/validation.ts, frontend/src/scripts/controllers/account-controller.ts, frontend/src/scripts/index.ts, frontend/src/scripts/observables/google-sign-up-event.ts, frontend/src/scripts/pages/login.ts, frontend/src/scripts/popups/google-sign-up-popup.ts, frontend/src/styles/popups.scss, frontend/static/html/popups.html
Username is no longer optional.
Firebase user will be deleted if user tried to login and no document was found in the database.
Added a new popup when user uses google sign up and the account is new.
=> Made username non optional

backend/api/controllers/ape-key.ts, backend/api/controllers/quote.ts, backend/dao/leaderboards.ts, backend/dao/new-quotes.ts, backend/dao/user.ts, backend/init/configuration.ts, backend/init/db.ts, backend/types/types.d.ts, backend/utils/logger.ts
Fix collection types so that it removes some `any`s and does objectid generation in the code.
Closes #
=> Fix Collection Types

.eslintrc.json, backend/api/schemas/config-schema.ts, frontend/src/scripts/config.ts, frontend/src/scripts/constants/default-config.ts, frontend/src/scripts/controllers/input-controller.ts, frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/pages/settings.ts, frontend/src/scripts/test/caret.ts, frontend/src/scripts/test/test-logic.ts, frontend/src/scripts/test/test-ui.ts, frontend/src/scripts/types/types.d.ts, frontend/src/styles/test.scss, frontend/static/challenges/_list.json, frontend/static/html/pages/settings.html
Mode which shows one line and scrolls horizontally
Closes #2858
=> Added tape mode

frontend/package-lock.json, frontend/package.json, frontend/src/scripts/controllers/account-controller.ts, frontend/src/scripts/elements/commandline-lists.ts, frontend/src/scripts/popups/share-test-settings-popup.ts, frontend/src/scripts/utils/url-handler.ts, frontend/src/styles/popups.scss, frontend/static/html/popups.html
=> Added popup to share test settings through url

frontend/static/html/pages/settings.html
In settings: changed 'conset' to 'consent'
=> Fix a typo

frontend/static/quotes/code_java.json
changes 'WIndows' to 'Windows'
=> fixed typo in Windows word

frontend/static/quotes/english.json
I added a quote from James Baldwin's book, Giovanni's Room!
=> Added a quote by James Baldwin!

frontend/static/quotes/english.json
>It adds a new quote to the English quotes JSON file
=> Add quote by Bradely Whiteford

.npmrc
=> Enforce save exact

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, CONTRIBUTING.md, LANGUAGES.md, QUOTES.md, README.md, THEMES.md, frontend/static/html/pages/about.html
Absolute links -> Relative Links
=> Update some document links

backend/api/controllers/ape-key.ts, backend/dao/ape-keys.ts, backend/middlewares/auth.ts
=> Ape keys dal

backend/api/controllers/result.ts, backend/api/controllers/user.ts, backend/dao/bot.ts, backend/jobs/update-leaderboards.ts
=> BotDAO -> BotDAL

backend/api/controllers/quote.ts, backend/dao/quote-ratings.ts
=> DAO -> DAL

backend/dal/ape-keys.ts, backend/dal/bot.ts, backend/dal/config.ts, backend/dal/leaderboards.ts, backend/dal/new-quotes.ts, backend/dal/preset.ts, backend/dal/psa.ts, backend/dal/public-stats.ts, backend/dal/quote-ratings.ts, backend/dal/report.ts, backend/dal/result.ts, backend/dal/user.ts, backend/init/configuration.ts, backend/init/db.ts, backend/jobs/delete-old-logs.ts, backend/middlewares/error.ts, backend/server.ts, backend/utils/logger.ts
=> Remove class syntax from db client

backend/api/controllers/result.ts, backend/api/controllers/user.ts, backend/jobs/update-leaderboards.ts, backend/server.ts, backend/tasks/george.ts, backend/utils/misc.ts
=> Remove class syntax from george

backend/server.ts, backend/tasks/george.ts
=> Remove await

.eslintrc.json, backend/package-lock.json, backend/package.json, backend/setup-tests.ts, backend/src/tasks/george.ts
run tests against real redis or mock
=> Testing - mock setup for redis

.github/workflows/pr-check.yml, backend/jest.config.ts, backend/package.json, backend/src/app.ts, package.json
=> Add test step in pr-check action

frontend/static/themes/moonlight.css
no big deal, just made the bg darker
**before:**
---
**after:**
=> make the bg color a bit darker* 🕳

CONTRIBUTING.md
you've changed install-windows, but I guess forgot to change install-all, because on my Mac, install:all doesn't work, and install-all works fine
=> install-all fix in contributing

backend/src/dal/user.ts, backend/src/types/types.d.ts
- Adds logic to remove needsToUpdateName field for users that update their name
- Related to issue #2954
=> Add backend logic to handle duplicate names

frontend/static/themes/_list.json, frontend/static/themes/peach_blossom.css
New Theme: Peach blossom
color palette
What it looks like
=> Add new Theme "Peach blossom"

frontend/src/ts/elements/commandline-lists.ts
Now, when user select "Presets..." in command line, he can also create preset, not only choose
=> Create preset addition in presets in command line

backend/__tests__/dal/user.spec.ts, backend/jest.config.ts, backend/src/dal/user.ts, backend/src/utils/validation.ts
=> Add more tests

frontend/static/quotes/english.json
Added quotes from Xavier: Renegade Angel and The Master and Margarita
Added 3 quotes for the english quote library.
=> Added english quotes

CODE_OF_CONDUCT.md
the new version can be found in https://www.contributor-covenant.org/version/2/1/code_of_conduct/
Update conduct to the new version 
note: it's okay if you don't want to update ur Code of Conduct.
=> Update CODE_OF_CONDUCT.md to new verison

CONTRIBUTING_BASIC.md
Small linguistic changes to documentation for contributing to the repo.
Edited a few sentences in `"CONTRIBUTING_BASIC.md"` to help clarify intent.
=> Small edits to Basic Contributing documentation

backend/__tests__/api/controllers/user.spec.ts, backend/jest.config.ts, backend/src/api/controllers/user.ts, backend/src/middlewares/auth.ts
=> Add user creation flow test

frontend/static/themes/_list.json, frontend/static/themes/dino.css
Dinosaur theme! A light theme, (that isn't TOO light) that is themed after the best animal the... DINOSAUR!!! It was made to match the colors of my profile pick, and I also made a dark mode version but it doesn't look that good. It is quite different from the other themes, and is pretty unique.
Adds a new theme, dinosaur theme!! BG is light, while other colors are a nice smooth shade of green.
URL for if you want to try it out yourself.
[Dinosaur theme](https://monkeytype.com?customTheme=WyIjZmZmZmZmIiwiIzQwZDY3MiIsIiM0MGQ2NzIiLCIjNjQ2NjY5IiwiIzQ3ZTE3OSIsIiMyNzgyNDUiLCIjMDM3MzI5IiwiIzAzNTcxZiIsIiMwMzczMjkiLCIjMDM1NzFmIl0=)
=> Dinosaur Theme

frontend/static/languages/english_25k.json
Removes the misspelling of "awesome" (spelt like "awsome") from `english_25k` and `english_450k`. "awesome" exists elsewhere in 25k and 450k.
=> removed mispelled word

backend/src/dal/result.ts
- Fixes discrepancy between public API documentation data and actual data (unexpected uid field)
=> Remove uid from last result

backend/__tests__/utils/daily-leaderboards.spec.ts, backend/__tests__/utils/misc.spec.ts, backend/package-lock.json, backend/package.json, backend/redis-scripts/add-result.lua, backend/setup-tests.ts, backend/src/api/controllers/leaderboard.ts, backend/src/api/controllers/result.ts, backend/src/api/routes/leaderboards.ts, backend/src/constants/base-configuration.ts, backend/src/init/redis.ts, backend/src/server.ts, backend/src/types/types.d.ts, backend/src/utils/daily-leaderboards.ts, backend/src/utils/misc.ts
- Setups the required logic and code paths to support daily leaderboards
=> Setup daily leaderboards backend

frontend/src/ts/ape/endpoints/leaderboards.ts, frontend/src/ts/ape/types/ape.d.ts
- To be merged first: https://github.com/monkeytypegame/monkeytype/pull/2987
=> Add Ape endpoint for daily leaderboard

backend/redis-scripts/add-result.lua, backend/redis-scripts/get-results.lua, backend/src/api/controllers/leaderboard.ts, backend/src/api/controllers/result.ts, backend/src/api/routes/leaderboards.ts, backend/src/utils/daily-leaderboards.ts
=> Daily leaderboards pagination

frontend/src/ts/controllers/account-controller.ts, frontend/src/ts/pages/login.ts, frontend/static/html/pages/login.html
=> Add checks for password and email on signup and add field indicators for them

backend/__tests__/dal/ape-keys.spec.ts, backend/src/api/controllers/leaderboard.ts, backend/src/api/controllers/result.ts, backend/src/api/routes/leaderboards.ts, backend/src/utils/daily-leaderboards.ts, frontend/src/ts/ape/endpoints/leaderboards.ts, frontend/src/ts/ape/types/ape.d.ts, frontend/src/ts/elements/leaderboards.ts
=> Add daily leaderboard rank

backend/__tests__/utils/daily-leaderboards.spec.ts, backend/src/constants/base-configuration.ts, backend/src/jobs/announce-daily-leaderboards.ts, backend/src/jobs/index.ts, backend/src/tasks/george.ts, backend/src/types/types.d.ts, backend/src/utils/daily-leaderboards.ts
=> Announce top daily leaderboard results

backend/src/utils/daily-leaderboards.ts
=> Add rank in daily leaderboard results

backend/src/constants/monkey-status-codes.ts, backend/src/dal/new-quotes.ts, frontend/src/ts/controllers/sound-controller.ts, frontend/src/ts/controllers/verification-controller.ts, frontend/src/ts/elements/monkey-power.ts, frontend/src/ts/pages/account.ts, frontend/src/ts/pages/settings.ts, frontend/src/ts/popups/cookie-popup.ts, frontend/src/ts/popups/quote-approve-popup.ts, frontend/src/ts/popups/quote-rate-popup.ts, frontend/src/ts/popups/quote-report-popup.ts, frontend/src/ts/popups/simple-popups.ts, frontend/src/ts/test/custom-text.ts, frontend/src/ts/test/test-input.ts, frontend/src/ts/test/test-stats.ts, frontend/src/ts/types/types.d.ts, frontend/src/ts/utils/misc.ts
=> use interfaces instead of types

backend/__tests__/dal/ape-keys.spec.ts, backend/__tests__/utils/daily-leaderboards.spec.ts, backend/__tests__/utils/misc.spec.ts, backend/package-lock.json, backend/package.json, backend/redis-scripts/add-result.lua, backend/redis-scripts/get-results.lua, backend/setup-tests.ts, backend/src/api/controllers/leaderboard.ts, backend/src/api/controllers/result.ts, backend/src/api/routes/leaderboards.ts, backend/src/constants/base-configuration.ts, backend/src/init/redis.ts, backend/src/jobs/announce-daily-leaderboards.ts, backend/src/jobs/index.ts, backend/src/server.ts, backend/src/tasks/george.ts, backend/src/types/types.d.ts, backend/src/utils/daily-leaderboards.ts, backend/src/utils/misc.ts, frontend/src/styles/leaderboards.scss, frontend/src/styles/z_media-queries.scss, frontend/src/ts/ape/endpoints/leaderboards.ts, frontend/src/ts/ape/types/ape.d.ts, frontend/src/ts/elements/leaderboards.ts, frontend/src/ts/test/test-logic.ts, frontend/static/html/popups.html
=> Add daily leaderboards

backend/__tests__/utils/misc.spec.ts, backend/src/utils/daily-leaderboards.ts, backend/src/utils/misc.ts
=> Use better score metric for daily leaderboards

README.md
Just fixing a broken link within the readme.
Closes #
Code of conduct link doesn't give a 404
=> Code of conduct link fix

backend/src/jobs/announce-daily-leaderboards.ts, backend/src/jobs/delete-old-logs.ts, backend/src/jobs/update-leaderboards.ts
=> Add maintenance check for cron jobs

frontend/static/quotes/english.json
=> Added english quote

backend/src/init/redis.ts
- Checks Redis connection status to make sure it is ready
=> Check redis status when getting client connection

backend/src/api/controllers/user.ts, backend/src/api/routes/users.ts, backend/src/dal/user.ts, frontend/src/styles/settings.scss, frontend/src/ts/ape/endpoints/users.ts, frontend/src/ts/controllers/account-controller.ts, frontend/src/ts/controllers/verification-controller.ts, frontend/src/ts/ui.ts, frontend/static/html/pages/settings.html
- Updating avatar now goes through the same code path as linking
=> Update discord avatar

package-lock.json, package.json
Bump up version to match the concurrently versions of the frontend and the backend directory
=> Bump up concurrently version

frontend/static/.well-known/security.txt
`security.txt` had an expiry date of 2022-06-03T21:00:00.000Z. This moves the expiry date one year later.
=> update security.txt expiry date

frontend/static/quotes/english.json
=> Added an English Quote

.github/workflows/pretty-fix.yml
=> Add git config

backend/src/api/controllers/leaderboard.ts, backend/src/api/controllers/result.ts, backend/src/dal/leaderboards.ts, backend/src/documentation/public-swagger.json, backend/src/types/types.d.ts, backend/src/utils/daily-leaderboards.ts, frontend/src/ts/types/types.d.ts
- Adds discord avatar and badges to leaderboard entry
- Updated leaderboard entry for leaderboards to be more consistent with daily entry
- Updated documentation
=> Add leaderboard avatars and badges

backend/private/style.css
=> Fix lines stylinh

frontend/src/ts/controllers/badge-controller.ts, frontend/src/ts/elements/leaderboards.ts
=> Refactor avatar logic and badges

backend/src/api/controllers/leaderboard.ts, backend/src/api/routes/leaderboards.ts, backend/src/server.ts, backend/src/utils/daily-leaderboards.ts, backend/src/utils/misc.ts, frontend/src/styles/leaderboards.scss, frontend/src/styles/z_media-queries.scss, frontend/src/ts/ape/endpoints/leaderboards.ts, frontend/src/ts/elements/leaderboards.ts, frontend/static/html/popups.html
=> Add logic to handle fetching previous daily leaderboards

frontend/src/ts/elements/leaderboards.ts
=> Fix yesterday toggle button

backend/__tests__/dal/user.spec.ts, backend/src/api/controllers/user.ts, backend/src/api/routes/users.ts, backend/src/constants/base-configuration.ts, backend/src/dal/user.ts, backend/src/types/types.d.ts
Rename Custom Filters to Result Filter Presets
=> Rename customFilters -> resultFilterPresets

frontend/src/styles/inputs.scss, frontend/src/styles/leaderboards.scss, frontend/src/styles/z_media-queries.scss, frontend/src/ts/elements/leaderboards.ts, frontend/static/html/popups.html
- Adds a language selector for leaderboards
- Still need to compile a list of languages we want to support
=> Add leaderboard language selection

backend/__tests__/dal/user.spec.ts, backend/__tests__/utils/misc.spec.ts, backend/jest.config.ts, backend/src/api/controllers/user.ts, backend/src/api/routes/users.ts, backend/src/constants/base-configuration.ts, backend/src/dal/user.ts, backend/src/middlewares/rate-limit.ts, backend/src/types/types.d.ts, backend/src/utils/misc.ts
=> Add user profile API

frontend/src/ts/test/test-logic.ts
- Includes language in daily lb notification
=> Include language in daily lb notification

frontend/static/quotes/indonesian.json
Exactly what the title says, from id: 151-170.
=> Add 20 more Indonesian quotes, 151-170

frontend/static/themes/_list.json, frontend/static/themes/hedge.css
=> add hedge theme

backend/src/dal/user.ts
- Refactors add user for less queries
=> Refactor add user

frontend/src/ts/elements/psa.ts
=> added psa request failed notification

frontend/src/ts/controllers/badge-controller.ts
@Miodec please edit the description fields to whatever you see fit. This is what the icons look like:
Closes [#3156]
=> create supporter and sugar daddy badges

frontend/static/challenges/_list.json, frontend/static/challenges/sourcecode.txt
also added messages for accuracy tests and autorole for accuracy test
=> added missing challenge 
